#! /bin/sh
# Copyright (C) 2013 Maxim Zakharov. All rights reserved.
# Copyright (C) 2003-2012 DataPark Ltd. All rights reserved.
# Copyright (C) 2003 Lavtech.com corp. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA 

if test -z "$LIBTOOLIZE" -a "`uname`" = "Darwin"; then
  LIBTOOLIZE=glibtoolize
fi

set +x
echo "aclocal"
${ACLOCAL:-aclocal} \
&& echo "libtoolize" \
&& ${LIBTOOLIZE:-libtoolize} --copy --force \
&& echo "automake" \
&& ${AUTOMAKE:-automake} --foreign --force-missing --add-missing --copy Makefile \
&& echo "automake 2nd" \
&& ${AUTOMAKE:-automake} -a --copy \
&& echo "autoconf" \
&& ${AUTOCONF:-autoconf} \
&& echo "Done."


