#! /bin/sh
echo "aclocal"
aclocal \
&& echo "libtoolize" \
&& libtoolize --copy --force \
&& echo "automake" \
&& automake --foreign --force-missing --add-missing --copy Makefile \
&& echo "automake 2nd" \
&& automake -a --copy \
&& echo "autoconf" \
&& autoconf \
&& echo "Done."


