Document: dpsearch
Title: Debian dpsearch Manual
Author: <insert document author here>
Abstract: This manual describes what dpsearch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dpsearch/dpsearch.sgml.gz

Format: postscript
Files: /usr/share/doc/dpsearch/dpsearch.ps.gz

Format: text
Files: /usr/share/doc/dpsearch/dpsearch.text.gz

Format: HTML
Index: /usr/share/doc/dpsearch/html/index.html
Files: /usr/share/doc/dpsearch/html/*.html

  
