{ "AElig", 	0x000C6, 	0x0 }, 	/* =capital AE diphthong (ligature) : 9573-2003-isolat1*/
{ "AMP", 	0x00026, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "Aacgr", 	0x00386, 	0x0 }, 	/* =capital Alpha, accent, Greek : 9573-2003-isogrk2*/
{ "Aacute", 	0x000C1, 	0x0 }, 	/* =capital A, acute accent : 9573-2003-isolat1*/
{ "Abreve", 	0x00102, 	0x0 }, 	/* =capital A, breve : 9573-2003-isolat2*/
{ "Acirc", 	0x000C2, 	0x0 }, 	/* =capital A, circumflex accent : 9573-2003-isolat1*/
{ "Acy", 	0x00410, 	0x0 }, 	/* =capital A, Cyrillic : 9573-2003-isocyr1*/
{ "Afr", 	0x1D504, 	0x0 }, 	/* /frak A, upper case a : 9573-2003-isomfrk*/
{ "Agr", 	0x00391, 	0x0 }, 	/* =capital Alpha, Greek : 9573-2003-isogrk1*/
{ "Agrave", 	0x000C0, 	0x0 }, 	/* =capital A, grave accent : 9573-2003-isolat1*/
{ "Alpha", 	0x00391, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Amacr", 	0x00100, 	0x0 }, 	/* =capital A, macron : 9573-2003-isolat2*/
{ "And", 	0x02A53, 	0x0 }, 	/* dbl logical and : 9573-2003-isotech*/
{ "Aogon", 	0x00104, 	0x0 }, 	/* =capital A, ogonek : 9573-2003-isolat2*/
{ "Aopf", 	0x1D538, 	0x0 }, 	/* /Bbb A, open face A : 9573-2003-isomopf*/
{ "ApplyFunction", 	0x02061, 	0x0 }, 	/* character showing function application in presentation tagging : mmlalias*/
{ "Aring", 	0x000C5, 	0x0 }, 	/* =capital A, ring : 9573-2003-isolat1*/
{ "Ascr", 	0x1D49C, 	0x0 }, 	/* /scr A, script letter A : 9573-2003-isomscr*/
{ "Assign", 	0x02254, 	0x0 }, 	/* assignment operator, alias ISOAMSR colone : mmlalias*/
{ "Ast", 	0x02051, 	0x0 }, 	/*  : STIX*/
{ "Atilde", 	0x000C3, 	0x0 }, 	/* =capital A, tilde : 9573-2003-isolat1*/
{ "Auml", 	0x000C4, 	0x0 }, 	/* =capital A, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "Backslash", 	0x02216, 	0x0 }, 	/* alias ISOAMSB setmn : mmlalias*/
{ "Barint", 	0x02A0E, 	0x0 }, 	/*  : STIX*/
{ "Barv", 	0x02AE7, 	0x0 }, 	/* vert, dbl bar (over) : 9573-2003-isoamsr*/
{ "Barwed", 	0x02306, 	0x0 }, 	/* /doublebarwedge B: log and, dbl bar above : 9573-2003-isoamsb*/
{ "Barwedl", 	0x02A5E, 	0x0 }, 	/* 2306 : STIX*/
{ "Bcy", 	0x00411, 	0x0 }, 	/* =capital BE, Cyrillic : 9573-2003-isocyr1*/
{ "Because", 	0x02235, 	0x0 }, 	/* alias ISOTECH becaus : mmlalias*/
{ "Bernoullis", 	0x0212C, 	0x0 }, 	/* alias ISOTECH bernou : mmlalias*/
{ "Beta", 	0x00392, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Bfr", 	0x1D505, 	0x0 }, 	/* /frak B, upper case b : 9573-2003-isomfrk*/
{ "Bgr", 	0x00392, 	0x0 }, 	/* =capital Beta, Greek : 9573-2003-isogrk1*/
{ "Bopf", 	0x1D539, 	0x0 }, 	/* /Bbb B, open face B : 9573-2003-isomopf*/
{ "Breve", 	0x002D8, 	0x0 }, 	/* alias ISODIA breve : mmlalias*/
{ "Bscr", 	0x0212C, 	0x0 }, 	/* /scr B, script letter B : 9573-2003-isomscr*/
{ "Bumpeq", 	0x0224E, 	0x0 }, 	/* alias ISOAMSR bump : mmlalias*/
{ "Bvert", 	0x02506, 	0x0 }, 	/*  : STIX*/
{ "CHcy", 	0x00427, 	0x0 }, 	/* =capital CHE, Cyrillic : 9573-2003-isocyr1*/
{ "COPY", 	0x000A9, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "Cacute", 	0x00106, 	0x0 }, 	/* =capital C, acute accent : 9573-2003-isolat2*/
{ "Cap", 	0x022D2, 	0x0 }, 	/* /Cap /doublecap B: dbl intersection : 9573-2003-isoamsb*/
{ "CapitalDifferentialD", 	0x02145, 	0x0 }, 	/* D for use in differentials, e.g., within integrals : mmlalias*/
{ "Cayleys", 	0x0212D, 	0x0 }, 	/* the non-associative ring of octonions or Cayley numbers : mmlalias*/
{ "Ccaron", 	0x0010C, 	0x0 }, 	/* =capital C, caron : 9573-2003-isolat2*/
{ "Ccedil", 	0x000C7, 	0x0 }, 	/* =capital C, cedilla : 9573-2003-isolat1*/
{ "Ccirc", 	0x00108, 	0x0 }, 	/* =capital C, circumflex accent : 9573-2003-isolat2*/
{ "Cconint", 	0x02230, 	0x0 }, 	/* triple contour integral operator : 9573-2003-isotech*/
{ "Cdot", 	0x0010A, 	0x0 }, 	/* =capital C, dot above : 9573-2003-isolat2*/
{ "Cedilla", 	0x000B8, 	0x0 }, 	/* alias ISODIA cedil : mmlalias*/
{ "CenterDot", 	0x000B7, 	0x0 }, 	/* alias ISONUM middot : mmlalias*/
{ "Cfr", 	0x0212D, 	0x0 }, 	/* /frak C, upper case c : 9573-2003-isomfrk*/
{ "Chi", 	0x003A7, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "CircleDot", 	0x02299, 	0x0 }, 	/* alias ISOAMSB odot : mmlalias*/
{ "CircleMinus", 	0x02296, 	0x0 }, 	/* alias ISOAMSB ominus : mmlalias*/
{ "CirclePlus", 	0x02295, 	0x0 }, 	/* alias ISOAMSB oplus : mmlalias*/
{ "CircleTimes", 	0x02297, 	0x0 }, 	/* alias ISOAMSB otimes : mmlalias*/
{ "ClockwiseContourIntegral", 	0x02232, 	0x0 }, 	/* alias ISOTECH cwconint : mmlalias*/
{ "CloseCurlyDoubleQuote", 	0x0201D, 	0x0 }, 	/* alias ISONUM rdquo : mmlalias*/
{ "CloseCurlyQuote", 	0x02019, 	0x0 }, 	/* alias ISONUM rsquo : mmlalias*/
{ "Colon", 	0x02237, 	0x0 }, 	/* /Colon, two colons : 9573-2003-isoamsr*/
{ "Colone", 	0x02A74, 	0x0 }, 	/* double colon, equals : 9573-2003-isoamsr*/
{ "Congruent", 	0x02261, 	0x0 }, 	/* alias ISOTECH equiv : mmlalias*/
{ "Conint", 	0x0222F, 	0x0 }, 	/* double contour integral operator : 9573-2003-isotech*/
{ "ContourIntegral", 	0x0222E, 	0x0 }, 	/* alias ISOTECH conint : mmlalias*/
{ "Copf", 	0x02102, 	0x0 }, 	/* /Bbb C, open face C : 9573-2003-isomopf*/
{ "Coproduct", 	0x02210, 	0x0 }, 	/* alias ISOAMSB coprod : mmlalias*/
{ "CounterClockwiseContourIntegral", 	0x02233, 	0x0 }, 	/* alias ISOTECH awconint : mmlalias*/
{ "Cross", 	0x02A2F, 	0x0 }, 	/* cross or vector product : mmlextra*/
{ "Cscr", 	0x1D49E, 	0x0 }, 	/* /scr C, script letter C : 9573-2003-isomscr*/
{ "Cup", 	0x022D3, 	0x0 }, 	/* /Cup /doublecup B: dbl union : 9573-2003-isoamsb*/
{ "CupCap", 	0x0224D, 	0x0 }, 	/* alias asympeq : mmlalias*/
{ "DD", 	0x02145, 	0x0 }, 	/* D for use in differentials, e.g., within integrals : mmlextra*/
{ "DDotrahd", 	0x02911, 	0x0 }, 	/* right arrow with dotted stem : 9573-2003-isoamsa*/
{ "DJcy", 	0x00402, 	0x0 }, 	/* =capital DJE, Serbian : 9573-2003-isocyr2*/
{ "DScy", 	0x00405, 	0x0 }, 	/* =capital DSE, Macedonian : 9573-2003-isocyr2*/
{ "DZcy", 	0x0040F, 	0x0 }, 	/* =capital dze, Serbian : 9573-2003-isocyr2*/
{ "Dagger", 	0x02021, 	0x0 }, 	/* /ddagger B: double dagger relation : 9573-2003-isoamsb*/
{ "Darr", 	0x021A1, 	0x0 }, 	/* down two-headed arrow : 9573-2003-isoamsa*/
{ "Dashv", 	0x02AE4, 	0x0 }, 	/* dbl dash, vertical : 9573-2003-isoamsr*/
{ "Dcaron", 	0x0010E, 	0x0 }, 	/* =capital D, caron : 9573-2003-isolat2*/
{ "Dcy", 	0x00414, 	0x0 }, 	/* =capital DE, Cyrillic : 9573-2003-isocyr1*/
{ "Del", 	0x02207, 	0x0 }, 	/* alias ISOTECH nabla : mmlalias*/
{ "Delta", 	0x00394, 	0x0 }, 	/* /Delta capital Delta, Greek : 9573-2003-isogrk3*/
{ "Dfr", 	0x1D507, 	0x0 }, 	/* /frak D, upper case d : 9573-2003-isomfrk*/
{ "Dgr", 	0x00394, 	0x0 }, 	/* =capital Delta, Greek : 9573-2003-isogrk1*/
{ "DiacriticalAcute", 	0x000B4, 	0x0 }, 	/* alias ISODIA acute : mmlalias*/
{ "DiacriticalDot", 	0x002D9, 	0x0 }, 	/* alias ISODIA dot : mmlalias*/
{ "DiacriticalDoubleAcute", 	0x002DD, 	0x0 }, 	/* alias ISODIA dblac : mmlalias*/
{ "DiacriticalGrave", 	0x00060, 	0x0 }, 	/* alias ISODIA grave : mmlalias*/
{ "DiacriticalTilde", 	0x002DC, 	0x0 }, 	/* alias ISODIA tilde : mmlalias*/
{ "Diamond", 	0x022C4, 	0x0 }, 	/* alias ISOAMSB diam : mmlalias*/
{ "DifferentialD", 	0x02146, 	0x0 }, 	/* d for use in differentials, e.g., within integrals : mmlalias*/
{ "Dopf", 	0x1D53B, 	0x0 }, 	/* /Bbb D, open face D : 9573-2003-isomopf*/
{ "Dot", 	0x000A8, 	0x0 }, 	/* dieresis or umlaut mark : 9573-2003-isotech*/
{ "DotDot", 	0x020DC, 	0x0 }, 	/* four dots above : 9573-2003-isotech*/
{ "DotEqual", 	0x02250, 	0x0 }, 	/* alias ISOAMSR esdot : mmlalias*/
{ "DoubleContourIntegral", 	0x0222F, 	0x0 }, 	/* alias ISOTECH Conint : mmlalias*/
{ "DoubleDot", 	0x000A8, 	0x0 }, 	/* alias ISODIA die : mmlalias*/
{ "DoubleDownArrow", 	0x021D3, 	0x0 }, 	/* alias ISOAMSA dArr : mmlalias*/
{ "DoubleLeftArrow", 	0x021D0, 	0x0 }, 	/* alias ISOTECH lArr : mmlalias*/
{ "DoubleLeftRightArrow", 	0x021D4, 	0x0 }, 	/* alias ISOAMSA hArr : mmlalias*/
{ "DoubleLeftTee", 	0x02AE4, 	0x0 }, 	/* alias for  &Dashv;  : mmlalias*/
{ "DoubleLongLeftArrow", 	0x027F8, 	0x0 }, 	/* alias ISOAMSA xlArr : mmlalias*/
{ "DoubleLongLeftRightArrow", 	0x027FA, 	0x0 }, 	/* alias ISOAMSA xhArr : mmlalias*/
{ "DoubleLongRightArrow", 	0x027F9, 	0x0 }, 	/* alias ISOAMSA xrArr : mmlalias*/
{ "DoubleRightArrow", 	0x021D2, 	0x0 }, 	/* alias ISOTECH rArr : mmlalias*/
{ "DoubleRightTee", 	0x022A8, 	0x0 }, 	/* alias ISOAMSR vDash : mmlalias*/
{ "DoubleUpArrow", 	0x021D1, 	0x0 }, 	/* alias ISOAMSA uArr : mmlalias*/
{ "DoubleUpDownArrow", 	0x021D5, 	0x0 }, 	/* alias ISOAMSA vArr : mmlalias*/
{ "DoubleVerticalBar", 	0x02225, 	0x0 }, 	/* alias ISOTECH par : mmlalias*/
{ "DownArrow", 	0x02193, 	0x0 }, 	/* alias ISONUM darr : mmlalias*/
{ "DownArrowBar", 	0x02913, 	0x0 }, 	/* down arrow to bar : mmlextra*/
{ "DownArrowUpArrow", 	0x021F5, 	0x0 }, 	/* alias ISOAMSA duarr : mmlalias*/
{ "DownBreve", 	0x00311, 	0x0 }, 	/*  : mmlextra*/
{ "DownLeftRightVector", 	0x02950, 	0x0 }, 	/* left-down-right-down harpoon : mmlextra*/
{ "DownLeftTeeVector", 	0x0295E, 	0x0 }, 	/* left-down harpoon from bar : mmlextra*/
{ "DownLeftVector", 	0x021BD, 	0x0 }, 	/* alias ISOAMSA lhard : mmlalias*/
{ "DownLeftVectorBar", 	0x02956, 	0x0 }, 	/* left-down harpoon to bar : mmlextra*/
{ "DownRightTeeVector", 	0x0295F, 	0x0 }, 	/* right-down harpoon from bar : mmlextra*/
{ "DownRightVector", 	0x021C1, 	0x0 }, 	/* alias ISOAMSA rhard : mmlalias*/
{ "DownRightVectorBar", 	0x02957, 	0x0 }, 	/* right-down harpoon to bar : mmlextra*/
{ "DownTee", 	0x022A4, 	0x0 }, 	/* alias ISOTECH top : mmlalias*/
{ "DownTeeArrow", 	0x021A7, 	0x0 }, 	/* alias for mapstodown : mmlalias*/
{ "Downarrow", 	0x021D3, 	0x0 }, 	/* alias ISOAMSA dArr : mmlalias*/
{ "Dscr", 	0x1D49F, 	0x0 }, 	/* /scr D, script letter D : 9573-2003-isomscr*/
{ "Dstrok", 	0x00110, 	0x0 }, 	/* =capital D, stroke : 9573-2003-isolat2*/
{ "EEacgr", 	0x00389, 	0x0 }, 	/* =capital Eta, accent, Greek : 9573-2003-isogrk2*/
{ "EEgr", 	0x00397, 	0x0 }, 	/* =capital Eta, Greek : 9573-2003-isogrk1*/
{ "ENG", 	0x0014A, 	0x0 }, 	/* =capital ENG, Lapp : 9573-2003-isolat2*/
{ "ETH", 	0x000D0, 	0x0 }, 	/* =capital Eth, Icelandic : 9573-2003-isolat1*/
{ "Eacgr", 	0x00388, 	0x0 }, 	/* =capital Epsilon, accent, Greek : 9573-2003-isogrk2*/
{ "Eacute", 	0x000C9, 	0x0 }, 	/* =capital E, acute accent : 9573-2003-isolat1*/
{ "Ecaron", 	0x0011A, 	0x0 }, 	/* =capital E, caron : 9573-2003-isolat2*/
{ "Ecirc", 	0x000CA, 	0x0 }, 	/* =capital E, circumflex accent : 9573-2003-isolat1*/
{ "Ecy", 	0x0042D, 	0x0 }, 	/* =capital E, Cyrillic : 9573-2003-isocyr1*/
{ "Edot", 	0x00116, 	0x0 }, 	/* =capital E, dot above : 9573-2003-isolat2*/
{ "Efr", 	0x1D508, 	0x0 }, 	/* /frak E, upper case e : 9573-2003-isomfrk*/
{ "Egr", 	0x00395, 	0x0 }, 	/* =capital Epsilon, Greek : 9573-2003-isogrk1*/
{ "Egrave", 	0x000C8, 	0x0 }, 	/* =capital E, grave accent : 9573-2003-isolat1*/
{ "Element", 	0x02208, 	0x0 }, 	/* alias ISOTECH isinv : mmlalias*/
{ "Emacr", 	0x00112, 	0x0 }, 	/* =capital E, macron : 9573-2003-isolat2*/
{ "EmptySmallSquare", 	0x025FB, 	0x0 }, 	/* empty small square : mmlextra*/
{ "EmptyVerySmallSquare", 	0x025AB, 	0x0 }, 	/*  : mmlextra*/
{ "Eogon", 	0x00118, 	0x0 }, 	/* =capital E, ogonek : 9573-2003-isolat2*/
{ "Eopf", 	0x1D53C, 	0x0 }, 	/* /Bbb E, open face E : 9573-2003-isomopf*/
{ "Epsilon", 	0x00395, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Equal", 	0x02A75, 	0x0 }, 	/* two consecutive equal signs : mmlextra*/
{ "EqualTilde", 	0x02242, 	0x0 }, 	/* alias ISOAMSR esim : mmlalias*/
{ "Equilibrium", 	0x021CC, 	0x0 }, 	/* alias ISOAMSA rlhar : mmlalias*/
{ "Escr", 	0x02130, 	0x0 }, 	/* /scr E, script letter E : 9573-2003-isomscr*/
{ "Esim", 	0x02A73, 	0x0 }, 	/* equal, similar : 9573-2003-isoamsr*/
{ "Eta", 	0x00397, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Euml", 	0x000CB, 	0x0 }, 	/* =capital E, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "Exists", 	0x02203, 	0x0 }, 	/* alias ISOTECH exist : mmlalias*/
{ "ExponentialE", 	0x02147, 	0x0 }, 	/* e use for the exponential base of the natural logarithms : mmlalias*/
{ "Fcy", 	0x00424, 	0x0 }, 	/* =capital EF, Cyrillic : 9573-2003-isocyr1*/
{ "Ffr", 	0x1D509, 	0x0 }, 	/* /frak F, upper case f : 9573-2003-isomfrk*/
{ "FilledSmallSquare", 	0x025FC, 	0x0 }, 	/* filled small square : mmlextra*/
{ "FilledVerySmallSquare", 	0x025AA, 	0x0 }, 	/* filled very small square : mmlextra*/
{ "Fopf", 	0x1D53D, 	0x0 }, 	/* /Bbb F, open face F : 9573-2003-isomopf*/
{ "ForAll", 	0x02200, 	0x0 }, 	/* alias ISOTECH forall : mmlalias*/
{ "Fouriertrf", 	0x02131, 	0x0 }, 	/* Fourier transform : mmlalias*/
{ "Fscr", 	0x02131, 	0x0 }, 	/* /scr F, script letter F : 9573-2003-isomscr*/
{ "GJcy", 	0x00403, 	0x0 }, 	/* =capital GJE Macedonian : 9573-2003-isocyr2*/
{ "GT", 	0x0003E, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "Game", 	0x02141, 	0x0 }, 	/*  : STIX*/
{ "Gamma", 	0x00393, 	0x0 }, 	/* /Gamma capital Gamma, Greek : 9573-2003-isogrk3*/
{ "Gammad", 	0x003DC, 	0x0 }, 	/* capital digamma : 9573-2003-isogrk3*/
{ "Gbreve", 	0x0011E, 	0x0 }, 	/* =capital G, breve : 9573-2003-isolat2*/
{ "Gcedil", 	0x00122, 	0x0 }, 	/* =capital G, cedilla : 9573-2003-isolat2*/
{ "Gcirc", 	0x0011C, 	0x0 }, 	/* =capital G, circumflex accent : 9573-2003-isolat2*/
{ "Gcy", 	0x00413, 	0x0 }, 	/* =capital GHE, Cyrillic : 9573-2003-isocyr1*/
{ "Gdot", 	0x00120, 	0x0 }, 	/* =capital G, dot above : 9573-2003-isolat2*/
{ "Gfr", 	0x1D50A, 	0x0 }, 	/* /frak G, upper case g : 9573-2003-isomfrk*/
{ "Gg", 	0x022D9, 	0x0 }, 	/* /ggg /Gg /gggtr R: triple gtr-than : 9573-2003-isoamsr*/
{ "Ggr", 	0x00393, 	0x0 }, 	/* =capital Gamma, Greek : 9573-2003-isogrk1*/
{ "Gopf", 	0x1D53E, 	0x0 }, 	/* /Bbb G, open face G : 9573-2003-isomopf*/
{ "GreaterEqual", 	0x02265, 	0x0 }, 	/* alias ISOTECH ge : mmlalias*/
{ "GreaterEqualLess", 	0x022DB, 	0x0 }, 	/* alias ISOAMSR gel : mmlalias*/
{ "GreaterFullEqual", 	0x02267, 	0x0 }, 	/* alias ISOAMSR gE : mmlalias*/
{ "GreaterGreater", 	0x02AA2, 	0x0 }, 	/* alias for GT : mmlextra*/
{ "GreaterLess", 	0x02277, 	0x0 }, 	/* alias ISOAMSR gl : mmlalias*/
{ "GreaterSlantEqual", 	0x02A7E, 	0x0 }, 	/* alias ISOAMSR ges : mmlalias*/
{ "GreaterTilde", 	0x02273, 	0x0 }, 	/* alias ISOAMSR gsim : mmlalias*/
{ "Gscr", 	0x1D4A2, 	0x0 }, 	/* /scr G, script letter G : 9573-2003-isomscr*/
{ "Gt", 	0x0226B, 	0x0 }, 	/* /gg R: dbl greater-than sign : 9573-2003-isoamsr*/
{ "Gt", 	0x02AA2, 	0x0 }, 	/*  : STIX*/
{ "HARDcy", 	0x0042A, 	0x0 }, 	/* =capital HARD sign, Cyrillic : 9573-2003-isocyr1*/
{ "Hacek", 	0x002C7, 	0x0 }, 	/* alias ISODIA caron : mmlalias*/
{ "Hat", 	0x0005E, 	0x0 }, 	/*  : mmlextra*/
{ "Hcirc", 	0x00124, 	0x0 }, 	/* =capital H, circumflex accent : 9573-2003-isolat2*/
{ "Hfr", 	0x0210C, 	0x0 }, 	/* /frak H, upper case h : 9573-2003-isomfrk*/
{ "HilbertSpace", 	0x0210B, 	0x0 }, 	/* Hilbert space : mmlalias*/
{ "Hopf", 	0x0210D, 	0x0 }, 	/* /Bbb H, open face H : 9573-2003-isomopf*/
{ "HorizontalLine", 	0x02500, 	0x0 }, 	/* short horizontal line  : mmlextra*/
{ "Hscr", 	0x0210B, 	0x0 }, 	/* /scr H, script letter H : 9573-2003-isomscr*/
{ "Hstrok", 	0x00126, 	0x0 }, 	/* =capital H, stroke : 9573-2003-isolat2*/
{ "HumpDownHump", 	0x0224E, 	0x0 }, 	/* alias ISOAMSR bump : mmlalias*/
{ "HumpEqual", 	0x0224F, 	0x0 }, 	/* alias ISOAMSR bumpe : mmlalias*/
{ "IEcy", 	0x00415, 	0x0 }, 	/* =capital IE, Cyrillic : 9573-2003-isocyr1*/
{ "IJlig", 	0x00132, 	0x0 }, 	/* =capital IJ ligature : 9573-2003-isolat2*/
{ "IOcy", 	0x00401, 	0x0 }, 	/* =capital IO, Russian : 9573-2003-isocyr1*/
{ "Iacgr", 	0x0038A, 	0x0 }, 	/* =capital Iota, accent, Greek : 9573-2003-isogrk2*/
{ "Iacute", 	0x000CD, 	0x0 }, 	/* =capital I, acute accent : 9573-2003-isolat1*/
{ "Icirc", 	0x000CE, 	0x0 }, 	/* =capital I, circumflex accent : 9573-2003-isolat1*/
{ "Icy", 	0x00418, 	0x0 }, 	/* =capital I, Cyrillic : 9573-2003-isocyr1*/
{ "Idigr", 	0x003AA, 	0x0 }, 	/* =capital Iota, dieresis, Greek : 9573-2003-isogrk2*/
{ "Idot", 	0x00130, 	0x0 }, 	/* =capital I, dot above : 9573-2003-isolat2*/
{ "Ifr", 	0x02111, 	0x0 }, 	/* /frak I, upper case i : 9573-2003-isomfrk*/
{ "Igr", 	0x00399, 	0x0 }, 	/* =capital Iota, Greek : 9573-2003-isogrk1*/
{ "Igrave", 	0x000CC, 	0x0 }, 	/* =capital I, grave accent : 9573-2003-isolat1*/
{ "Im", 	0x02111, 	0x0 }, 	/* alias ISOAMSO image : mmlalias*/
{ "Imacr", 	0x0012A, 	0x0 }, 	/* =capital I, macron : 9573-2003-isolat2*/
{ "ImaginaryI", 	0x02148, 	0x0 }, 	/* i for use as a square root of -1 : mmlalias*/
{ "Implies", 	0x021D2, 	0x0 }, 	/* alias ISOTECH rArr : mmlalias*/
{ "Int", 	0x0222C, 	0x0 }, 	/* double integral operator : 9573-2003-isotech*/
{ "Integral", 	0x0222B, 	0x0 }, 	/* alias ISOTECH int : mmlalias*/
{ "Intersection", 	0x022C2, 	0x0 }, 	/* alias ISOAMSB xcap : mmlalias*/
{ "InvisibleComma", 	0x02063, 	0x0 }, 	/* used as a separator, e.g., in indices : mmlalias*/
{ "InvisibleTimes", 	0x02062, 	0x0 }, 	/* marks multiplication when it is understood without a mark : mmlalias*/
{ "Iogon", 	0x0012E, 	0x0 }, 	/* =capital I, ogonek : 9573-2003-isolat2*/
{ "Iopf", 	0x1D540, 	0x0 }, 	/* /Bbb I, open face I : 9573-2003-isomopf*/
{ "Iota", 	0x00399, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Iscr", 	0x02110, 	0x0 }, 	/* /scr I, script letter I : 9573-2003-isomscr*/
{ "Itilde", 	0x00128, 	0x0 }, 	/* =capital I, tilde : 9573-2003-isolat2*/
{ "Iukcy", 	0x00406, 	0x0 }, 	/* =capital I, Ukrainian : 9573-2003-isocyr2*/
{ "Iuml", 	0x000CF, 	0x0 }, 	/* =capital I, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "Jcirc", 	0x00134, 	0x0 }, 	/* =capital J, circumflex accent : 9573-2003-isolat2*/
{ "Jcy", 	0x00419, 	0x0 }, 	/* =capital short I, Cyrillic : 9573-2003-isocyr1*/
{ "Jfr", 	0x1D50D, 	0x0 }, 	/* /frak J, upper case j : 9573-2003-isomfrk*/
{ "Jopf", 	0x1D541, 	0x0 }, 	/* /Bbb J, open face J : 9573-2003-isomopf*/
{ "Jscr", 	0x1D4A5, 	0x0 }, 	/* /scr J, script letter J : 9573-2003-isomscr*/
{ "Jsercy", 	0x00408, 	0x0 }, 	/* =capital JE, Serbian : 9573-2003-isocyr2*/
{ "Jukcy", 	0x00404, 	0x0 }, 	/* =capital JE, Ukrainian : 9573-2003-isocyr2*/
{ "KHcy", 	0x00425, 	0x0 }, 	/* =capital HA, Cyrillic : 9573-2003-isocyr1*/
{ "KHgr", 	0x003A7, 	0x0 }, 	/* =capital Chi, Greek : 9573-2003-isogrk1*/
{ "KJcy", 	0x0040C, 	0x0 }, 	/* =capital KJE, Macedonian : 9573-2003-isocyr2*/
{ "Kappa", 	0x0039A, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Kcedil", 	0x00136, 	0x0 }, 	/* =capital K, cedilla : 9573-2003-isolat2*/
{ "Kcy", 	0x0041A, 	0x0 }, 	/* =capital KA, Cyrillic : 9573-2003-isocyr1*/
{ "Kfr", 	0x1D50E, 	0x0 }, 	/* /frak K, upper case k : 9573-2003-isomfrk*/
{ "Kgr", 	0x0039A, 	0x0 }, 	/* =capital Kappa, Greek : 9573-2003-isogrk1*/
{ "Kopf", 	0x1D542, 	0x0 }, 	/* /Bbb K, open face K  : 9573-2003-isomopf*/
{ "Kscr", 	0x1D4A6, 	0x0 }, 	/* /scr K, script letter K : 9573-2003-isomscr*/
{ "LJcy", 	0x00409, 	0x0 }, 	/* =capital LJE, Serbian : 9573-2003-isocyr2*/
{ "LT", 	0x0003C, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "Lacute", 	0x00139, 	0x0 }, 	/* =capital L, acute accent : 9573-2003-isolat2*/
{ "Lambda", 	0x0039B, 	0x0 }, 	/* /Lambda capital Lambda, Greek : 9573-2003-isogrk3*/
{ "Lang", 	0x027EA, 	0x0 }, 	/* left angle bracket, double : 9573-2003-isotech*/
{ "Laplacetrf", 	0x02112, 	0x0 }, 	/* Laplace transform : mmlalias*/
{ "Larr", 	0x0219E, 	0x0 }, 	/* /twoheadleftarrow A: : 9573-2003-isoamsa*/
{ "Lcaron", 	0x0013D, 	0x0 }, 	/* =capital L, caron : 9573-2003-isolat2*/
{ "Lcedil", 	0x0013B, 	0x0 }, 	/* =capital L, cedilla : 9573-2003-isolat2*/
{ "Lcy", 	0x0041B, 	0x0 }, 	/* =capital EL, Cyrillic : 9573-2003-isocyr1*/
{ "LeftAngleBracket", 	0x027E8, 	0x0 }, 	/* alias ISOTECH lang : mmlalias*/
{ "LeftArrow", 	0x02190, 	0x0 }, 	/* alias ISONUM larr : mmlalias*/
{ "LeftArrowBar", 	0x021E4, 	0x0 }, 	/* alias for larrb : mmlalias*/
{ "LeftArrowRightArrow", 	0x021C6, 	0x0 }, 	/* alias ISOAMSA lrarr : mmlalias*/
{ "LeftCeiling", 	0x02308, 	0x0 }, 	/* alias ISOAMSC lceil : mmlalias*/
{ "LeftDoubleBracket", 	0x027E6, 	0x0 }, 	/* left double bracket delimiter : mmlalias*/
{ "LeftDownTeeVector", 	0x02961, 	0x0 }, 	/* down-left harpoon from bar : mmlextra*/
{ "LeftDownVector", 	0x021C3, 	0x0 }, 	/* alias ISOAMSA dharl : mmlalias*/
{ "LeftDownVectorBar", 	0x02959, 	0x0 }, 	/* down-left harpoon to bar : mmlextra*/
{ "LeftFloor", 	0x0230A, 	0x0 }, 	/* alias ISOAMSC lfloor : mmlalias*/
{ "LeftRightArrow", 	0x02194, 	0x0 }, 	/* alias ISOAMSA harr : mmlalias*/
{ "LeftRightVector", 	0x0294E, 	0x0 }, 	/* left-up-right-up harpoon : mmlextra*/
{ "LeftTee", 	0x022A3, 	0x0 }, 	/* alias ISOAMSR dashv : mmlalias*/
{ "LeftTeeArrow", 	0x021A4, 	0x0 }, 	/* alias for mapstoleft : mmlalias*/
{ "LeftTeeVector", 	0x0295A, 	0x0 }, 	/* left-up harpoon from bar : mmlextra*/
{ "LeftTriangle", 	0x022B2, 	0x0 }, 	/* alias ISOAMSR vltri : mmlalias*/
{ "LeftTriangleBar", 	0x029CF, 	0x0 }, 	/* left triangle, vertical bar : mmlextra*/
{ "LeftTriangleEqual", 	0x022B4, 	0x0 }, 	/* alias ISOAMSR ltrie : mmlalias*/
{ "LeftUpDownVector", 	0x02951, 	0x0 }, 	/* up-left-down-left harpoon : mmlextra*/
{ "LeftUpTeeVector", 	0x02960, 	0x0 }, 	/* up-left harpoon from bar : mmlextra*/
{ "LeftUpVector", 	0x021BF, 	0x0 }, 	/* alias ISOAMSA uharl : mmlalias*/
{ "LeftUpVectorBar", 	0x02958, 	0x0 }, 	/* up-left harpoon to bar : mmlextra*/
{ "LeftVector", 	0x021BC, 	0x0 }, 	/* alias ISOAMSA lharu : mmlalias*/
{ "LeftVectorBar", 	0x02952, 	0x0 }, 	/* left-up harpoon to bar : mmlextra*/
{ "Leftarrow", 	0x021D0, 	0x0 }, 	/* alias ISOTECH lArr : mmlalias*/
{ "Leftrightarrow", 	0x021D4, 	0x0 }, 	/* alias ISOAMSA hArr : mmlalias*/
{ "LessEqualGreater", 	0x022DA, 	0x0 }, 	/* alias ISOAMSR leg : mmlalias*/
{ "LessFullEqual", 	0x02266, 	0x0 }, 	/* alias ISOAMSR lE : mmlalias*/
{ "LessGreater", 	0x02276, 	0x0 }, 	/* alias ISOAMSR lg : mmlalias*/
{ "LessLess", 	0x02AA1, 	0x0 }, 	/* alias for Lt : mmlextra*/
{ "LessSlantEqual", 	0x02A7D, 	0x0 }, 	/* alias ISOAMSR les : mmlalias*/
{ "LessTilde", 	0x02272, 	0x0 }, 	/* alias ISOAMSR lsim : mmlalias*/
{ "Lfr", 	0x1D50F, 	0x0 }, 	/* /frak L, upper case l : 9573-2003-isomfrk*/
{ "Lgr", 	0x0039B, 	0x0 }, 	/* =capital Lambda, Greek : 9573-2003-isogrk1*/
{ "Ll", 	0x022D8, 	0x0 }, 	/* /Ll /lll /llless R: triple less-than : 9573-2003-isoamsr*/
{ "Lleftarrow", 	0x021DA, 	0x0 }, 	/* alias ISOAMSA lAarr : mmlalias*/
{ "Lmidot", 	0x0013F, 	0x0 }, 	/* =capital L, middle dot : 9573-2003-isolat2*/
{ "LongLeftArrow", 	0x027F5, 	0x0 }, 	/* alias ISOAMSA xlarr : mmlalias*/
{ "LongLeftRightArrow", 	0x027F7, 	0x0 }, 	/* alias ISOAMSA xharr : mmlalias*/
{ "LongRightArrow", 	0x027F6, 	0x0 }, 	/* alias ISOAMSA xrarr : mmlalias*/
{ "Longleftarrow", 	0x027F8, 	0x0 }, 	/* alias ISOAMSA xlArr : mmlalias*/
{ "Longleftrightarrow", 	0x027FA, 	0x0 }, 	/* alias ISOAMSA xhArr : mmlalias*/
{ "Longrightarrow", 	0x027F9, 	0x0 }, 	/* alias ISOAMSA xrArr : mmlalias*/
{ "Lopf", 	0x1D543, 	0x0 }, 	/* /Bbb L, open face L  : 9573-2003-isomopf*/
{ "LowerLeftArrow", 	0x02199, 	0x0 }, 	/* alias ISOAMSA swarr : mmlalias*/
{ "LowerRightArrow", 	0x02198, 	0x0 }, 	/* alias ISOAMSA searr : mmlalias*/
{ "Lscr", 	0x02112, 	0x0 }, 	/* /scr L, script letter L : 9573-2003-isomscr*/
{ "Lsh", 	0x021B0, 	0x0 }, 	/* alias ISOAMSA lsh : mmlalias*/
{ "Lstrok", 	0x00141, 	0x0 }, 	/* =capital L, stroke : 9573-2003-isolat2*/
{ "Lt", 	0x0226A, 	0x0 }, 	/* /ll R: double less-than sign : 9573-2003-isoamsr*/
{ "Lt", 	0x02AA1, 	0x0 }, 	/*  : STIX*/
{ "Ltbar", 	0x02AA3, 	0x0 }, 	/*  : STIX*/
{ "Map", 	0x02905, 	0x0 }, 	/* twoheaded mapsto : 9573-2003-isoamsa*/
{ "Mapfrom", 	0x02906, 	0x0 }, 	/* E834 : STIX*/
{ "Mapto", 	0x02907, 	0x0 }, 	/* E835 : STIX*/
{ "Mcy", 	0x0041C, 	0x0 }, 	/* =capital EM, Cyrillic : 9573-2003-isocyr1*/
{ "MediumSpace", 	0x0205F, 	0x0 }, 	/*  : mmlextra*/
{ "Mellintrf", 	0x02133, 	0x0 }, 	/* Mellin transform : mmlalias*/
{ "Mfr", 	0x1D510, 	0x0 }, 	/* /frak M, upper case m : 9573-2003-isomfrk*/
{ "Mgr", 	0x0039C, 	0x0 }, 	/* =capital Mu, Greek : 9573-2003-isogrk1*/
{ "MinusPlus", 	0x02213, 	0x0 }, 	/* alias ISOTECH mnplus : mmlalias*/
{ "Mopf", 	0x1D544, 	0x0 }, 	/* /Bbb M, open face M  : 9573-2003-isomopf*/
{ "Mscr", 	0x02133, 	0x0 }, 	/* /scr M, script letter M : 9573-2003-isomscr*/
{ "Mu", 	0x0039C, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "NJcy", 	0x0040A, 	0x0 }, 	/* =capital NJE, Serbian : 9573-2003-isocyr2*/
{ "Nacute", 	0x00143, 	0x0 }, 	/* =capital N, acute accent : 9573-2003-isolat2*/
{ "Ncaron", 	0x00147, 	0x0 }, 	/* =capital N, caron : 9573-2003-isolat2*/
{ "Ncedil", 	0x00145, 	0x0 }, 	/* =capital N, cedilla : 9573-2003-isolat2*/
{ "Ncy", 	0x0041D, 	0x0 }, 	/* =capital EN, Cyrillic : 9573-2003-isocyr1*/
{ "NegativeMediumSpace", 	0x0200B, 	0x0 }, 	/* space of width -4/18 em : mmlalias*/
{ "NegativeThickSpace", 	0x0200B, 	0x0 }, 	/* space of width -5/18 em : mmlalias*/
{ "NegativeThinSpace", 	0x0200B, 	0x0 }, 	/* space of width -3/18 em : mmlalias*/
{ "NegativeVeryThinSpace", 	0x0200B, 	0x0 }, 	/* space of width -1/18 em : mmlalias*/
{ "NestedGreaterGreater", 	0x0226B, 	0x0 }, 	/* alias ISOAMSR Gt : mmlalias*/
{ "NestedLessLess", 	0x0226A, 	0x0 }, 	/* alias ISOAMSR Lt : mmlalias*/
{ "NewLine", 	0x0000A, 	0x0 }, 	/*  : mmlextra*/
{ "Nfr", 	0x1D511, 	0x0 }, 	/* /frak N, upper case n : 9573-2003-isomfrk*/
{ "Ngr", 	0x0039D, 	0x0 }, 	/* =capital Nu, Greek : 9573-2003-isogrk1*/
{ "NoBreak", 	0x02060, 	0x0 }, 	/*  : mmlextra*/
{ "NonBreakingSpace", 	0x000A0, 	0x0 }, 	/* alias ISONUM nbsp : mmlalias*/
{ "Nopf", 	0x02115, 	0x0 }, 	/* /Bbb N, open face N : 9573-2003-isomopf*/
{ "Not", 	0x02AEC, 	0x0 }, 	/* not with two horizontal strokes : 9573-2003-isotech*/
{ "NotCongruent", 	0x02262, 	0x0 }, 	/* alias ISOAMSN nequiv : mmlalias*/
{ "NotCupCap", 	0x0226D, 	0x0 }, 	/*  : mmlextra*/
{ "NotDoubleVerticalBar", 	0x02226, 	0x0 }, 	/* alias ISOAMSN npar : mmlalias*/
{ "NotElement", 	0x02209, 	0x0 }, 	/* alias ISOTECH notin : mmlalias*/
{ "NotEqual", 	0x02260, 	0x0 }, 	/* alias ISOTECH ne : mmlalias*/
{ "NotEqualTilde", 	0x02242, 	0x00338 }, 	/* alias for  &nesim; : mmlalias*/
{ "NotExists", 	0x02204, 	0x0 }, 	/* alias ISOAMSO nexist : mmlalias*/
{ "NotGreater", 	0x0226F, 	0x0 }, 	/* alias ISOAMSN ngt : mmlalias*/
{ "NotGreaterEqual", 	0x02271, 	0x0 }, 	/* alias ISOAMSN nge : mmlalias*/
{ "NotGreaterFullEqual", 	0x02267, 	0x00338 }, 	/* alias ISOAMSN ngE : mmlalias*/
{ "NotGreaterGreater", 	0x0226B, 	0x00338 }, 	/* alias ISOAMSN nGtv : mmlalias*/
{ "NotGreaterLess", 	0x02279, 	0x0 }, 	/* alias ISOAMSN ntvgl : mmlalias*/
{ "NotGreaterSlantEqual", 	0x02A7E, 	0x00338 }, 	/* alias ISOAMSN nges : mmlalias*/
{ "NotGreaterTilde", 	0x02275, 	0x0 }, 	/* alias ISOAMSN ngsim : mmlalias*/
{ "NotHumpDownHump", 	0x0224E, 	0x00338 }, 	/* alias for &nbump; : mmlalias*/
{ "NotHumpEqual", 	0x0224F, 	0x00338 }, 	/* alias for &nbumpe; : mmlextra*/
{ "NotLeftTriangle", 	0x022EA, 	0x0 }, 	/* alias ISOAMSN nltri : mmlalias*/
{ "NotLeftTriangleBar", 	0x029CF, 	0x00338 }, 	/* not left triangle, vertical bar : mmlextra*/
{ "NotLeftTriangleEqual", 	0x022EC, 	0x0 }, 	/* alias ISOAMSN nltrie : mmlalias*/
{ "NotLess", 	0x0226E, 	0x0 }, 	/* alias ISOAMSN nlt : mmlalias*/
{ "NotLessEqual", 	0x02270, 	0x0 }, 	/* alias ISOAMSN nle : mmlalias*/
{ "NotLessGreater", 	0x02278, 	0x0 }, 	/* alias ISOAMSN ntvlg : mmlalias*/
{ "NotLessLess", 	0x0226A, 	0x00338 }, 	/* alias ISOAMSN nLtv : mmlalias*/
{ "NotLessSlantEqual", 	0x02A7D, 	0x00338 }, 	/* alias ISOAMSN nles : mmlalias*/
{ "NotLessTilde", 	0x02274, 	0x0 }, 	/* alias ISOAMSN nlsim : mmlalias*/
{ "NotNestedGreaterGreater", 	0x02AA2, 	0x00338 }, 	/* not double greater-than sign : mmlextra*/
{ "NotNestedLessLess", 	0x02AA1, 	0x00338 }, 	/* not double less-than sign : mmlextra*/
{ "NotPrecedes", 	0x02280, 	0x0 }, 	/* alias ISOAMSN npr : mmlalias*/
{ "NotPrecedesEqual", 	0x02AAF, 	0x00338 }, 	/* alias ISOAMSN npre : mmlalias*/
{ "NotPrecedesSlantEqual", 	0x022E0, 	0x0 }, 	/* alias ISOAMSN nprcue : mmlalias*/
{ "NotReverseElement", 	0x0220C, 	0x0 }, 	/* alias ISOTECH notniva : mmlalias*/
{ "NotRightTriangle", 	0x022EB, 	0x0 }, 	/* alias ISOAMSN nrtri : mmlalias*/
{ "NotRightTriangleBar", 	0x029D0, 	0x00338 }, 	/* not vertical bar, right triangle : mmlextra*/
{ "NotRightTriangleEqual", 	0x022ED, 	0x0 }, 	/* alias ISOAMSN nrtrie : mmlalias*/
{ "NotSquareSubset", 	0x0228F, 	0x00338 }, 	/* square not subset : mmlextra*/
{ "NotSquareSubsetEqual", 	0x022E2, 	0x0 }, 	/* alias ISOAMSN nsqsube : mmlalias*/
{ "NotSquareSuperset", 	0x02290, 	0x00338 }, 	/* negated set-like partial order operator : mmlextra*/
{ "NotSquareSupersetEqual", 	0x022E3, 	0x0 }, 	/* alias ISOAMSN nsqsupe : mmlalias*/
{ "NotSubset", 	0x02282, 	0x020D2 }, 	/* alias ISOAMSN vnsub : mmlalias*/
{ "NotSubsetEqual", 	0x02288, 	0x0 }, 	/* alias ISOAMSN nsube : mmlalias*/
{ "NotSucceeds", 	0x02281, 	0x0 }, 	/* alias ISOAMSN nsc : mmlalias*/
{ "NotSucceedsEqual", 	0x02AB0, 	0x00338 }, 	/* alias ISOAMSN nsce : mmlalias*/
{ "NotSucceedsSlantEqual", 	0x022E1, 	0x0 }, 	/* alias ISOAMSN nsccue : mmlalias*/
{ "NotSucceedsTilde", 	0x0227F, 	0x00338 }, 	/* not succeeds or similar : mmlextra*/
{ "NotSuperset", 	0x02283, 	0x020D2 }, 	/* alias ISOAMSN vnsup : mmlalias*/
{ "NotSupersetEqual", 	0x02289, 	0x0 }, 	/* alias ISOAMSN nsupe : mmlalias*/
{ "NotTilde", 	0x02241, 	0x0 }, 	/* alias ISOAMSN nsim : mmlalias*/
{ "NotTildeEqual", 	0x02244, 	0x0 }, 	/* alias ISOAMSN nsime : mmlalias*/
{ "NotTildeFullEqual", 	0x02247, 	0x0 }, 	/* alias ISOAMSN ncong : mmlalias*/
{ "NotTildeTilde", 	0x02249, 	0x0 }, 	/* alias ISOAMSN nap : mmlalias*/
{ "NotVerticalBar", 	0x02224, 	0x0 }, 	/* alias ISOAMSN nmid : mmlalias*/
{ "Nscr", 	0x1D4A9, 	0x0 }, 	/* /scr N, script letter N : 9573-2003-isomscr*/
{ "Ntilde", 	0x000D1, 	0x0 }, 	/* =capital N, tilde : 9573-2003-isolat1*/
{ "Nu", 	0x0039D, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "OElig", 	0x00152, 	0x0 }, 	/* =capital OE ligature : 9573-2003-isolat2*/
{ "OHacgr", 	0x0038F, 	0x0 }, 	/* =capital Omega, accent, Greek : 9573-2003-isogrk2*/
{ "OHgr", 	0x003A9, 	0x0 }, 	/* =capital Omega, Greek : 9573-2003-isogrk1*/
{ "Oacgr", 	0x0038C, 	0x0 }, 	/* =capital Omicron, accent, Greek : 9573-2003-isogrk2*/
{ "Oacute", 	0x000D3, 	0x0 }, 	/* =capital O, acute accent : 9573-2003-isolat1*/
{ "Ocirc", 	0x000D4, 	0x0 }, 	/* =capital O, circumflex accent : 9573-2003-isolat1*/
{ "Ocy", 	0x0041E, 	0x0 }, 	/* =capital O, Cyrillic : 9573-2003-isocyr1*/
{ "Odblac", 	0x00150, 	0x0 }, 	/* =capital O, double acute accent : 9573-2003-isolat2*/
{ "Ofr", 	0x1D512, 	0x0 }, 	/* /frak O, upper case o : 9573-2003-isomfrk*/
{ "Ogr", 	0x0039F, 	0x0 }, 	/* =capital Omicron, Greek : 9573-2003-isogrk1*/
{ "Ograve", 	0x000D2, 	0x0 }, 	/* =capital O, grave accent : 9573-2003-isolat1*/
{ "Omacr", 	0x0014C, 	0x0 }, 	/* =capital O, macron : 9573-2003-isolat2*/
{ "Omega", 	0x003A9, 	0x0 }, 	/* /Omega capital Omega, Greek : 9573-2003-isogrk3*/
{ "Omicron", 	0x0039F, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Oopf", 	0x1D546, 	0x0 }, 	/* /Bbb O, open face O : 9573-2003-isomopf*/
{ "OpenCurlyDoubleQuote", 	0x0201C, 	0x0 }, 	/* alias ISONUM ldquo : mmlalias*/
{ "OpenCurlyQuote", 	0x02018, 	0x0 }, 	/* alias ISONUM lsquo : mmlalias*/
{ "Or", 	0x02A54, 	0x0 }, 	/* dbl logical or : 9573-2003-isotech*/
{ "Oscr", 	0x1D4AA, 	0x0 }, 	/* /scr O, script letter O : 9573-2003-isomscr*/
{ "Oslash", 	0x000D8, 	0x0 }, 	/* =capital O, slash : 9573-2003-isolat1*/
{ "Otilde", 	0x000D5, 	0x0 }, 	/* =capital O, tilde : 9573-2003-isolat1*/
{ "Otimes", 	0x02A37, 	0x0 }, 	/* multiply sign in double circle : 9573-2003-isoamsb*/
{ "Ouml", 	0x000D6, 	0x0 }, 	/* =capital O, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "OverBar", 	0x0203E, 	0x0 }, 	/* over bar : mmlextra*/
{ "OverBrace", 	0x023DE, 	0x0 }, 	/* over brace  : mmlextra*/
{ "OverBracket", 	0x023B4, 	0x0 }, 	/* over bracket : mmlextra*/
{ "OverParenthesis", 	0x023DC, 	0x0 }, 	/* over parenthesis : mmlextra*/
{ "PHgr", 	0x003A6, 	0x0 }, 	/* =capital Phi, Greek : 9573-2003-isogrk1*/
{ "PSgr", 	0x003A8, 	0x0 }, 	/* =capital Psi, Greek : 9573-2003-isogrk1*/
{ "PartialD", 	0x02202, 	0x0 }, 	/* alias ISOTECH part : mmlalias*/
{ "Pcy", 	0x0041F, 	0x0 }, 	/* =capital PE, Cyrillic : 9573-2003-isocyr1*/
{ "Pfr", 	0x1D513, 	0x0 }, 	/* /frak P, upper case p : 9573-2003-isomfrk*/
{ "Pgr", 	0x003A0, 	0x0 }, 	/* =capital Pi, Greek : 9573-2003-isogrk1*/
{ "Phi", 	0x003A6, 	0x0 }, 	/* /Phi capital Phi, Greek : 9573-2003-isogrk3*/
{ "Pi", 	0x003A0, 	0x0 }, 	/* /Pi capital Pi, Greek : 9573-2003-isogrk3*/
{ "PlusMinus", 	0x000B1, 	0x0 }, 	/* alias ISONUM plusmn : mmlalias*/
{ "Poincareplane", 	0x0210C, 	0x0 }, 	/* the Poincare upper half-plane : mmlalias*/
{ "Popf", 	0x02119, 	0x0 }, 	/* /Bbb P, open face P : 9573-2003-isomopf*/
{ "Pr", 	0x02ABB, 	0x0 }, 	/* dbl precedes : 9573-2003-isoamsr*/
{ "Precedes", 	0x0227A, 	0x0 }, 	/* alias ISOAMSR pr : mmlalias*/
{ "PrecedesEqual", 	0x02AAF, 	0x0 }, 	/* alias ISOAMSR pre : mmlalias*/
{ "PrecedesSlantEqual", 	0x0227C, 	0x0 }, 	/* alias ISOAMSR prcue : mmlalias*/
{ "PrecedesTilde", 	0x0227E, 	0x0 }, 	/* alias ISOAMSR prsim : mmlalias*/
{ "Prime", 	0x02033, 	0x0 }, 	/* double prime or second : 9573-2003-isotech*/
{ "Product", 	0x0220F, 	0x0 }, 	/* alias for &prod; : mmlextra*/
{ "Proportion", 	0x02237, 	0x0 }, 	/* alias ISOAMSR Colon : mmlalias*/
{ "Proportional", 	0x0221D, 	0x0 }, 	/* alias ISOTECH prop : mmlalias*/
{ "Pscr", 	0x1D4AB, 	0x0 }, 	/* /scr P, script letter P : 9573-2003-isomscr*/
{ "Psi", 	0x003A8, 	0x0 }, 	/* /Psi capital Psi, Greek : 9573-2003-isogrk3*/
{ "QUOT", 	0x00022, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "Qfr", 	0x1D514, 	0x0 }, 	/* /frak Q, upper case q : 9573-2003-isomfrk*/
{ "Qopf", 	0x0211A, 	0x0 }, 	/* /Bbb Q, open face Q : 9573-2003-isomopf*/
{ "Qscr", 	0x1D4AC, 	0x0 }, 	/* /scr Q, script letter Q : 9573-2003-isomscr*/
{ "RBarr", 	0x02910, 	0x0 }, 	/* /drbkarow A: twoheaded right broken arrow : 9573-2003-isoamsa*/
{ "REG", 	0x000AE, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "Racute", 	0x00154, 	0x0 }, 	/* =capital R, acute accent : 9573-2003-isolat2*/
{ "Rang", 	0x027EB, 	0x0 }, 	/* right angle bracket, double : 9573-2003-isotech*/
{ "Rarr", 	0x021A0, 	0x0 }, 	/* /twoheadrightarrow A: : 9573-2003-isoamsa*/
{ "Rarrtl", 	0x02916, 	0x0 }, 	/* right two-headed arrow with tail : 9573-2003-isoamsa*/
{ "Rcaron", 	0x00158, 	0x0 }, 	/* =capital R, caron : 9573-2003-isolat2*/
{ "Rcedil", 	0x00156, 	0x0 }, 	/* =capital R, cedilla : 9573-2003-isolat2*/
{ "Rcy", 	0x00420, 	0x0 }, 	/* =capital ER, Cyrillic : 9573-2003-isocyr1*/
{ "Re", 	0x0211C, 	0x0 }, 	/* alias ISOAMSO real : mmlalias*/
{ "ReverseElement", 	0x0220B, 	0x0 }, 	/* alias ISOTECH niv : mmlalias*/
{ "ReverseEquilibrium", 	0x021CB, 	0x0 }, 	/* alias ISOAMSA lrhar : mmlalias*/
{ "ReverseUpEquilibrium", 	0x0296F, 	0x0 }, 	/* alias ISOAMSA duhar : mmlalias*/
{ "Rfr", 	0x0211C, 	0x0 }, 	/* /frak R, upper case r : 9573-2003-isomfrk*/
{ "Rgr", 	0x003A1, 	0x0 }, 	/* =capital Rho, Greek : 9573-2003-isogrk1*/
{ "Rho", 	0x003A1, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "RightAngleBracket", 	0x027E9, 	0x0 }, 	/* alias ISOTECH rang : mmlalias*/
{ "RightArrow", 	0x02192, 	0x0 }, 	/* alias ISONUM rarr : mmlalias*/
{ "RightArrowBar", 	0x021E5, 	0x0 }, 	/* alias for rarrb : mmlalias*/
{ "RightArrowLeftArrow", 	0x021C4, 	0x0 }, 	/* alias ISOAMSA rlarr : mmlalias*/
{ "RightCeiling", 	0x02309, 	0x0 }, 	/* alias ISOAMSC rceil : mmlalias*/
{ "RightDoubleBracket", 	0x027E7, 	0x0 }, 	/* right double bracket delimiter : mmlalias*/
{ "RightDownTeeVector", 	0x0295D, 	0x0 }, 	/* down-right harpoon from bar : mmlextra*/
{ "RightDownVector", 	0x021C2, 	0x0 }, 	/* alias ISOAMSA dharr : mmlalias*/
{ "RightDownVectorBar", 	0x02955, 	0x0 }, 	/* down-right harpoon to bar : mmlextra*/
{ "RightFloor", 	0x0230B, 	0x0 }, 	/* alias ISOAMSC rfloor : mmlalias*/
{ "RightTee", 	0x022A2, 	0x0 }, 	/* alias ISOAMSR vdash : mmlalias*/
{ "RightTeeArrow", 	0x021A6, 	0x0 }, 	/* alias ISOAMSA map : mmlalias*/
{ "RightTeeVector", 	0x0295B, 	0x0 }, 	/* right-up harpoon from bar : mmlextra*/
{ "RightTriangle", 	0x022B3, 	0x0 }, 	/* alias ISOAMSR vrtri : mmlalias*/
{ "RightTriangleBar", 	0x029D0, 	0x0 }, 	/* vertical bar, right triangle : mmlextra*/
{ "RightTriangleEqual", 	0x022B5, 	0x0 }, 	/* alias ISOAMSR rtrie : mmlalias*/
{ "RightUpDownVector", 	0x0294F, 	0x0 }, 	/* up-right-down-right harpoon : mmlextra*/
{ "RightUpTeeVector", 	0x0295C, 	0x0 }, 	/* up-right harpoon from bar : mmlextra*/
{ "RightUpVector", 	0x021BE, 	0x0 }, 	/* alias ISOAMSA uharr : mmlalias*/
{ "RightUpVectorBar", 	0x02954, 	0x0 }, 	/* up-right harpoon to bar : mmlextra*/
{ "RightVector", 	0x021C0, 	0x0 }, 	/* alias ISOAMSA rharu : mmlalias*/
{ "RightVectorBar", 	0x02953, 	0x0 }, 	/* up-right harpoon to bar : mmlextra*/
{ "Rightarrow", 	0x021D2, 	0x0 }, 	/* alias ISOTECH rArr : mmlalias*/
{ "Ropf", 	0x0211D, 	0x0 }, 	/* /Bbb R, open face R : 9573-2003-isomopf*/
{ "RoundImplies", 	0x02970, 	0x0 }, 	/* round implies : mmlextra*/
{ "Rrightarrow", 	0x021DB, 	0x0 }, 	/* alias ISOAMSA rAarr : mmlalias*/
{ "Rscr", 	0x0211B, 	0x0 }, 	/* /scr R, script letter R : 9573-2003-isomscr*/
{ "Rsh", 	0x021B1, 	0x0 }, 	/* alias ISOAMSA rsh : mmlalias*/
{ "RuleDelayed", 	0x029F4, 	0x0 }, 	/* rule-delayed (colon right arrow) : mmlextra*/
{ "SHCHcy", 	0x00429, 	0x0 }, 	/* =capital SHCHA, Cyrillic : 9573-2003-isocyr1*/
{ "SHcy", 	0x00428, 	0x0 }, 	/* =capital SHA, Cyrillic : 9573-2003-isocyr1*/
{ "SOFTcy", 	0x0042C, 	0x0 }, 	/* =capital SOFT sign, Cyrillic : 9573-2003-isocyr1*/
{ "Sacute", 	0x0015A, 	0x0 }, 	/* =capital S, acute accent : 9573-2003-isolat2*/
{ "Sc", 	0x02ABC, 	0x0 }, 	/* dbl succeeds : 9573-2003-isoamsr*/
{ "Scaron", 	0x00160, 	0x0 }, 	/* =capital S, caron : 9573-2003-isolat2*/
{ "Scedil", 	0x0015E, 	0x0 }, 	/* =capital S, cedilla : 9573-2003-isolat2*/
{ "Scirc", 	0x0015C, 	0x0 }, 	/* =capital S, circumflex accent : 9573-2003-isolat2*/
{ "Scy", 	0x00421, 	0x0 }, 	/* =capital ES, Cyrillic : 9573-2003-isocyr1*/
{ "Sfr", 	0x1D516, 	0x0 }, 	/* /frak S, upper case s : 9573-2003-isomfrk*/
{ "Sgr", 	0x003A3, 	0x0 }, 	/* =capital Sigma, Greek : 9573-2003-isogrk1*/
{ "ShortDownArrow", 	0x02193, 	0x0 }, 	/* short down arrow : mmlalias*/
{ "ShortLeftArrow", 	0x02190, 	0x0 }, 	/* alias ISOAMSA slarr : mmlalias*/
{ "ShortRightArrow", 	0x02192, 	0x0 }, 	/* alias ISOAMSA srarr : mmlalias*/
{ "ShortUpArrow", 	0x02191, 	0x0 }, 	/* short up arrow  : mmlalias*/
{ "Sigma", 	0x003A3, 	0x0 }, 	/* /Sigma capital Sigma, Greek : 9573-2003-isogrk3*/
{ "SmallCircle", 	0x02218, 	0x0 }, 	/* alias ISOTECH compfn : mmlalias*/
{ "Sopf", 	0x1D54A, 	0x0 }, 	/* /Bbb S, open face S : 9573-2003-isomopf*/
{ "Sqrt", 	0x0221A, 	0x0 }, 	/* alias ISOTECH radic : mmlalias*/
{ "Square", 	0x025A1, 	0x0 }, 	/* alias for square : mmlalias*/
{ "SquareIntersection", 	0x02293, 	0x0 }, 	/* alias ISOAMSB sqcap : mmlalias*/
{ "SquareSubset", 	0x0228F, 	0x0 }, 	/* alias ISOAMSR sqsub : mmlalias*/
{ "SquareSubsetEqual", 	0x02291, 	0x0 }, 	/* alias ISOAMSR sqsube : mmlalias*/
{ "SquareSuperset", 	0x02290, 	0x0 }, 	/* alias ISOAMSR sqsup : mmlalias*/
{ "SquareSupersetEqual", 	0x02292, 	0x0 }, 	/* alias ISOAMSR sqsupe : mmlalias*/
{ "SquareUnion", 	0x02294, 	0x0 }, 	/* alias ISOAMSB sqcup : mmlalias*/
{ "Sscr", 	0x1D4AE, 	0x0 }, 	/* /scr S, script letter S : 9573-2003-isomscr*/
{ "Star", 	0x022C6, 	0x0 }, 	/* alias ISOAMSB sstarf : mmlalias*/
{ "Sub", 	0x022D0, 	0x0 }, 	/* /Subset R: double subset : 9573-2003-isoamsr*/
{ "Subset", 	0x022D0, 	0x0 }, 	/* alias ISOAMSR Sub : mmlalias*/
{ "SubsetEqual", 	0x02286, 	0x0 }, 	/* alias ISOTECH sube : mmlalias*/
{ "Succeeds", 	0x0227B, 	0x0 }, 	/* alias ISOAMSR sc : mmlalias*/
{ "SucceedsEqual", 	0x02AB0, 	0x0 }, 	/* alias ISOAMSR sce : mmlalias*/
{ "SucceedsSlantEqual", 	0x0227D, 	0x0 }, 	/* alias ISOAMSR sccue : mmlalias*/
{ "SucceedsTilde", 	0x0227F, 	0x0 }, 	/* alias ISOAMSR scsim : mmlalias*/
{ "SuchThat", 	0x0220B, 	0x0 }, 	/* ISOTECH  ni : mmlalias*/
{ "Sum", 	0x02211, 	0x0 }, 	/* alias ISOAMSB sum : mmlalias*/
{ "Sup", 	0x022D1, 	0x0 }, 	/* /Supset R: dbl superset : 9573-2003-isoamsr*/
{ "Superset", 	0x02283, 	0x0 }, 	/* alias ISOTECH sup : mmlalias*/
{ "SupersetEqual", 	0x02287, 	0x0 }, 	/* alias ISOTECH supe : mmlalias*/
{ "Supset", 	0x022D1, 	0x0 }, 	/* alias ISOAMSR Sup : mmlalias*/
{ "THORN", 	0x000DE, 	0x0 }, 	/* =capital THORN, Icelandic : 9573-2003-isolat1*/
{ "THgr", 	0x00398, 	0x0 }, 	/* =capital Theta, Greek : 9573-2003-isogrk1*/
{ "TRADE", 	0x02122, 	0x0 }, 	/* legacy uppercase name : html5-uppercase*/
{ "TSHcy", 	0x0040B, 	0x0 }, 	/* =capital TSHE, Serbian : 9573-2003-isocyr2*/
{ "TScy", 	0x00426, 	0x0 }, 	/* =capital TSE, Cyrillic : 9573-2003-isocyr1*/
{ "Tab", 	0x00009, 	0x0 }, 	/*  : mmlextra*/
{ "Tau", 	0x003A4, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Tcaron", 	0x00164, 	0x0 }, 	/* =capital T, caron : 9573-2003-isolat2*/
{ "Tcedil", 	0x00162, 	0x0 }, 	/* =capital T, cedilla : 9573-2003-isolat2*/
{ "Tcy", 	0x00422, 	0x0 }, 	/* =capital TE, Cyrillic : 9573-2003-isocyr1*/
{ "Tfr", 	0x1D517, 	0x0 }, 	/* /frak T, upper case t : 9573-2003-isomfrk*/
{ "Tgr", 	0x003A4, 	0x0 }, 	/* =capital Tau, Greek : 9573-2003-isogrk1*/
{ "Therefore", 	0x02234, 	0x0 }, 	/* alias ISOTECH there4 : mmlalias*/
{ "Theta", 	0x00398, 	0x0 }, 	/* /Theta capital Theta, Greek : 9573-2003-isogrk3*/
{ "Thetav", 	0x003F4, 	0x0 }, 	/* 04E8 : STIX*/
{ "ThickSpace", 	0x0205F, 	0x0200A }, 	/*  : mmlextra*/
{ "ThinSpace", 	0x02009, 	0x0 }, 	/* space of width 3/18 em alias ISOPUB thinsp : mmlalias*/
{ "Tilde", 	0x0223C, 	0x0 }, 	/* alias ISOTECH sim : mmlalias*/
{ "TildeEqual", 	0x02243, 	0x0 }, 	/* alias ISOTECH sime : mmlalias*/
{ "TildeFullEqual", 	0x02245, 	0x0 }, 	/* alias ISOTECH cong : mmlalias*/
{ "TildeTilde", 	0x02248, 	0x0 }, 	/* alias ISOTECH ap : mmlalias*/
{ "Topf", 	0x1D54B, 	0x0 }, 	/* /Bbb T, open face T : 9573-2003-isomopf*/
{ "TripleDot", 	0x020DB, 	0x0 }, 	/* alias ISOTECH tdot : mmlalias*/
{ "Tscr", 	0x1D4AF, 	0x0 }, 	/* /scr T, script letter T : 9573-2003-isomscr*/
{ "Tstrok", 	0x00166, 	0x0 }, 	/* =capital T, stroke : 9573-2003-isolat2*/
{ "Uacgr", 	0x0038E, 	0x0 }, 	/* =capital Upsilon, accent, Greek : 9573-2003-isogrk2*/
{ "Uacute", 	0x000DA, 	0x0 }, 	/* =capital U, acute accent : 9573-2003-isolat1*/
{ "Uarr", 	0x0219F, 	0x0 }, 	/* up two-headed arrow : 9573-2003-isoamsa*/
{ "Uarrocir", 	0x02949, 	0x0 }, 	/* up two-headed arrow above circle : 9573-2003-isoamsa*/
{ "Ubrcy", 	0x0040E, 	0x0 }, 	/* =capital U, Byelorussian : 9573-2003-isocyr2*/
{ "Ubreve", 	0x0016C, 	0x0 }, 	/* =capital U, breve : 9573-2003-isolat2*/
{ "Ucirc", 	0x000DB, 	0x0 }, 	/* =capital U, circumflex accent : 9573-2003-isolat1*/
{ "Ucy", 	0x00423, 	0x0 }, 	/* =capital U, Cyrillic : 9573-2003-isocyr1*/
{ "Udblac", 	0x00170, 	0x0 }, 	/* =capital U, double acute accent : 9573-2003-isolat2*/
{ "Udigr", 	0x003AB, 	0x0 }, 	/* =capital Upsilon, dieresis, Greek : 9573-2003-isogrk2*/
{ "Ufr", 	0x1D518, 	0x0 }, 	/* /frak U, upper case u : 9573-2003-isomfrk*/
{ "Ugr", 	0x003A5, 	0x0 }, 	/* =capital Upsilon, Greek : 9573-2003-isogrk1*/
{ "Ugrave", 	0x000D9, 	0x0 }, 	/* =capital U, grave accent : 9573-2003-isolat1*/
{ "Umacr", 	0x0016A, 	0x0 }, 	/* =capital U, macron : 9573-2003-isolat2*/
{ "UnderBar", 	0x0005F, 	0x0 }, 	/* combining low line : mmlextra*/
{ "UnderBrace", 	0x023DF, 	0x0 }, 	/* under brace  : mmlextra*/
{ "UnderBracket", 	0x023B5, 	0x0 }, 	/* under bracket : mmlextra*/
{ "UnderParenthesis", 	0x023DD, 	0x0 }, 	/* under parenthesis : mmlextra*/
{ "Union", 	0x022C3, 	0x0 }, 	/* alias ISOAMSB xcup : mmlalias*/
{ "UnionPlus", 	0x0228E, 	0x0 }, 	/* alias ISOAMSB uplus : mmlalias*/
{ "Uogon", 	0x00172, 	0x0 }, 	/* =capital U, ogonek : 9573-2003-isolat2*/
{ "Uopf", 	0x1D54C, 	0x0 }, 	/* /Bbb U, open face U : 9573-2003-isomopf*/
{ "UpArrow", 	0x02191, 	0x0 }, 	/* alias ISONUM uarr : mmlalias*/
{ "UpArrowBar", 	0x02912, 	0x0 }, 	/* up arrow to bar : mmlextra*/
{ "UpArrowDownArrow", 	0x021C5, 	0x0 }, 	/* alias ISOAMSA udarr : mmlalias*/
{ "UpDownArrow", 	0x02195, 	0x0 }, 	/* alias ISOAMSA varr : mmlalias*/
{ "UpEquilibrium", 	0x0296E, 	0x0 }, 	/* alias ISOAMSA udhar : mmlalias*/
{ "UpTee", 	0x022A5, 	0x0 }, 	/* alias ISOTECH perp : mmlalias*/
{ "UpTeeArrow", 	0x021A5, 	0x0 }, 	/* Alias mapstoup : mmlalias*/
{ "Uparrow", 	0x021D1, 	0x0 }, 	/* alias ISOAMSA uArr : mmlalias*/
{ "Updownarrow", 	0x021D5, 	0x0 }, 	/* alias ISOAMSA vArr : mmlalias*/
{ "UpperLeftArrow", 	0x02196, 	0x0 }, 	/* alias ISOAMSA nwarr : mmlalias*/
{ "UpperRightArrow", 	0x02197, 	0x0 }, 	/* alias ISOAMSA nearr : mmlalias*/
{ "Upsi", 	0x003D2, 	0x0 }, 	/* /Upsilon capital Upsilon, Greek : 9573-2003-isogrk3*/
{ "Upsilon", 	0x003A5, 	0x0 }, 	/* greek capital letter upsilon : xhtml1-symbol*/
{ "Uring", 	0x0016E, 	0x0 }, 	/* =capital U, ring : 9573-2003-isolat2*/
{ "Uscr", 	0x1D4B0, 	0x0 }, 	/* /scr U, script letter U : 9573-2003-isomscr*/
{ "Utilde", 	0x00168, 	0x0 }, 	/* =capital U, tilde : 9573-2003-isolat2*/
{ "Uuml", 	0x000DC, 	0x0 }, 	/* =capital U, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "VDash", 	0x022AB, 	0x0 }, 	/* dbl vert, dbl dash : 9573-2003-isoamsr*/
{ "Vbar", 	0x02AEB, 	0x0 }, 	/* dbl vert, bar (under) : 9573-2003-isoamsr*/
{ "Vcy", 	0x00412, 	0x0 }, 	/* =capital VE, Cyrillic : 9573-2003-isocyr1*/
{ "Vdash", 	0x022A9, 	0x0 }, 	/* /Vdash R: dbl vertical, dash : 9573-2003-isoamsr*/
{ "Vdashl", 	0x02AE6, 	0x0 }, 	/* vertical, dash (long) : 9573-2003-isoamsr*/
{ "Vee", 	0x022C1, 	0x0 }, 	/* alias ISOAMSB xvee : mmlalias*/
{ "Verbar", 	0x02016, 	0x0 }, 	/* /Vert dbl vertical bar : 9573-2003-isotech*/
{ "Vert", 	0x02016, 	0x0 }, 	/* alias ISOTECH Verbar : mmlalias*/
{ "VerticalBar", 	0x02223, 	0x0 }, 	/* alias ISOAMSR mid : mmlalias*/
{ "VerticalLine", 	0x0007C, 	0x0 }, 	/* alias ISONUM verbar : mmlextra*/
{ "VerticalSeparator", 	0x02758, 	0x0 }, 	/*  : mmlextra*/
{ "VerticalTilde", 	0x02240, 	0x0 }, 	/* alias ISOAMSB wreath : mmlalias*/
{ "VeryThinSpace", 	0x0200A, 	0x0 }, 	/* space of width 1/18 em alias ISOPUB hairsp : mmlalias*/
{ "Vfr", 	0x1D519, 	0x0 }, 	/* /frak V, upper case v : 9573-2003-isomfrk*/
{ "Vopf", 	0x1D54D, 	0x0 }, 	/* /Bbb V, open face V : 9573-2003-isomopf*/
{ "Vscr", 	0x1D4B1, 	0x0 }, 	/* /scr V, script letter V : 9573-2003-isomscr*/
{ "Vvdash", 	0x022AA, 	0x0 }, 	/* /Vvdash R: triple vertical, dash : 9573-2003-isoamsr*/
{ "Wcirc", 	0x00174, 	0x0 }, 	/* =capital W, circumflex accent : 9573-2003-isolat2*/
{ "Wedge", 	0x022C0, 	0x0 }, 	/* alias ISOAMSB xwedge : mmlalias*/
{ "Wfr", 	0x1D51A, 	0x0 }, 	/* /frak W, upper case w : 9573-2003-isomfrk*/
{ "Wopf", 	0x1D54E, 	0x0 }, 	/* /Bbb W, open face W : 9573-2003-isomopf*/
{ "Wscr", 	0x1D4B2, 	0x0 }, 	/* /scr W, script letter W : 9573-2003-isomscr*/
{ "Xfr", 	0x1D51B, 	0x0 }, 	/* /frak X, upper case x : 9573-2003-isomfrk*/
{ "Xgr", 	0x0039E, 	0x0 }, 	/* =capital Xi, Greek : 9573-2003-isogrk1*/
{ "Xi", 	0x0039E, 	0x0 }, 	/* /Xi capital Xi, Greek : 9573-2003-isogrk3*/
{ "Xopf", 	0x1D54F, 	0x0 }, 	/* /Bbb X, open face X : 9573-2003-isomopf*/
{ "Xscr", 	0x1D4B3, 	0x0 }, 	/* /scr X, script letter X : 9573-2003-isomscr*/
{ "YAcy", 	0x0042F, 	0x0 }, 	/* =capital YA, Cyrillic : 9573-2003-isocyr1*/
{ "YIcy", 	0x00407, 	0x0 }, 	/* =capital YI, Ukrainian : 9573-2003-isocyr2*/
{ "YUcy", 	0x0042E, 	0x0 }, 	/* =capital YU, Cyrillic : 9573-2003-isocyr1*/
{ "Yacute", 	0x000DD, 	0x0 }, 	/* =capital Y, acute accent : 9573-2003-isolat1*/
{ "Ycirc", 	0x00176, 	0x0 }, 	/* =capital Y, circumflex accent : 9573-2003-isolat2*/
{ "Ycy", 	0x0042B, 	0x0 }, 	/* =capital YERU, Cyrillic : 9573-2003-isocyr1*/
{ "Yfr", 	0x1D51C, 	0x0 }, 	/* /frak Y, upper case y : 9573-2003-isomfrk*/
{ "Yopf", 	0x1D550, 	0x0 }, 	/* /Bbb Y, open face Y : 9573-2003-isomopf*/
{ "Yscr", 	0x1D4B4, 	0x0 }, 	/* /scr Y, script letter Y : 9573-2003-isomscr*/
{ "Yuml", 	0x00178, 	0x0 }, 	/* =capital Y, dieresis or umlaut mark : 9573-2003-isolat2*/
{ "ZHcy", 	0x00416, 	0x0 }, 	/* =capital ZHE, Cyrillic : 9573-2003-isocyr1*/
{ "Zacute", 	0x00179, 	0x0 }, 	/* =capital Z, acute accent : 9573-2003-isolat2*/
{ "Zcaron", 	0x0017D, 	0x0 }, 	/* =capital Z, caron : 9573-2003-isolat2*/
{ "Zcy", 	0x00417, 	0x0 }, 	/* =capital ZE, Cyrillic : 9573-2003-isocyr1*/
{ "Zdot", 	0x0017B, 	0x0 }, 	/* =capital Z, dot above : 9573-2003-isolat2*/
{ "ZeroWidthSpace", 	0x0200B, 	0x0 }, 	/* zero width space : mmlextra*/
{ "Zeta", 	0x00396, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "Zfr", 	0x02128, 	0x0 }, 	/* /frak Z, upper case z  : 9573-2003-isomfrk*/
{ "Zgr", 	0x00396, 	0x0 }, 	/* =capital Zeta, Greek : 9573-2003-isogrk1*/
{ "Zopf", 	0x02124, 	0x0 }, 	/* /Bbb Z, open face Z : 9573-2003-isomopf*/
{ "Zscr", 	0x1D4B5, 	0x0 }, 	/* /scr Z, script letter Z : 9573-2003-isomscr*/
{ "aacgr", 	0x003AC, 	0x0 }, 	/* =small alpha, accent, Greek : 9573-2003-isogrk2*/
{ "aacute", 	0x000E1, 	0x0 }, 	/* =small a, acute accent : 9573-2003-isolat1*/
{ "abreve", 	0x00103, 	0x0 }, 	/* =small a, breve : 9573-2003-isolat2*/
{ "ac", 	0x0223E, 	0x0 }, 	/* most positive : 9573-2003-isoamsb*/
{ "acE", 	0x0223E, 	0x00333 }, 	/* most positive, two lines below : 9573-2003-isoamsb*/
{ "acd", 	0x0223F, 	0x0 }, 	/* ac current : 9573-2003-isotech*/
{ "acirc", 	0x000E2, 	0x0 }, 	/* =small a, circumflex accent : 9573-2003-isolat1*/
{ "actuary", 	0x020E7, 	0x0 }, 	/*  : STIX*/
{ "acute", 	0x000B4, 	0x0 }, 	/* =acute accent : 9573-2003-isodia*/
{ "acy", 	0x00430, 	0x0 }, 	/* =small a, Cyrillic : 9573-2003-isocyr1*/
{ "aelig", 	0x000E6, 	0x0 }, 	/* =small ae diphthong (ligature) : 9573-2003-isolat1*/
{ "af", 	0x02061, 	0x0 }, 	/* character showing function application in presentation tagging : mmlextra*/
{ "afr", 	0x1D51E, 	0x0 }, 	/* /frak a, lower case a : 9573-2003-isomfrk*/
{ "agr", 	0x003B1, 	0x0 }, 	/* =small alpha, Greek : 9573-2003-isogrk1*/
{ "agrave", 	0x000E0, 	0x0 }, 	/* =small a, grave accent : 9573-2003-isolat1*/
{ "alefsym", 	0x02135, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "aleph", 	0x02135, 	0x0 }, 	/* /aleph aleph, Hebrew : 9573-2003-isotech*/
{ "alpha", 	0x003B1, 	0x0 }, 	/* /alpha small alpha, Greek : 9573-2003-isogrk3*/
{ "amacr", 	0x00101, 	0x0 }, 	/* =small a, macron : 9573-2003-isolat2*/
{ "amalg", 	0x02A3F, 	0x0 }, 	/* /amalg B: amalgamation or coproduct : 9573-2003-isoamsb*/
{ "amp", 	0x00026, 	0x0 }, 	/* =ampersand : 9573-2003-isonum*/
{ "and", 	0x02227, 	0x0 }, 	/* /wedge /land B: logical and : 9573-2003-isotech*/
{ "andand", 	0x02A55, 	0x0 }, 	/* two logical and : 9573-2003-isotech*/
{ "andd", 	0x02A5C, 	0x0 }, 	/* and, horizontal dash : 9573-2003-isotech*/
{ "andslope", 	0x02A58, 	0x0 }, 	/* sloping large and : 9573-2003-isotech*/
{ "andv", 	0x02A5A, 	0x0 }, 	/* and with middle stem : 9573-2003-isotech*/
{ "ang", 	0x02220, 	0x0 }, 	/* /angle - angle : 9573-2003-isoamso*/
{ "ang90", 	0x0221F, 	0x0 }, 	/* =right (90 degree) angle : 8879-isotech*/
{ "angdnl", 	0x029A2, 	0x0 }, 	/*  : STIX*/
{ "angdnr", 	0x0299F, 	0x0 }, 	/*  : STIX*/
{ "ange", 	0x029A4, 	0x0 }, 	/* angle, equal : 9573-2003-isoamso*/
{ "angle", 	0x02220, 	0x0 }, 	/* alias ISOAMSO ang : mmlalias*/
{ "angles", 	0x0299E, 	0x0 }, 	/*  : STIX*/
{ "angmsd", 	0x02221, 	0x0 }, 	/* /measuredangle - angle-measured : 9573-2003-isoamso*/
{ "angmsdaa", 	0x029A8, 	0x0 }, 	/* angle-measured, arrow, up, right : 9573-2003-isoamso*/
{ "angmsdab", 	0x029A9, 	0x0 }, 	/* angle-measured, arrow, up, left : 9573-2003-isoamso*/
{ "angmsdac", 	0x029AA, 	0x0 }, 	/* angle-measured, arrow, down, right : 9573-2003-isoamso*/
{ "angmsdad", 	0x029AB, 	0x0 }, 	/* angle-measured, arrow, down, left : 9573-2003-isoamso*/
{ "angmsdae", 	0x029AC, 	0x0 }, 	/* angle-measured, arrow, right, up : 9573-2003-isoamso*/
{ "angmsdaf", 	0x029AD, 	0x0 }, 	/* angle-measured, arrow, left, up : 9573-2003-isoamso*/
{ "angmsdag", 	0x029AE, 	0x0 }, 	/* angle-measured, arrow, right, down : 9573-2003-isoamso*/
{ "angmsdah", 	0x029AF, 	0x0 }, 	/* angle-measured, arrow, left, down : 9573-2003-isoamso*/
{ "angrt", 	0x0221F, 	0x0 }, 	/* right (90 degree) angle : 9573-2003-isotech*/
{ "angrtvb", 	0x022BE, 	0x0 }, 	/* right angle-measured : 9573-2003-isoamso*/
{ "angrtvbd", 	0x0299D, 	0x0 }, 	/* right angle-measured, dot : 9573-2003-isoamso*/
{ "angsph", 	0x02222, 	0x0 }, 	/* /sphericalangle angle-spherical : 9573-2003-isotech*/
{ "angst", 	0x000C5, 	0x0 }, 	/* Angstrom capital A, ring : 9573-2003-isotech*/
{ "angupl", 	0x029A3, 	0x0 }, 	/*  : STIX*/
{ "angzarr", 	0x0237C, 	0x0 }, 	/* angle with down zig-zag arrow : 9573-2003-isoamsa*/
{ "aogon", 	0x00105, 	0x0 }, 	/* =small a, ogonek : 9573-2003-isolat2*/
{ "aopf", 	0x1D552, 	0x0 }, 	/*  : mmlextra*/
{ "ap", 	0x02248, 	0x0 }, 	/* /approx R: approximate : 9573-2003-isotech*/
{ "apE", 	0x02A70, 	0x0 }, 	/* approximately equal or equal to : 9573-2003-isoamsr*/
{ "apacir", 	0x02A6F, 	0x0 }, 	/* approximate, circumflex accent : 9573-2003-isotech*/
{ "ape", 	0x0224A, 	0x0 }, 	/* /approxeq R: approximate, equals : 9573-2003-isoamsr*/
{ "apid", 	0x0224B, 	0x0 }, 	/* approximately identical to : 9573-2003-isoamsr*/
{ "apos", 	0x00027, 	0x0 }, 	/* =apostrophe : 9573-2003-isonum*/
{ "approx", 	0x02248, 	0x0 }, 	/* alias ISOTECH ap : mmlalias*/
{ "approxeq", 	0x0224A, 	0x0 }, 	/* alias ISOAMSR ape : mmlalias*/
{ "aring", 	0x000E5, 	0x0 }, 	/* =small a, ring : 9573-2003-isolat1*/
{ "arrllsr", 	0x02943, 	0x0 }, 	/*  : STIX*/
{ "arrlrsl", 	0x02942, 	0x0 }, 	/*  : STIX*/
{ "arrsrll", 	0x02944, 	0x0 }, 	/*  : STIX*/
{ "ascr", 	0x1D4B6, 	0x0 }, 	/* /scr a, script letter a : 9573-2003-isomscr*/
{ "ast", 	0x0002A, 	0x0 }, 	/* /ast B: =asterisk : 9573-2003-isonum*/
{ "astb", 	0x029C6, 	0x0 }, 	/*  : STIX*/
{ "asymp", 	0x02248, 	0x0 }, 	/* almost equal to = asymptotic to : xhtml1-symbol*/
{ "asympeq", 	0x0224D, 	0x0 }, 	/* Old ISOAMSR asymp (for HTML compatibility) : mmlextra*/
{ "atilde", 	0x000E3, 	0x0 }, 	/* =small a, tilde : 9573-2003-isolat1*/
{ "auml", 	0x000E4, 	0x0 }, 	/* =small a, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "awconint", 	0x02233, 	0x0 }, 	/* contour integral, anti-clockwise : 9573-2003-isotech*/
{ "awint", 	0x02A11, 	0x0 }, 	/* anti clock-wise integration : 9573-2003-isotech*/
{ "b.Delta", 	0x1D6AB, 	0x0 }, 	/* capital Delta, Greek : 8879-isogrk4*/
{ "b.Gamma", 	0x1D6AA, 	0x0 }, 	/* capital gamma, Greek : 8879-isogrk4*/
{ "b.Gammad", 	0x1D7CA, 	0x0 }, 	/* capital Digamma : 8879-isogrk4*/
{ "b.Lambda", 	0x1D6B2, 	0x0 }, 	/* capital Lambda, Greek : 8879-isogrk4*/
{ "b.Omega", 	0x1D6C0, 	0x0 }, 	/* capital Omega, Greek : 8879-isogrk4*/
{ "b.Phi", 	0x1D6BD, 	0x0 }, 	/* capital Phi, Greek : 8879-isogrk4*/
{ "b.Pi", 	0x1D6B7, 	0x0 }, 	/* capital Pi, Greek : 8879-isogrk4*/
{ "b.Psi", 	0x1D6BF, 	0x0 }, 	/* capital Psi, Greek : 8879-isogrk4*/
{ "b.Sigma", 	0x1D6BA, 	0x0 }, 	/* capital Sigma, Greek : 8879-isogrk4*/
{ "b.Theta", 	0x1D6AF, 	0x0 }, 	/* capital Theta, Greek : 8879-isogrk4*/
{ "b.Upsi", 	0x1D6BC, 	0x0 }, 	/* capital Upsilon, Greek : 8879-isogrk4*/
{ "b.Xi", 	0x1D6B5, 	0x0 }, 	/* capital Xi, Greek : 8879-isogrk4*/
{ "b.alpha", 	0x1D6C2, 	0x0 }, 	/* small alpha, Greek : 8879-isogrk4*/
{ "b.beta", 	0x1D6C3, 	0x0 }, 	/* small beta, Greek : 8879-isogrk4*/
{ "b.chi", 	0x1D6D8, 	0x0 }, 	/* small chi, Greek : 8879-isogrk4*/
{ "b.delta", 	0x1D6C5, 	0x0 }, 	/* small delta, Greek : 8879-isogrk4*/
{ "b.epsi", 	0x1D6C6, 	0x0 }, 	/* small epsilon, Greek : 8879-isogrk4*/
{ "b.epsiv", 	0x1D6DC, 	0x0 }, 	/* variant epsilon : 8879-isogrk4*/
{ "b.eta", 	0x1D6C8, 	0x0 }, 	/* small eta, Greek : 8879-isogrk4*/
{ "b.gamma", 	0x1D6C4, 	0x0 }, 	/* small gamma, Greek : 8879-isogrk4*/
{ "b.gammad", 	0x1D7CB, 	0x0 }, 	/* digamma : 8879-isogrk4*/
{ "b.iota", 	0x1D6CA, 	0x0 }, 	/* small iota, Greek : 8879-isogrk4*/
{ "b.kappa", 	0x1D6CB, 	0x0 }, 	/* small kappa, Greek : 8879-isogrk4*/
{ "b.kappav", 	0x1D6DE, 	0x0 }, 	/* variant kappa : 8879-isogrk4*/
{ "b.lambda", 	0x1D6CC, 	0x0 }, 	/* small lambda, Greek : 8879-isogrk4*/
{ "b.mu", 	0x1D6CD, 	0x0 }, 	/* small mu, Greek : 8879-isogrk4*/
{ "b.nu", 	0x1D6CE, 	0x0 }, 	/* small nu, Greek : 8879-isogrk4*/
{ "b.omega", 	0x1D6DA, 	0x0 }, 	/* small omega, Greek : 8879-isogrk4*/
{ "b.phi", 	0x1D6D7, 	0x0 }, 	/* small phi, Greek : 8879-isogrk4*/
{ "b.phiv", 	0x1D6DF, 	0x0 }, 	/* variant phi : 8879-isogrk4*/
{ "b.pi", 	0x1D6D1, 	0x0 }, 	/* small pi, Greek : 8879-isogrk4*/
{ "b.piv", 	0x1D6E1, 	0x0 }, 	/* variant pi : 8879-isogrk4*/
{ "b.psi", 	0x1D6D9, 	0x0 }, 	/* small psi, Greek : 8879-isogrk4*/
{ "b.rho", 	0x1D6D2, 	0x0 }, 	/* small rho, Greek : 8879-isogrk4*/
{ "b.rhov", 	0x1D6E0, 	0x0 }, 	/* variant rho : 8879-isogrk4*/
{ "b.sigma", 	0x1D6D4, 	0x0 }, 	/* small sigma, Greek : 8879-isogrk4*/
{ "b.sigmav", 	0x1D6D3, 	0x0 }, 	/* variant sigma : 8879-isogrk4*/
{ "b.tau", 	0x1D6D5, 	0x0 }, 	/* small tau, Greek : 8879-isogrk4*/
{ "b.thetas", 	0x1D6C9, 	0x0 }, 	/* straight theta, Greek : 8879-isogrk4*/
{ "b.thetav", 	0x1D6DD, 	0x0 }, 	/* variant thete : 8879-isogrk4*/
{ "b.upsi", 	0x1D6D6, 	0x0 }, 	/* small upsilon, Greek : 8879-isogrk4*/
{ "b.xi", 	0x1D6CF, 	0x0 }, 	/* small xi, Greek : 8879-isogrk4*/
{ "b.zeta", 	0x1D6C7, 	0x0 }, 	/* small zeta, Greek : 8879-isogrk4*/
{ "bNot", 	0x02AED, 	0x0 }, 	/* reverse not with two horizontal strokes : 9573-2003-isotech*/
{ "backcong", 	0x0224C, 	0x0 }, 	/* alias ISOAMSR bcong : mmlalias*/
{ "backepsilon", 	0x003F6, 	0x0 }, 	/* alias ISOAMSR bepsi : mmlalias*/
{ "backprime", 	0x02035, 	0x0 }, 	/* alias ISOAMSO bprime : mmlalias*/
{ "backsim", 	0x0223D, 	0x0 }, 	/* alias ISOAMSR bsim : mmlalias*/
{ "backsimeq", 	0x022CD, 	0x0 }, 	/* alias ISOAMSR bsime : mmlalias*/
{ "barV", 	0x02AEA, 	0x0 }, 	/*  : STIX*/
{ "barvee", 	0x022BD, 	0x0 }, 	/* bar, vee : 9573-2003-isoamsb*/
{ "barwed", 	0x02305, 	0x0 }, 	/* /barwedge B: logical and, bar above : 9573-2003-isoamsb*/
{ "barwedge", 	0x02305, 	0x0 }, 	/* alias ISOAMSB barwed : mmlalias*/
{ "bbrk", 	0x023B5, 	0x0 }, 	/* bottom square bracket : 9573-2003-isoamso*/
{ "bbrktbrk", 	0x023B6, 	0x0 }, 	/* bottom above top square bracket : 9573-2003-isoamso*/
{ "bcong", 	0x0224C, 	0x0 }, 	/* /backcong R: reverse congruent : 9573-2003-isoamsr*/
{ "bcy", 	0x00431, 	0x0 }, 	/* =small be, Cyrillic : 9573-2003-isocyr1*/
{ "bdlhar", 	0x02961, 	0x0 }, 	/*  : STIX*/
{ "bdquo", 	0x0201E, 	0x0 }, 	/* double low-9 quotation mark : xhtml1-special*/
{ "bdrhar", 	0x0295D, 	0x0 }, 	/*  : STIX*/
{ "becaus", 	0x02235, 	0x0 }, 	/* /because R: because : 9573-2003-isotech*/
{ "because", 	0x02235, 	0x0 }, 	/* alias ISOTECH becaus : mmlalias*/
{ "bemptyv", 	0x029B0, 	0x0 }, 	/* reversed circle, slash : 9573-2003-isoamso*/
{ "bepsi", 	0x003F6, 	0x0 }, 	/* /backepsilon R: such that : 9573-2003-isoamsr*/
{ "bernou", 	0x0212C, 	0x0 }, 	/* Bernoulli function (script capital B)  : 8879-isotech*/
{ "beta", 	0x003B2, 	0x0 }, 	/* /beta small beta, Greek : 9573-2003-isogrk3*/
{ "beth", 	0x02136, 	0x0 }, 	/* /beth - beth, Hebrew : 9573-2003-isoamso*/
{ "between", 	0x0226C, 	0x0 }, 	/* alias ISOAMSR twixt : mmlalias*/
{ "bfr", 	0x1D51F, 	0x0 }, 	/* /frak b, lower case b : 9573-2003-isomfrk*/
{ "bgr", 	0x003B2, 	0x0 }, 	/* =small beta, Greek : 9573-2003-isogrk1*/
{ "bigcap", 	0x022C2, 	0x0 }, 	/* alias ISOAMSB xcap : mmlalias*/
{ "bigcirc", 	0x025EF, 	0x0 }, 	/* alias ISOAMSB xcirc : mmlalias*/
{ "bigcup", 	0x022C3, 	0x0 }, 	/* alias ISOAMSB xcup : mmlalias*/
{ "bigodot", 	0x02A00, 	0x0 }, 	/* alias ISOAMSB xodot : mmlalias*/
{ "bigoplus", 	0x02A01, 	0x0 }, 	/* alias ISOAMSB xoplus : mmlalias*/
{ "bigotimes", 	0x02A02, 	0x0 }, 	/* alias ISOAMSB xotime : mmlalias*/
{ "bigsqcup", 	0x02A06, 	0x0 }, 	/* alias ISOAMSB xsqcup : mmlalias*/
{ "bigstar", 	0x02605, 	0x0 }, 	/* ISOPUB    starf  : mmlalias*/
{ "bigtriangledown", 	0x025BD, 	0x0 }, 	/* alias ISOAMSB xdtri : mmlalias*/
{ "bigtriangleup", 	0x025B3, 	0x0 }, 	/* alias ISOAMSB xutri : mmlalias*/
{ "biguplus", 	0x02A04, 	0x0 }, 	/* alias ISOAMSB xuplus : mmlalias*/
{ "bigvee", 	0x022C1, 	0x0 }, 	/* alias ISOAMSB xvee : mmlalias*/
{ "bigwedge", 	0x022C0, 	0x0 }, 	/* alias ISOAMSB xwedge : mmlalias*/
{ "bkarow", 	0x0290D, 	0x0 }, 	/* alias ISOAMSA rbarr : mmlalias*/
{ "blacklozenge", 	0x029EB, 	0x0 }, 	/* alias ISOPUB lozf : mmlalias*/
{ "blacksquare", 	0x025AA, 	0x0 }, 	/* ISOTECH  squarf  : mmlalias*/
{ "blacktriangle", 	0x025B4, 	0x0 }, 	/* alias ISOPUB utrif : mmlalias*/
{ "blacktriangledown", 	0x025BE, 	0x0 }, 	/* alias ISOPUB dtrif : mmlalias*/
{ "blacktriangleleft", 	0x025C2, 	0x0 }, 	/* alias ISOPUB ltrif : mmlalias*/
{ "blacktriangleright", 	0x025B8, 	0x0 }, 	/* alias ISOPUB rtrif : mmlalias*/
{ "blank", 	0x02422, 	0x0 }, 	/*  : STIX*/
{ "blank", 	0x02423, 	0x0 }, 	/* =significant blank symbol : 9573-2003-isopub*/
{ "bldhar", 	0x0295E, 	0x0 }, 	/*  : STIX*/
{ "blk12", 	0x02592, 	0x0 }, 	/* =50% shaded block : 9573-2003-isopub*/
{ "blk14", 	0x02591, 	0x0 }, 	/* =25% shaded block : 9573-2003-isopub*/
{ "blk34", 	0x02593, 	0x0 }, 	/* =75% shaded block : 9573-2003-isopub*/
{ "block", 	0x02588, 	0x0 }, 	/* =full block : 9573-2003-isopub*/
{ "bluhar", 	0x0295A, 	0x0 }, 	/*  : STIX*/
{ "bne", 	0x0003D, 	0x020E5 }, 	/* reverse not equal : 9573-2003-isotech*/
{ "bnequiv", 	0x02261, 	0x020E5 }, 	/* reverse not equivalent : 9573-2003-isotech*/
{ "bnot", 	0x02310, 	0x0 }, 	/* reverse not : 9573-2003-isotech*/
{ "bopf", 	0x1D553, 	0x0 }, 	/*  : mmlextra*/
{ "bot", 	0x022A5, 	0x0 }, 	/* alias ISOTECH bottom : mmlalias*/
{ "bottom", 	0x022A5, 	0x0 }, 	/* /bot bottom : 9573-2003-isotech*/
{ "bowtie", 	0x022C8, 	0x0 }, 	/* /bowtie R: : 9573-2003-isoamsr*/
{ "boxDL", 	0x02557, 	0x0 }, 	/* lower left quadrant : 9573-2003-isobox*/
{ "boxDR", 	0x02554, 	0x0 }, 	/* lower right quadrant : 9573-2003-isobox*/
{ "boxDl", 	0x02556, 	0x0 }, 	/* lower left quadrant : 9573-2003-isobox*/
{ "boxDr", 	0x02553, 	0x0 }, 	/* lower right quadrant : 9573-2003-isobox*/
{ "boxH", 	0x02550, 	0x0 }, 	/* horizontal line : 9573-2003-isobox*/
{ "boxHD", 	0x02566, 	0x0 }, 	/* lower left and right quadrants : 9573-2003-isobox*/
{ "boxHU", 	0x02569, 	0x0 }, 	/* upper left and right quadrants : 9573-2003-isobox*/
{ "boxHd", 	0x02564, 	0x0 }, 	/* lower left and right quadrants : 9573-2003-isobox*/
{ "boxHu", 	0x02567, 	0x0 }, 	/* upper left and right quadrants : 9573-2003-isobox*/
{ "boxUL", 	0x0255D, 	0x0 }, 	/* upper left quadrant : 9573-2003-isobox*/
{ "boxUR", 	0x0255A, 	0x0 }, 	/* upper right quadrant : 9573-2003-isobox*/
{ "boxUl", 	0x0255C, 	0x0 }, 	/* upper left quadrant : 9573-2003-isobox*/
{ "boxUr", 	0x02559, 	0x0 }, 	/* upper right quadrant : 9573-2003-isobox*/
{ "boxV", 	0x02551, 	0x0 }, 	/* vertical line : 9573-2003-isobox*/
{ "boxVH", 	0x0256C, 	0x0 }, 	/* all four quadrants : 9573-2003-isobox*/
{ "boxVL", 	0x02563, 	0x0 }, 	/* upper and lower left quadrants : 9573-2003-isobox*/
{ "boxVR", 	0x02560, 	0x0 }, 	/* upper and lower right quadrants : 9573-2003-isobox*/
{ "boxVh", 	0x0256B, 	0x0 }, 	/* all four quadrants : 9573-2003-isobox*/
{ "boxVl", 	0x02562, 	0x0 }, 	/* upper and lower left quadrants : 9573-2003-isobox*/
{ "boxVr", 	0x0255F, 	0x0 }, 	/* upper and lower right quadrants : 9573-2003-isobox*/
{ "boxbox", 	0x029C9, 	0x0 }, 	/* two joined squares : 9573-2003-isoamso*/
{ "boxdL", 	0x02555, 	0x0 }, 	/* lower left quadrant : 9573-2003-isobox*/
{ "boxdR", 	0x02552, 	0x0 }, 	/* lower right quadrant : 9573-2003-isobox*/
{ "boxdl", 	0x02510, 	0x0 }, 	/* lower left quadrant : 9573-2003-isobox*/
{ "boxdr", 	0x0250C, 	0x0 }, 	/* lower right quadrant : 9573-2003-isobox*/
{ "boxh", 	0x02500, 	0x0 }, 	/* horizontal line  : 9573-2003-isobox*/
{ "boxhD", 	0x02565, 	0x0 }, 	/* lower left and right quadrants : 9573-2003-isobox*/
{ "boxhU", 	0x02568, 	0x0 }, 	/* upper left and right quadrants : 9573-2003-isobox*/
{ "boxhd", 	0x0252C, 	0x0 }, 	/* lower left and right quadrants : 9573-2003-isobox*/
{ "boxhu", 	0x02534, 	0x0 }, 	/* upper left and right quadrants : 9573-2003-isobox*/
{ "boxminus", 	0x0229F, 	0x0 }, 	/* alias ISOAMSB minusb : mmlalias*/
{ "boxplus", 	0x0229E, 	0x0 }, 	/* alias ISOAMSB plusb : mmlalias*/
{ "boxtimes", 	0x022A0, 	0x0 }, 	/* alias ISOAMSB timesb : mmlalias*/
{ "boxuL", 	0x0255B, 	0x0 }, 	/* upper left quadrant : 9573-2003-isobox*/
{ "boxuR", 	0x02558, 	0x0 }, 	/* upper right quadrant : 9573-2003-isobox*/
{ "boxul", 	0x02518, 	0x0 }, 	/* upper left quadrant : 9573-2003-isobox*/
{ "boxur", 	0x02514, 	0x0 }, 	/* upper right quadrant : 9573-2003-isobox*/
{ "boxv", 	0x02502, 	0x0 }, 	/* vertical line : 9573-2003-isobox*/
{ "boxvH", 	0x0256A, 	0x0 }, 	/* all four quadrants : 9573-2003-isobox*/
{ "boxvL", 	0x02561, 	0x0 }, 	/* upper and lower left quadrants : 9573-2003-isobox*/
{ "boxvR", 	0x0255E, 	0x0 }, 	/* upper and lower right quadrants : 9573-2003-isobox*/
{ "boxvh", 	0x0253C, 	0x0 }, 	/* all four quadrants : 9573-2003-isobox*/
{ "boxvl", 	0x02524, 	0x0 }, 	/* upper and lower left quadrants : 9573-2003-isobox*/
{ "boxvr", 	0x0251C, 	0x0 }, 	/* upper and lower right quadrants : 9573-2003-isobox*/
{ "bprime", 	0x02035, 	0x0 }, 	/* /backprime - reverse prime : 9573-2003-isoamso*/
{ "brdhar", 	0x0295F, 	0x0 }, 	/*  : STIX*/
{ "breve", 	0x002D8, 	0x0 }, 	/* =breve : 9573-2003-isodia*/
{ "bruhar", 	0x0295B, 	0x0 }, 	/*  : STIX*/
{ "brvbar", 	0x000A6, 	0x0 }, 	/* =broken (vertical) bar : 9573-2003-isonum*/
{ "bscr", 	0x1D4B7, 	0x0 }, 	/* /scr b, script letter b : 9573-2003-isomscr*/
{ "bsemi", 	0x0204F, 	0x0 }, 	/* reverse semi-colon : 9573-2003-isoamso*/
{ "bsim", 	0x0223D, 	0x0 }, 	/* /backsim R: reverse similar : 9573-2003-isoamsr*/
{ "bsime", 	0x022CD, 	0x0 }, 	/* /backsimeq R: reverse similar, eq : 9573-2003-isoamsr*/
{ "bsol", 	0x0005C, 	0x0 }, 	/* /backslash =reverse solidus : 9573-2003-isonum*/
{ "bsolb", 	0x029C5, 	0x0 }, 	/* reverse solidus in square : 9573-2003-isoamsb*/
{ "bsolhsub", 	0x027C8, 	0x0 }, 	/* reverse solidus, subset : 9573-2003-isoamsr*/
{ "btimes", 	0x02A32, 	0x0 }, 	/*  : STIX*/
{ "bulhar", 	0x02960, 	0x0 }, 	/*  : STIX*/
{ "bull", 	0x02022, 	0x0 }, 	/* /bullet B: =round bullet, filled : 9573-2003-isopub*/
{ "bullet", 	0x02022, 	0x0 }, 	/* alias ISOPUB bull : mmlalias*/
{ "bump", 	0x0224E, 	0x0 }, 	/* /Bumpeq R: bumpy equals : 9573-2003-isoamsr*/
{ "bumpE", 	0x02AAE, 	0x0 }, 	/* bump, equals : 9573-2003-isoamsr*/
{ "bumpe", 	0x0224F, 	0x0 }, 	/* /bumpeq R: bumpy equals, equals : 9573-2003-isoamsr*/
{ "bumpeq", 	0x0224F, 	0x0 }, 	/* alias ISOAMSR bumpe : mmlalias*/
{ "burhar", 	0x0295C, 	0x0 }, 	/*  : STIX*/
{ "cacute", 	0x00107, 	0x0 }, 	/* =small c, acute accent : 9573-2003-isolat2*/
{ "cap", 	0x02229, 	0x0 }, 	/* /cap B: intersection : 9573-2003-isotech*/
{ "capand", 	0x02A44, 	0x0 }, 	/* intersection, and : 9573-2003-isoamsb*/
{ "capbrcup", 	0x02A49, 	0x0 }, 	/* intersection, bar, union : 9573-2003-isoamsb*/
{ "capcap", 	0x02A4B, 	0x0 }, 	/* intersection, intersection, joined : 9573-2003-isoamsb*/
{ "capcup", 	0x02A47, 	0x0 }, 	/* intersection above union : 9573-2003-isoamsb*/
{ "capdot", 	0x02A40, 	0x0 }, 	/* intersection, with dot : 9573-2003-isoamsb*/
{ "capint", 	0x02A19, 	0x0 }, 	/*  : STIX*/
{ "caps", 	0x02229, 	0x0FE00 }, 	/* intersection, serifs : 9573-2003-isoamsb*/
{ "caret", 	0x02041, 	0x0 }, 	/* =caret (insertion mark) : 9573-2003-isopub*/
{ "caron", 	0x002C7, 	0x0 }, 	/* =caron : 9573-2003-isodia*/
{ "ccaps", 	0x02A4D, 	0x0 }, 	/* closed intersection, serifs : 9573-2003-isoamsb*/
{ "ccaron", 	0x0010D, 	0x0 }, 	/* =small c, caron : 9573-2003-isolat2*/
{ "ccedil", 	0x000E7, 	0x0 }, 	/* =small c, cedilla : 9573-2003-isolat1*/
{ "ccirc", 	0x00109, 	0x0 }, 	/* =small c, circumflex accent : 9573-2003-isolat2*/
{ "ccups", 	0x02A4C, 	0x0 }, 	/* closed union, serifs : 9573-2003-isoamsb*/
{ "ccupssm", 	0x02A50, 	0x0 }, 	/* closed union, serifs, smash product : 9573-2003-isoamsb*/
{ "cdot", 	0x0010B, 	0x0 }, 	/* =small c, dot above : 9573-2003-isolat2*/
{ "cedil", 	0x000B8, 	0x0 }, 	/* =cedilla : 9573-2003-isodia*/
{ "cemptyv", 	0x029B2, 	0x0 }, 	/* circle, slash, small circle above : 9573-2003-isoamso*/
{ "cent", 	0x000A2, 	0x0 }, 	/* =cent sign : 9573-2003-isonum*/
{ "centerdot", 	0x000B7, 	0x0 }, 	/* alias ISONUM middot : mmlalias*/
{ "cfr", 	0x1D520, 	0x0 }, 	/* /frak c, lower case c : 9573-2003-isomfrk*/
{ "chcy", 	0x00447, 	0x0 }, 	/* =small che, Cyrillic : 9573-2003-isocyr1*/
{ "check", 	0x02713, 	0x0 }, 	/* /checkmark =tick, check mark : 9573-2003-isopub*/
{ "checkmark", 	0x02713, 	0x0 }, 	/* alias ISOPUB check : mmlalias*/
{ "chi", 	0x003C7, 	0x0 }, 	/* /chi small chi, Greek : 9573-2003-isogrk3*/
{ "cir", 	0x025CB, 	0x0 }, 	/* /circ B: =circle, open : 9573-2003-isopub*/
{ "cirE", 	0x029C3, 	0x0 }, 	/* circle, two horizontal stroked to the right : 9573-2003-isoamso*/
{ "cirb", 	0x029C7, 	0x0 }, 	/*  : STIX*/
{ "circ", 	0x002C6, 	0x0 }, 	/* circumflex accent : 9573-2003-isodia*/
{ "circeq", 	0x02257, 	0x0 }, 	/* alias ISOAMSR cire : mmlalias*/
{ "circlearrowleft", 	0x021BA, 	0x0 }, 	/* alias ISOAMSA olarr : mmlalias*/
{ "circlearrowright", 	0x021BB, 	0x0 }, 	/* alias ISOAMSA orarr : mmlalias*/
{ "circledR", 	0x000AE, 	0x0 }, 	/* alias ISONUM reg : mmlalias*/
{ "circledS", 	0x024C8, 	0x0 }, 	/* alias ISOAMSO oS : mmlalias*/
{ "circledast", 	0x0229B, 	0x0 }, 	/* alias ISOAMSB oast : mmlalias*/
{ "circledcirc", 	0x0229A, 	0x0 }, 	/* alias ISOAMSB ocir : mmlalias*/
{ "circleddash", 	0x0229D, 	0x0 }, 	/* alias ISOAMSB odash : mmlalias*/
{ "cirdarr", 	0x029EC, 	0x0 }, 	/*  : STIX*/
{ "cire", 	0x02257, 	0x0 }, 	/* /circeq R: circle, equals : 9573-2003-isoamsr*/
{ "cirerr", 	0x029F2, 	0x0 }, 	/*  : STIX*/
{ "cirfdarr", 	0x029ED, 	0x0 }, 	/*  : STIX*/
{ "cirferr", 	0x029F3, 	0x0 }, 	/*  : STIX*/
{ "cirfnint", 	0x02A10, 	0x0 }, 	/* circulation function : 9573-2003-isotech*/
{ "cirmid", 	0x02AEF, 	0x0 }, 	/* circle, mid below : 9573-2003-isoamsa*/
{ "cirscir", 	0x029C2, 	0x0 }, 	/* circle, small circle to the right : 9573-2003-isoamso*/
{ "closur", 	0x02050, 	0x0 }, 	/*  : STIX*/
{ "clubs", 	0x02663, 	0x0 }, 	/* black club suit = shamrock : xhtml1-symbol*/
{ "clubsuit", 	0x02663, 	0x0 }, 	/* ISOPUB    clubs  : mmlalias*/
{ "colon", 	0x0003A, 	0x0 }, 	/* /colon P: : 9573-2003-isonum*/
{ "colone", 	0x02254, 	0x0 }, 	/* /coloneq R: colon, equals : 9573-2003-isoamsr*/
{ "coloneq", 	0x02254, 	0x0 }, 	/* alias ISOAMSR colone : mmlalias*/
{ "comma", 	0x0002C, 	0x0 }, 	/* P: =comma : 9573-2003-isonum*/
{ "commat", 	0x00040, 	0x0 }, 	/* =commercial at : 9573-2003-isonum*/
{ "comp", 	0x02201, 	0x0 }, 	/* /complement - complement sign : 9573-2003-isoamso*/
{ "compfn", 	0x02218, 	0x0 }, 	/* /circ B: composite function (small circle) : 9573-2003-isotech*/
{ "complement", 	0x02201, 	0x0 }, 	/* alias ISOAMSO comp : mmlalias*/
{ "complexes", 	0x02102, 	0x0 }, 	/* the field of complex numbers : mmlalias*/
{ "cong", 	0x02245, 	0x0 }, 	/* /cong R: congruent with : 9573-2003-isotech*/
{ "congdot", 	0x02A6D, 	0x0 }, 	/* congruent, dot : 9573-2003-isoamsr*/
{ "conint", 	0x0222E, 	0x0 }, 	/* /oint L: contour integral operator : 9573-2003-isotech*/
{ "copf", 	0x1D554, 	0x0 }, 	/*  : mmlextra*/
{ "coprod", 	0x02210, 	0x0 }, 	/* /coprod L: coproduct operator : 9573-2003-isoamsb*/
{ "copy", 	0x000A9, 	0x0 }, 	/* =copyright sign : 9573-2003-isonum*/
{ "copysr", 	0x02117, 	0x0 }, 	/* =sound recording copyright sign : 9573-2003-isopub*/
{ "crarr", 	0x021B5, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "cross", 	0x02717, 	0x0 }, 	/* =ballot cross : 9573-2003-isopub*/
{ "cscr", 	0x1D4B8, 	0x0 }, 	/* /scr c, script letter c : 9573-2003-isomscr*/
{ "csub", 	0x02ACF, 	0x0 }, 	/* subset, closed : 9573-2003-isoamsr*/
{ "csube", 	0x02AD1, 	0x0 }, 	/* subset, closed, equals : 9573-2003-isoamsr*/
{ "csup", 	0x02AD0, 	0x0 }, 	/* superset, closed : 9573-2003-isoamsr*/
{ "csupe", 	0x02AD2, 	0x0 }, 	/* superset, closed, equals : 9573-2003-isoamsr*/
{ "ctdot", 	0x022EF, 	0x0 }, 	/* /cdots, three dots, centered : 9573-2003-isotech*/
{ "cudarrl", 	0x02938, 	0x0 }, 	/* left, curved, down arrow : 9573-2003-isoamsa*/
{ "cudarrr", 	0x02935, 	0x0 }, 	/* right, curved, down arrow : 9573-2003-isoamsa*/
{ "cudarrr", 	0x02939, 	0x0 }, 	/*  : STIX*/
{ "cuepr", 	0x022DE, 	0x0 }, 	/* /curlyeqprec R: curly eq, precedes : 9573-2003-isoamsr*/
{ "cuesc", 	0x022DF, 	0x0 }, 	/* /curlyeqsucc R: curly eq, succeeds : 9573-2003-isoamsr*/
{ "cularr", 	0x021B6, 	0x0 }, 	/* /curvearrowleft A: left curved arrow : 9573-2003-isoamsa*/
{ "cularrp", 	0x0293D, 	0x0 }, 	/* curved left arrow with plus : 9573-2003-isoamsa*/
{ "cup", 	0x0222A, 	0x0 }, 	/* /cup B: union or logical sum : 9573-2003-isotech*/
{ "cupbrcap", 	0x02A48, 	0x0 }, 	/* union, bar, intersection : 9573-2003-isoamsb*/
{ "cupcap", 	0x02A46, 	0x0 }, 	/* union above intersection : 9573-2003-isoamsb*/
{ "cupcup", 	0x02A4A, 	0x0 }, 	/* union, union, joined : 9573-2003-isoamsb*/
{ "cupdot", 	0x0228D, 	0x0 }, 	/* union, with dot : 9573-2003-isoamsb*/
{ "cupint", 	0x02A1A, 	0x0 }, 	/*  : STIX*/
{ "cupor", 	0x02A45, 	0x0 }, 	/* union, or : 9573-2003-isoamsb*/
{ "cupre", 	0x0227C, 	0x0 }, 	/* /curlypreceq R: curly precedes, eq : 8879-isoamsr*/
{ "cups", 	0x0222A, 	0x0FE00 }, 	/* union, serifs : 9573-2003-isoamsb*/
{ "curarr", 	0x021B7, 	0x0 }, 	/* /curvearrowright A: rt curved arrow : 9573-2003-isoamsa*/
{ "curarrm", 	0x0293C, 	0x0 }, 	/* curved right arrow with minus : 9573-2003-isoamsa*/
{ "curlyeqprec", 	0x022DE, 	0x0 }, 	/* alias ISOAMSR cuepr : mmlalias*/
{ "curlyeqsucc", 	0x022DF, 	0x0 }, 	/* alias ISOAMSR cuesc : mmlalias*/
{ "curlyvee", 	0x022CE, 	0x0 }, 	/* alias ISOAMSB cuvee : mmlalias*/
{ "curlywedge", 	0x022CF, 	0x0 }, 	/* alias ISOAMSB cuwed : mmlalias*/
{ "curren", 	0x000A4, 	0x0 }, 	/* =general currency sign : 9573-2003-isonum*/
{ "curvearrowleft", 	0x021B6, 	0x0 }, 	/* alias ISOAMSA cularr : mmlalias*/
{ "curvearrowright", 	0x021B7, 	0x0 }, 	/* alias ISOAMSA curarr : mmlalias*/
{ "cuvee", 	0x022CE, 	0x0 }, 	/* /curlyvee B: curly logical or : 9573-2003-isoamsb*/
{ "cuwed", 	0x022CF, 	0x0 }, 	/* /curlywedge B: curly logical and : 9573-2003-isoamsb*/
{ "cwconint", 	0x02232, 	0x0 }, 	/* contour integral, clockwise : 9573-2003-isotech*/
{ "cwint", 	0x02231, 	0x0 }, 	/* clockwise integral : 9573-2003-isotech*/
{ "cylcty", 	0x0232D, 	0x0 }, 	/* cylindricity : 9573-2003-isotech*/
{ "dAarr", 	0x0290B, 	0x0 }, 	/*  : STIX*/
{ "dArr", 	0x021D3, 	0x0 }, 	/* /Downarrow A: down dbl arrow : 9573-2003-isoamsa*/
{ "dHar", 	0x02965, 	0x0 }, 	/* down harpoon-left, down harpoon-right : 9573-2003-isoamsa*/
{ "dagger", 	0x02020, 	0x0 }, 	/* /dagger B: dagger relation : 9573-2003-isoamsb*/
{ "dalembrt", 	0x029E0, 	0x0 }, 	/*  : STIX*/
{ "daleth", 	0x02138, 	0x0 }, 	/* /daleth - daleth, Hebrew : 9573-2003-isoamso*/
{ "darr", 	0x02193, 	0x0 }, 	/* /downarrow A: =downward arrow : 9573-2003-isonum*/
{ "darr2", 	0x021CA, 	0x0 }, 	/* /downdownarrows A: two down arrows  : 8879-isoamsa*/
{ "darrb", 	0x02913, 	0x0 }, 	/*  : STIX*/
{ "darrln", 	0x02908, 	0x0 }, 	/* 2356 : STIX*/
{ "dash", 	0x02010, 	0x0 }, 	/* =hyphen (true graphic) : 9573-2003-isopub*/
{ "dashV", 	0x02AE3, 	0x0 }, 	/*  : STIX*/
{ "dashv", 	0x022A3, 	0x0 }, 	/* /dashv R: dash, vertical : 9573-2003-isoamsr*/
{ "dbkarow", 	0x0290F, 	0x0 }, 	/* alias ISOAMSA rBarr : mmlalias*/
{ "dblac", 	0x002DD, 	0x0 }, 	/* =double acute accent : 9573-2003-isodia*/
{ "dcaron", 	0x0010F, 	0x0 }, 	/* =small d, caron : 9573-2003-isolat2*/
{ "dcy", 	0x00434, 	0x0 }, 	/* =small de, Cyrillic : 9573-2003-isocyr1*/
{ "dd", 	0x02146, 	0x0 }, 	/* d for use in differentials, e.g., within integrals : mmlextra*/
{ "ddagger", 	0x02021, 	0x0 }, 	/* alias ISOPUB Dagger : mmlalias*/
{ "ddarr", 	0x021CA, 	0x0 }, 	/* /downdownarrows A: two down arrows : 9573-2003-isoamsa*/
{ "ddotseq", 	0x02A77, 	0x0 }, 	/* alias ISOAMSR eDDot : mmlalias*/
{ "deg", 	0x000B0, 	0x0 }, 	/* =degree sign : 9573-2003-isonum*/
{ "delta", 	0x003B4, 	0x0 }, 	/* /delta small delta, Greek : 9573-2003-isogrk3*/
{ "demptyv", 	0x029B1, 	0x0 }, 	/* circle, slash, bar above : 9573-2003-isoamso*/
{ "dfisht", 	0x0297F, 	0x0 }, 	/* down fish tail : 9573-2003-isoamsa*/
{ "dfr", 	0x1D521, 	0x0 }, 	/* /frak d, lower case d : 9573-2003-isomfrk*/
{ "dgr", 	0x003B4, 	0x0 }, 	/* =small delta, Greek : 9573-2003-isogrk1*/
{ "dharl", 	0x021C3, 	0x0 }, 	/* /downharpoonleft A: dn harpoon-left : 9573-2003-isoamsa*/
{ "dharr", 	0x021C2, 	0x0 }, 	/* /downharpoonright A: down harpoon-rt : 9573-2003-isoamsa*/
{ "diam", 	0x022C4, 	0x0 }, 	/* /diamond B: open diamond : 9573-2003-isoamsb*/
{ "diamdarr", 	0x029EA, 	0x0 }, 	/*  : STIX*/
{ "diamerr", 	0x029F0, 	0x0 }, 	/*  : STIX*/
{ "diamerrf", 	0x029F1, 	0x0 }, 	/*  : STIX*/
{ "diamond", 	0x022C4, 	0x0 }, 	/* alias ISOAMSB diam : mmlalias*/
{ "diamondsuit", 	0x02666, 	0x0 }, 	/* ISOPUB    diams  : mmlalias*/
{ "diams", 	0x02666, 	0x0 }, 	/* black diamond suit : xhtml1-symbol*/
{ "die", 	0x000A8, 	0x0 }, 	/* =dieresis : 9573-2003-isodia*/
{ "digamma", 	0x003DD, 	0x0 }, 	/* alias ISOGRK3 gammad : mmlalias*/
{ "disin", 	0x022F2, 	0x0 }, 	/* set membership, long horizontal stroke : 9573-2003-isotech*/
{ "div", 	0x000F7, 	0x0 }, 	/* alias ISONUM divide : mmlalias*/
{ "divide", 	0x000F7, 	0x0 }, 	/* /div B: =divide sign : 9573-2003-isonum*/
{ "divideontimes", 	0x022C7, 	0x0 }, 	/* alias ISOAMSB divonx : mmlalias*/
{ "divonx", 	0x022C7, 	0x0 }, 	/* /divideontimes B: division on times : 9573-2003-isoamsb*/
{ "djcy", 	0x00452, 	0x0 }, 	/* =small dje, Serbian : 9573-2003-isocyr2*/
{ "dlarr", 	0x02199, 	0x0 }, 	/* /swarrow A: downward l arrow  : 8879-isoamsa*/
{ "dlcorn", 	0x0231E, 	0x0 }, 	/* /llcorner O: lower left corner : 9573-2003-isoamsc*/
{ "dlcrop", 	0x0230D, 	0x0 }, 	/* downward left crop mark  : 9573-2003-isopub*/
{ "dlharb", 	0x02959, 	0x0 }, 	/*  : STIX*/
{ "dollar", 	0x00024, 	0x0 }, 	/* =dollar sign : 9573-2003-isonum*/
{ "dopf", 	0x1D555, 	0x0 }, 	/*  : mmlextra*/
{ "dot", 	0x002D9, 	0x0 }, 	/* =dot above : 9573-2003-isodia*/
{ "doteq", 	0x02250, 	0x0 }, 	/* alias ISOAMSR esdot : mmlalias*/
{ "doteqdot", 	0x02251, 	0x0 }, 	/* alias ISOAMSR eDot : mmlalias*/
{ "dotminus", 	0x02238, 	0x0 }, 	/* alias ISOAMSB minusd : mmlalias*/
{ "dotplus", 	0x02214, 	0x0 }, 	/* alias ISOAMSB plusdo : mmlalias*/
{ "dotsquare", 	0x022A1, 	0x0 }, 	/* alias ISOAMSB sdotb : mmlalias*/
{ "doublebarwedge", 	0x02306, 	0x0 }, 	/* alias ISOAMSB Barwed : mmlalias*/
{ "downarrow", 	0x02193, 	0x0 }, 	/* alias ISONUM darr : mmlalias*/
{ "downdownarrows", 	0x021CA, 	0x0 }, 	/* alias ISOAMSA ddarr : mmlalias*/
{ "downharpoonleft", 	0x021C3, 	0x0 }, 	/* alias ISOAMSA dharl : mmlalias*/
{ "downharpoonright", 	0x021C2, 	0x0 }, 	/* alias ISOAMSA dharr : mmlalias*/
{ "drarr", 	0x02198, 	0x0 }, 	/* /searrow A: downward rt arrow  : 8879-isoamsa*/
{ "drbkarow", 	0x02910, 	0x0 }, 	/* alias ISOAMSA RBarr : mmlalias*/
{ "drcorn", 	0x0231F, 	0x0 }, 	/* /lrcorner C: lower right corner : 9573-2003-isoamsc*/
{ "drcrop", 	0x0230C, 	0x0 }, 	/* downward right crop mark  : 9573-2003-isopub*/
{ "drharb", 	0x02955, 	0x0 }, 	/*  : STIX*/
{ "dscr", 	0x1D4B9, 	0x0 }, 	/* /scr d, script letter d : 9573-2003-isomscr*/
{ "dscy", 	0x00455, 	0x0 }, 	/* =small dse, Macedonian : 9573-2003-isocyr2*/
{ "dsol", 	0x029F6, 	0x0 }, 	/* solidus, bar above : 9573-2003-isotech*/
{ "dstrok", 	0x00111, 	0x0 }, 	/* =small d, stroke : 9573-2003-isolat2*/
{ "dtdot", 	0x022F1, 	0x0 }, 	/* /ddots, three dots, descending : 9573-2003-isotech*/
{ "dtri", 	0x025BF, 	0x0 }, 	/* /triangledown =down triangle, open : 9573-2003-isopub*/
{ "dtrif", 	0x025BE, 	0x0 }, 	/* /blacktriangledown =dn tri, filled : 9573-2003-isopub*/
{ "dtrilf", 	0x029E8, 	0x0 }, 	/*  : STIX*/
{ "dtrirf", 	0x029E9, 	0x0 }, 	/*  : STIX*/
{ "duarr", 	0x021F5, 	0x0 }, 	/* down arrow, up arrow : 9573-2003-isoamsa*/
{ "duhar", 	0x0296F, 	0x0 }, 	/* down harp, up harp : 9573-2003-isoamsa*/
{ "dumap", 	0x029DF, 	0x0 }, 	/*  : STIX*/
{ "dwangle", 	0x029A6, 	0x0 }, 	/* large downward pointing angle : 9573-2003-isotech*/
{ "dzcy", 	0x0045F, 	0x0 }, 	/* =small dze, Serbian : 9573-2003-isocyr2*/
{ "dzigrarr", 	0x027FF, 	0x0 }, 	/* right long zig-zag arrow : 9573-2003-isoamsa*/
{ "eDDot", 	0x02A77, 	0x0 }, 	/* /ddotseq R: equal with four dots : 9573-2003-isoamsr*/
{ "eDot", 	0x02251, 	0x0 }, 	/* /doteqdot /Doteq R: eq, even dots : 9573-2003-isoamsr*/
{ "eacgr", 	0x003AD, 	0x0 }, 	/* =small epsilon, accent, Greek : 9573-2003-isogrk2*/
{ "eacute", 	0x000E9, 	0x0 }, 	/* =small e, acute accent : 9573-2003-isolat1*/
{ "easter", 	0x02A6E, 	0x0 }, 	/* equal, asterisk above : 9573-2003-isoamsr*/
{ "ecaron", 	0x0011B, 	0x0 }, 	/* =small e, caron : 9573-2003-isolat2*/
{ "ecir", 	0x02256, 	0x0 }, 	/* /eqcirc R: circle on equals sign : 9573-2003-isoamsr*/
{ "ecirc", 	0x000EA, 	0x0 }, 	/* =small e, circumflex accent : 9573-2003-isolat1*/
{ "ecolon", 	0x02255, 	0x0 }, 	/* /eqcolon R: equals, colon : 9573-2003-isoamsr*/
{ "ecy", 	0x0044D, 	0x0 }, 	/* =small e, Cyrillic : 9573-2003-isocyr1*/
{ "edot", 	0x00117, 	0x0 }, 	/* =small e, dot above : 9573-2003-isolat2*/
{ "ee", 	0x02147, 	0x0 }, 	/* e use for the exponential base of the natural logarithms : mmlextra*/
{ "eeacgr", 	0x003AE, 	0x0 }, 	/* =small eta, accent, Greek : 9573-2003-isogrk2*/
{ "eegr", 	0x003B7, 	0x0 }, 	/* =small eta, Greek : 9573-2003-isogrk1*/
{ "efDot", 	0x02252, 	0x0 }, 	/* /fallingdotseq R: eq, falling dots : 9573-2003-isoamsr*/
{ "efr", 	0x1D522, 	0x0 }, 	/* /frak e, lower case e : 9573-2003-isomfrk*/
{ "eg", 	0x02A9A, 	0x0 }, 	/* equal-or-greater : 9573-2003-isoamsr*/
{ "egr", 	0x003B5, 	0x0 }, 	/* =small epsilon, Greek : 9573-2003-isogrk1*/
{ "egrave", 	0x000E8, 	0x0 }, 	/* =small e, grave accent : 9573-2003-isolat1*/
{ "egs", 	0x02A96, 	0x0 }, 	/*  : STIX*/
{ "egsdot", 	0x02A98, 	0x0 }, 	/* equal-or-greater, slanted, dot inside : 9573-2003-isoamsr*/
{ "el", 	0x02A99, 	0x0 }, 	/* equal-or-less : 9573-2003-isoamsr*/
{ "elinters", 	0x023E7, 	0x0 }, 	/* electrical intersection : 9573-2003-isotech*/
{ "ell", 	0x02113, 	0x0 }, 	/* /ell - cursive small l : 9573-2003-isoamso*/
{ "els", 	0x02A95, 	0x0 }, 	/*  : STIX*/
{ "elsdot", 	0x02A97, 	0x0 }, 	/* equal-or-less, slanted, dot inside : 9573-2003-isoamsr*/
{ "emacr", 	0x00113, 	0x0 }, 	/* =small e, macron : 9573-2003-isolat2*/
{ "empty", 	0x02205, 	0x0 }, 	/* empty set = null set = diameter : xhtml1-symbol*/
{ "emptyset", 	0x02205, 	0x0 }, 	/* alias ISOAMSO empty : mmlalias*/
{ "emptyv", 	0x02205, 	0x0 }, 	/* /varnothing - circle, slash : 9573-2003-isoamso*/
{ "emsp", 	0x02003, 	0x0 }, 	/* =em space : 9573-2003-isopub*/
{ "emsp13", 	0x02004, 	0x0 }, 	/* =1/3-em space : 9573-2003-isopub*/
{ "emsp14", 	0x02005, 	0x0 }, 	/* =1/4-em space : 9573-2003-isopub*/
{ "eng", 	0x0014B, 	0x0 }, 	/* =small eng, Lapp : 9573-2003-isolat2*/
{ "ensp", 	0x02002, 	0x0 }, 	/* =en space (1/2-em) : 9573-2003-isopub*/
{ "eogon", 	0x00119, 	0x0 }, 	/* =small e, ogonek : 9573-2003-isolat2*/
{ "eopf", 	0x1D556, 	0x0 }, 	/*  : mmlextra*/
{ "epar", 	0x022D5, 	0x0 }, 	/* parallel, equal; equal or parallel : 9573-2003-isotech*/
{ "eparsl", 	0x029E3, 	0x0 }, 	/* parallel, slanted, equal; homothetically congruent to : 9573-2003-isotech*/
{ "eplus", 	0x02A71, 	0x0 }, 	/* equal, plus : 9573-2003-isoamsb*/
{ "epsi", 	0x003B5, 	0x0 }, 	/* /epsilon : 9573-2003-isogrk3*/
{ "epsi", 	0x003F5, 	0x0 }, 	/* /straightepsilon, small epsilon, Greek : 9573-1991-isogrk3*/
{ "epsilon", 	0x003B5, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "epsis", 	0x003F5, 	0x0 }, 	/* /straightepsilon : 8879-isogrk3*/
{ "epsiv", 	0x003F5, 	0x0 }, 	/* /straightepsilon, small epsilon, Greek : 9573-2003-isogrk3*/
{ "eqcirc", 	0x02256, 	0x0 }, 	/* alias ISOAMSR ecir : mmlalias*/
{ "eqcolon", 	0x02255, 	0x0 }, 	/* alias ISOAMSR ecolon : mmlalias*/
{ "eqeq", 	0x02A75, 	0x0 }, 	/*  : STIX*/
{ "eqsim", 	0x02242, 	0x0 }, 	/* alias ISOAMSR esim : mmlalias*/
{ "eqslantgtr", 	0x02A96, 	0x0 }, 	/* alias ISOAMSR egs : mmlalias*/
{ "eqslantless", 	0x02A95, 	0x0 }, 	/* alias ISOAMSR els : mmlalias*/
{ "equals", 	0x0003D, 	0x0 }, 	/* =equals sign R: : 9573-2003-isonum*/
{ "equest", 	0x0225F, 	0x0 }, 	/* /questeq R: equal with questionmark : 9573-2003-isoamsr*/
{ "equiv", 	0x02261, 	0x0 }, 	/* /equiv R: identical with : 9573-2003-isotech*/
{ "equivDD", 	0x02A78, 	0x0 }, 	/* equivalent, four dots above : 9573-2003-isoamsr*/
{ "eqvparsl", 	0x029E5, 	0x0 }, 	/* equivalent, equal; congruent and parallel : 9573-2003-isotech*/
{ "erDot", 	0x02253, 	0x0 }, 	/* /risingdotseq R: eq, rising dots : 9573-2003-isoamsr*/
{ "erarr", 	0x02971, 	0x0 }, 	/* equal, right arrow below : 9573-2003-isoamsa*/
{ "escr", 	0x0212F, 	0x0 }, 	/* /scr e, script letter e : 9573-2003-isomscr*/
{ "esdot", 	0x02250, 	0x0 }, 	/* /doteq R: equals, single dot above : 9573-2003-isoamsr*/
{ "esim", 	0x02242, 	0x0 }, 	/* /esim R: equals, similar : 9573-2003-isoamsr*/
{ "eta", 	0x003B7, 	0x0 }, 	/* /eta small eta, Greek : 9573-2003-isogrk3*/
{ "eth", 	0x000F0, 	0x0 }, 	/* =small eth, Icelandic : 9573-2003-isolat1*/
{ "euml", 	0x000EB, 	0x0 }, 	/* =small e, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "euro", 	0x020AC, 	0x0 }, 	/*  : xhtml1-special*/
{ "excl", 	0x00021, 	0x0 }, 	/* =exclamation mark : 9573-2003-isonum*/
{ "exist", 	0x02203, 	0x0 }, 	/* /exists at least one exists : 9573-2003-isotech*/
{ "expectation", 	0x02130, 	0x0 }, 	/* expectation (operator) : mmlalias*/
{ "exponentiale", 	0x02147, 	0x0 }, 	/* base of the Napierian logarithms : mmlalias*/
{ "fallingdotseq", 	0x02252, 	0x0 }, 	/* alias ISOAMSR efDot : mmlalias*/
{ "fbowtie", 	0x029D3, 	0x0 }, 	/*  : STIX*/
{ "fcy", 	0x00444, 	0x0 }, 	/* =small ef, Cyrillic : 9573-2003-isocyr1*/
{ "fdiag", 	0x02572, 	0x0 }, 	/*  : STIX*/
{ "fdiordi", 	0x0292C, 	0x0 }, 	/*  : STIX*/
{ "fdonearr", 	0x0292F, 	0x0 }, 	/*  : STIX*/
{ "female", 	0x02640, 	0x0 }, 	/* =female symbol : 9573-2003-isopub*/
{ "ffilig", 	0x0FB03, 	0x0 }, 	/* small ffi ligature : 9573-2003-isopub*/
{ "fflig", 	0x0FB00, 	0x0 }, 	/* small ff ligature : 9573-2003-isopub*/
{ "ffllig", 	0x0FB04, 	0x0 }, 	/* small ffl ligature : 9573-2003-isopub*/
{ "ffr", 	0x1D523, 	0x0 }, 	/* /frak f, lower case f : 9573-2003-isomfrk*/
{ "fhrglass", 	0x029D7, 	0x0 }, 	/*  : STIX*/
{ "filig", 	0x0FB01, 	0x0 }, 	/* small fi ligature : 9573-2003-isopub*/
{ "fjlig", 	0x00066, 	0x0006A }, 	/* small fj ligature : 9573-2003-isopub*/
{ "flat", 	0x0266D, 	0x0 }, 	/* /flat =musical flat : 9573-2003-isopub*/
{ "fllig", 	0x0FB02, 	0x0 }, 	/* small fl ligature : 9573-2003-isopub*/
{ "fltns", 	0x025B1, 	0x0 }, 	/* flatness : 9573-2003-isotech*/
{ "fnof", 	0x00192, 	0x0 }, 	/* function of (italic small f) : 9573-2003-isotech*/
{ "fnof", 	0x1D453, 	0x0 }, 	/*  : STIX*/
{ "fopf", 	0x1D557, 	0x0 }, 	/*  : mmlextra*/
{ "forall", 	0x02200, 	0x0 }, 	/* /forall for all : 9573-2003-isotech*/
{ "fork", 	0x022D4, 	0x0 }, 	/* /pitchfork R: pitchfork : 9573-2003-isoamsr*/
{ "forkv", 	0x02AD9, 	0x0 }, 	/* fork, variant : 9573-2003-isoamsr*/
{ "fpartint", 	0x02A0D, 	0x0 }, 	/* finite part integral : 9573-2003-isotech*/
{ "frac12", 	0x000BD, 	0x0 }, 	/* =fraction one-half : 9573-2003-isonum*/
{ "frac13", 	0x02153, 	0x0 }, 	/* =fraction one-third : 9573-2003-isopub*/
{ "frac14", 	0x000BC, 	0x0 }, 	/* =fraction one-quarter : 9573-2003-isonum*/
{ "frac15", 	0x02155, 	0x0 }, 	/* =fraction one-fifth : 9573-2003-isopub*/
{ "frac16", 	0x02159, 	0x0 }, 	/* =fraction one-sixth : 9573-2003-isopub*/
{ "frac18", 	0x0215B, 	0x0 }, 	/* =fraction one-eighth : 9573-2003-isonum*/
{ "frac23", 	0x02154, 	0x0 }, 	/* =fraction two-thirds : 9573-2003-isopub*/
{ "frac25", 	0x02156, 	0x0 }, 	/* =fraction two-fifths : 9573-2003-isopub*/
{ "frac34", 	0x000BE, 	0x0 }, 	/* =fraction three-quarters : 9573-2003-isonum*/
{ "frac35", 	0x02157, 	0x0 }, 	/* =fraction three-fifths : 9573-2003-isopub*/
{ "frac38", 	0x0215C, 	0x0 }, 	/* =fraction three-eighths : 9573-2003-isonum*/
{ "frac45", 	0x02158, 	0x0 }, 	/* =fraction four-fifths : 9573-2003-isopub*/
{ "frac56", 	0x0215A, 	0x0 }, 	/* =fraction five-sixths : 9573-2003-isopub*/
{ "frac58", 	0x0215D, 	0x0 }, 	/* =fraction five-eighths : 9573-2003-isonum*/
{ "frac78", 	0x0215E, 	0x0 }, 	/* =fraction seven-eighths : 9573-2003-isonum*/
{ "frasl", 	0x02044, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "frown", 	0x02322, 	0x0 }, 	/* /frown R: down curve : 9573-2003-isoamsr*/
{ "fscr", 	0x1D4BB, 	0x0 }, 	/* /scr f, script letter f : 9573-2003-isomscr*/
{ "gE", 	0x02267, 	0x0 }, 	/* /geqq R: greater, double equals : 9573-2003-isoamsr*/
{ "gEl", 	0x02A8C, 	0x0 }, 	/*  : STIX*/
{ "gacute", 	0x001F5, 	0x0 }, 	/* =small g, acute accent : 9573-2003-isolat2*/
{ "gamma", 	0x003B3, 	0x0 }, 	/* /gamma small gamma, Greek : 9573-2003-isogrk3*/
{ "gammad", 	0x003DD, 	0x0 }, 	/*  : STIX*/
{ "gap", 	0x02A86, 	0x0 }, 	/* /gtrapprox R: greater, approximate : 9573-2003-isoamsr*/
{ "gbreve", 	0x0011F, 	0x0 }, 	/* =small g, breve : 9573-2003-isolat2*/
{ "gcedil", 	0x00123, 	0x0 }, 	/*  : ISOlat2*/
{ "gcirc", 	0x0011D, 	0x0 }, 	/* =small g, circumflex accent : 9573-2003-isolat2*/
{ "gcy", 	0x00433, 	0x0 }, 	/* =small ghe, Cyrillic : 9573-2003-isocyr1*/
{ "gdot", 	0x00121, 	0x0 }, 	/* =small g, dot above : 9573-2003-isolat2*/
{ "ge", 	0x02265, 	0x0 }, 	/* /geq /ge R: greater-than-or-equal : 9573-2003-isotech*/
{ "gel", 	0x022DB, 	0x0 }, 	/* /gtreqless R: greater, equals, less : 9573-2003-isoamsr*/
{ "geq", 	0x02265, 	0x0 }, 	/* alias ISOTECH ge : mmlalias*/
{ "geqq", 	0x02267, 	0x0 }, 	/* alias ISOAMSR gE : mmlalias*/
{ "geqslant", 	0x02A7E, 	0x0 }, 	/* alias ISOAMSR ges : mmlalias*/
{ "ges", 	0x02A7E, 	0x0 }, 	/* /geqslant R: gt-or-equal, slanted : 9573-2003-isoamsr*/
{ "gescc", 	0x02AA9, 	0x0 }, 	/* greater than, closed by curve, equal, slanted : 9573-2003-isoamsr*/
{ "gesdot", 	0x02A80, 	0x0 }, 	/* greater-than-or-equal, slanted, dot inside : 9573-2003-isoamsr*/
{ "gesdoto", 	0x02A82, 	0x0 }, 	/* greater-than-or-equal, slanted, dot above : 9573-2003-isoamsr*/
{ "gesdotol", 	0x02A84, 	0x0 }, 	/* greater-than-or-equal, slanted, dot above left : 9573-2003-isoamsr*/
{ "gesl", 	0x022DB, 	0x0FE00 }, 	/* greater, equal, slanted, less : 9573-2003-isoamsr*/
{ "gesles", 	0x02A94, 	0x0 }, 	/* greater, equal, slanted, less, equal, slanted : 9573-2003-isoamsr*/
{ "gfr", 	0x1D524, 	0x0 }, 	/* /frak g, lower case g : 9573-2003-isomfrk*/
{ "gg", 	0x0226B, 	0x0 }, 	/* alias ISOAMSR Gt : mmlalias*/
{ "ggg", 	0x022D9, 	0x0 }, 	/* alias ISOAMSR Gg : mmlalias*/
{ "ggr", 	0x003B3, 	0x0 }, 	/* =small gamma, Greek : 9573-2003-isogrk1*/
{ "gimel", 	0x02137, 	0x0 }, 	/* /gimel - gimel, Hebrew : 9573-2003-isoamso*/
{ "gjcy", 	0x00453, 	0x0 }, 	/* =small gje, Macedonian : 9573-2003-isocyr2*/
{ "gl", 	0x02277, 	0x0 }, 	/* /gtrless R: greater, less : 9573-2003-isoamsr*/
{ "glE", 	0x02A92, 	0x0 }, 	/* greater, less, equal : 9573-2003-isoamsr*/
{ "gla", 	0x02AA5, 	0x0 }, 	/* greater, less, apart : 9573-2003-isoamsr*/
{ "glj", 	0x02AA4, 	0x0 }, 	/* greater, less, overlapping : 9573-2003-isoamsr*/
{ "gnE", 	0x02269, 	0x0 }, 	/* /gneqq N: greater, not dbl equals : 9573-2003-isoamsn*/
{ "gnap", 	0x02A8A, 	0x0 }, 	/* /gnapprox N: greater, not approximate : 9573-2003-isoamsn*/
{ "gnapprox", 	0x02A8A, 	0x0 }, 	/* alias ISOAMSN gnap : mmlalias*/
{ "gne", 	0x02A88, 	0x0 }, 	/*  : STIX*/
{ "gneq", 	0x02A88, 	0x0 }, 	/* alias ISOAMSN gne : mmlalias*/
{ "gneqq", 	0x02269, 	0x0 }, 	/* alias ISOAMSN gnE : mmlalias*/
{ "gnsim", 	0x022E7, 	0x0 }, 	/* /gnsim N: greater, not similar : 9573-2003-isoamsn*/
{ "gopf", 	0x1D558, 	0x0 }, 	/*  : mmlextra*/
{ "grave", 	0x00060, 	0x0 }, 	/* =grave accent : 9573-2003-isodia*/
{ "gscr", 	0x0210A, 	0x0 }, 	/* /scr g, script letter g : 9573-2003-isomscr*/
{ "gsdot", 	0x022D7, 	0x0 }, 	/* /gtrdot R: greater than, single dot : 8879-isoamsr*/
{ "gsim", 	0x02273, 	0x0 }, 	/* /gtrsim R: greater, similar : 9573-2003-isoamsr*/
{ "gsime", 	0x02A8E, 	0x0 }, 	/* greater, similar, equal : 9573-2003-isoamsr*/
{ "gsiml", 	0x02A90, 	0x0 }, 	/* greater, similar, less : 9573-2003-isoamsr*/
{ "gt", 	0x0003E, 	0x0 }, 	/* =greater-than sign R: : 9573-2003-isonum*/
{ "gtcc", 	0x02AA7, 	0x0 }, 	/* greater than, closed by curve : 9573-2003-isoamsr*/
{ "gtcir", 	0x02A7A, 	0x0 }, 	/* greater than, circle inside : 9573-2003-isoamsr*/
{ "gtdot", 	0x022D7, 	0x0 }, 	/* /gtrdot R: greater than, with dot : 9573-2003-isoamsr*/
{ "gtlPar", 	0x02995, 	0x0 }, 	/* dbl left parenthesis, greater : 9573-2003-isoamsc*/
{ "gtquest", 	0x02A7C, 	0x0 }, 	/* greater than, questionmark above : 9573-2003-isoamsr*/
{ "gtrapprox", 	0x02A86, 	0x0 }, 	/* alias ISOAMSR gap : mmlalias*/
{ "gtrarr", 	0x02978, 	0x0 }, 	/* greater than, right arrow : 9573-2003-isoamsr*/
{ "gtrdot", 	0x022D7, 	0x0 }, 	/* alias ISOAMSR gtdot : mmlalias*/
{ "gtreqless", 	0x022DB, 	0x0 }, 	/* alias ISOAMSR gel : mmlalias*/
{ "gtreqqless", 	0x02A8C, 	0x0 }, 	/* alias ISOAMSR gEl : mmlalias*/
{ "gtrless", 	0x02277, 	0x0 }, 	/* alias ISOAMSR gl : mmlalias*/
{ "gtrpar", 	0x029A0, 	0x0 }, 	/*  : STIX*/
{ "gtrsim", 	0x02273, 	0x0 }, 	/* alias ISOAMSR gsim : mmlalias*/
{ "gvertneqq", 	0x02269, 	0x0FE00 }, 	/* alias ISOAMSN gvnE : mmlalias*/
{ "gvnE", 	0x02269, 	0x0FE00 }, 	/* /gvertneqq N: gt, vert, not dbl eq : 9573-2003-isoamsn*/
{ "hArr", 	0x021D4, 	0x0 }, 	/* /Leftrightarrow A: l&r dbl arrow : 9573-2003-isoamsa*/
{ "hairsp", 	0x0200A, 	0x0 }, 	/* =hair space : 9573-2003-isopub*/
{ "half", 	0x000BD, 	0x0 }, 	/* =fraction one-half : 9573-2003-isonum*/
{ "hamilt", 	0x0210B, 	0x0 }, 	/* Hamiltonian (script capital H)  : 8879-isotech*/
{ "hardcy", 	0x0044A, 	0x0 }, 	/* =small hard sign, Cyrillic : 9573-2003-isocyr1*/
{ "harr", 	0x02194, 	0x0 }, 	/* /leftrightarrow A: l&r arrow : 9573-2003-isoamsa*/
{ "harrcir", 	0x02948, 	0x0 }, 	/* left and right arrow with a circle : 9573-2003-isoamsa*/
{ "harrw", 	0x021AD, 	0x0 }, 	/* /leftrightsquigarrow A: l&r arr-wavy : 9573-2003-isoamsa*/
{ "hbar", 	0x0210F, 	0x0 }, 	/* alias ISOAMSO plank : mmlalias*/
{ "hcirc", 	0x00125, 	0x0 }, 	/* =small h, circumflex accent : 9573-2003-isolat2*/
{ "hearts", 	0x02665, 	0x0 }, 	/* black heart suit = valentine : xhtml1-symbol*/
{ "heartsuit", 	0x02665, 	0x0 }, 	/* ISOPUB hearts : mmlalias*/
{ "hellip", 	0x02026, 	0x0 }, 	/* =ellipsis (horizontal) : 9573-2003-isopub*/
{ "hercon", 	0x022B9, 	0x0 }, 	/* hermitian conjugate matrix : 9573-2003-isoamsb*/
{ "hfr", 	0x1D525, 	0x0 }, 	/* /frak h, lower case h : 9573-2003-isomfrk*/
{ "hksearow", 	0x02925, 	0x0 }, 	/* alias ISOAMSA searhk : mmlalias*/
{ "hkswarow", 	0x02926, 	0x0 }, 	/* alias ISOAMSA swarhk : mmlalias*/
{ "hoarr", 	0x021FF, 	0x0 }, 	/* horizontal open arrow : 9573-2003-isoamsa*/
{ "homtht", 	0x0223B, 	0x0 }, 	/* homothetic : 9573-2003-isoamsr*/
{ "hookleftarrow", 	0x021A9, 	0x0 }, 	/* alias ISOAMSA larrhk : mmlalias*/
{ "hookrightarrow", 	0x021AA, 	0x0 }, 	/* alias ISOAMSA rarrhk : mmlalias*/
{ "hopf", 	0x1D559, 	0x0 }, 	/*  : mmlextra*/
{ "horbar", 	0x02015, 	0x0 }, 	/* =horizontal bar : 9573-2003-isonum*/
{ "hrglass", 	0x029D6, 	0x0 }, 	/*  : STIX*/
{ "hscr", 	0x1D4BD, 	0x0 }, 	/* /scr h, script letter h : 9573-2003-isomscr*/
{ "hslash", 	0x0210F, 	0x0 }, 	/* alias ISOAMSO plankv : mmlalias*/
{ "hstrok", 	0x00127, 	0x0 }, 	/* =small h, stroke : 9573-2003-isolat2*/
{ "htimes", 	0x02A2F, 	0x0 }, 	/*  : STIX*/
{ "hybull", 	0x02043, 	0x0 }, 	/* rectangle, filled (hyphen bullet) : 9573-2003-isopub*/
{ "hyphen", 	0x02010, 	0x0 }, 	/* =hyphen : 9573-2003-isonum*/
{ "iacgr", 	0x003AF, 	0x0 }, 	/* =small iota, accent, Greek : 9573-2003-isogrk2*/
{ "iacute", 	0x000ED, 	0x0 }, 	/* =small i, acute accent : 9573-2003-isolat1*/
{ "ic", 	0x02063, 	0x0 }, 	/* short form of &InvisibleComma; : mmlextra*/
{ "icirc", 	0x000EE, 	0x0 }, 	/* =small i, circumflex accent : 9573-2003-isolat1*/
{ "icy", 	0x00438, 	0x0 }, 	/* =small i, Cyrillic : 9573-2003-isocyr1*/
{ "idiagr", 	0x00390, 	0x0 }, 	/* =small iota, dieresis, accent, Greek : 9573-2003-isogrk2*/
{ "idigr", 	0x003CA, 	0x0 }, 	/* =small iota, dieresis, Greek : 9573-2003-isogrk2*/
{ "iecy", 	0x00435, 	0x0 }, 	/* =small ie, Cyrillic : 9573-2003-isocyr1*/
{ "iexcl", 	0x000A1, 	0x0 }, 	/* =inverted exclamation mark : 9573-2003-isonum*/
{ "iff", 	0x021D4, 	0x0 }, 	/* /iff =if and only if  : 8879-isotech*/
{ "ifr", 	0x1D526, 	0x0 }, 	/* /frak i, lower case i : 9573-2003-isomfrk*/
{ "igr", 	0x003B9, 	0x0 }, 	/* =small iota, Greek : 9573-2003-isogrk1*/
{ "igrave", 	0x000EC, 	0x0 }, 	/* =small i, grave accent : 9573-2003-isolat1*/
{ "ii", 	0x02148, 	0x0 }, 	/* i for use as a square root of -1 : mmlextra*/
{ "iiiint", 	0x02A0C, 	0x0 }, 	/* alias ISOTECH qint : mmlalias*/
{ "iiint", 	0x0222D, 	0x0 }, 	/* alias ISOTECH tint : mmlalias*/
{ "iinfin", 	0x029DC, 	0x0 }, 	/* infinity sign, incomplete : 9573-2003-isotech*/
{ "iiota", 	0x02129, 	0x0 }, 	/* inverted iota : 9573-2003-isoamso*/
{ "ijlig", 	0x00133, 	0x0 }, 	/* =small ij ligature : 9573-2003-isolat2*/
{ "imacr", 	0x0012B, 	0x0 }, 	/* =small i, macron : 9573-2003-isolat2*/
{ "image", 	0x02111, 	0x0 }, 	/* /Im - imaginary   : 9573-2003-isoamso*/
{ "imagline", 	0x02110, 	0x0 }, 	/* the geometric imaginary line : mmlalias*/
{ "imagpart", 	0x02111, 	0x0 }, 	/* alias ISOAMSO image : mmlalias*/
{ "imath", 	0x00131, 	0x0 }, 	/* /imath - small i, no dot : 9573-2003-isoamso*/
{ "imof", 	0x022B7, 	0x0 }, 	/* image of : 9573-2003-isoamsa*/
{ "imped", 	0x001B5, 	0x0 }, 	/* impedance : 9573-2003-isotech*/
{ "in", 	0x02208, 	0x0 }, 	/* ISOTECH   isin  : mmlalias*/
{ "incare", 	0x02105, 	0x0 }, 	/* =in-care-of symbol : 9573-2003-isopub*/
{ "infin", 	0x0221E, 	0x0 }, 	/* /infty infinity : 9573-2003-isotech*/
{ "infintie", 	0x029DD, 	0x0 }, 	/* tie, infinity : 9573-2003-isotech*/
{ "inodot", 	0x00131, 	0x0 }, 	/* /imath =small i, no dot : 8879-isoamso*/
{ "int", 	0x0222B, 	0x0 }, 	/* /int L: integral operator : 9573-2003-isotech*/
{ "intcal", 	0x022BA, 	0x0 }, 	/* /intercal B: intercal : 9573-2003-isoamsb*/
{ "integers", 	0x02124, 	0x0 }, 	/* the ring of integers : mmlalias*/
{ "intercal", 	0x022BA, 	0x0 }, 	/* alias ISOAMSB intcal : mmlalias*/
{ "intlarhk", 	0x02A17, 	0x0 }, 	/* integral, left arrow with hook : 9573-2003-isotech*/
{ "intprod", 	0x02A3C, 	0x0 }, 	/* alias ISOAMSB iprod : mmlalias*/
{ "iocy", 	0x00451, 	0x0 }, 	/* =small io, Russian : 9573-2003-isocyr1*/
{ "iogon", 	0x0012F, 	0x0 }, 	/* =small i, ogonek : 9573-2003-isolat2*/
{ "iopf", 	0x1D55A, 	0x0 }, 	/*  : mmlextra*/
{ "iota", 	0x003B9, 	0x0 }, 	/* /iota small iota, Greek : 9573-2003-isogrk3*/
{ "iprod", 	0x02A3C, 	0x0 }, 	/* /intprod : 9573-2003-isoamsb*/
{ "iprodr", 	0x02A3D, 	0x0 }, 	/*  : STIX*/
{ "iquest", 	0x000BF, 	0x0 }, 	/* =inverted question mark : 9573-2003-isonum*/
{ "iscr", 	0x1D4BE, 	0x0 }, 	/* /scr i, script letter i : 9573-2003-isomscr*/
{ "isin", 	0x02208, 	0x0 }, 	/* element of : xhtml1-symbol*/
{ "isinE", 	0x022F9, 	0x0 }, 	/* set membership, two horizontal strokes : 9573-2003-isotech*/
{ "isindot", 	0x022F5, 	0x0 }, 	/* set membership, dot above : 9573-2003-isotech*/
{ "isins", 	0x022F4, 	0x0 }, 	/* set membership, vertical bar on horizontal stroke : 9573-2003-isotech*/
{ "isinsv", 	0x022F3, 	0x0 }, 	/* large set membership, vertical bar on horizontal stroke : 9573-2003-isotech*/
{ "isinv", 	0x02208, 	0x0 }, 	/* set membership, variant : 9573-2003-isotech*/
{ "isinvb", 	0x022F8, 	0x0 }, 	/*  : STIX*/
{ "it", 	0x02062, 	0x0 }, 	/* marks multiplication when it is understood without a mark : mmlextra*/
{ "itilde", 	0x00129, 	0x0 }, 	/* =small i, tilde : 9573-2003-isolat2*/
{ "iukcy", 	0x00456, 	0x0 }, 	/* =small i, Ukrainian : 9573-2003-isocyr2*/
{ "iuml", 	0x000EF, 	0x0 }, 	/* =small i, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "jcirc", 	0x00135, 	0x0 }, 	/* =small j, circumflex accent : 9573-2003-isolat2*/
{ "jcy", 	0x00439, 	0x0 }, 	/* =small short i, Cyrillic : 9573-2003-isocyr1*/
{ "jfr", 	0x1D527, 	0x0 }, 	/* /frak j, lower case j : 9573-2003-isomfrk*/
{ "jmath", 	0x00237, 	0x0 }, 	/* /jmath - small j, no dot : 9573-2003-isoamso*/
{ "jnodot", 	0x00237, 	0x0 }, 	/* /jmath - small j, no dot  : 8879-isoamso*/
{ "jopf", 	0x1D55B, 	0x0 }, 	/*  : mmlextra*/
{ "jscr", 	0x1D4BF, 	0x0 }, 	/* /scr j, script letter j : 9573-2003-isomscr*/
{ "jsercy", 	0x00458, 	0x0 }, 	/* =small je, Serbian : 9573-2003-isocyr2*/
{ "jukcy", 	0x00454, 	0x0 }, 	/* =small je, Ukrainian : 9573-2003-isocyr2*/
{ "kappa", 	0x003BA, 	0x0 }, 	/* /kappa small kappa, Greek : 9573-2003-isogrk3*/
{ "kappav", 	0x003F0, 	0x0 }, 	/* /varkappa : 9573-2003-isogrk3*/
{ "kcedil", 	0x00137, 	0x0 }, 	/* =small k, cedilla : 9573-2003-isolat2*/
{ "kcy", 	0x0043A, 	0x0 }, 	/* =small ka, Cyrillic : 9573-2003-isocyr1*/
{ "kfr", 	0x1D528, 	0x0 }, 	/* /frak k, lower case k : 9573-2003-isomfrk*/
{ "kgr", 	0x003BA, 	0x0 }, 	/* =small kappa, Greek : 9573-2003-isogrk1*/
{ "kgreen", 	0x00138, 	0x0 }, 	/* =small k, Greenlandic : 9573-2003-isolat2*/
{ "khcy", 	0x00445, 	0x0 }, 	/* =small ha, Cyrillic : 9573-2003-isocyr1*/
{ "khgr", 	0x003C7, 	0x0 }, 	/* =small chi, Greek : 9573-2003-isogrk1*/
{ "kjcy", 	0x0045C, 	0x0 }, 	/* =small kje Macedonian : 9573-2003-isocyr2*/
{ "kopf", 	0x1D55C, 	0x0 }, 	/*  : mmlextra*/
{ "koppa", 	0x003DE, 	0x0 }, 	/* 03DE : STIX*/
{ "kscr", 	0x1D4C0, 	0x0 }, 	/* /scr k, script letter k : 9573-2003-isomscr*/
{ "lAarr", 	0x021DA, 	0x0 }, 	/* /Lleftarrow A: left triple arrow : 9573-2003-isoamsa*/
{ "lArr", 	0x021D0, 	0x0 }, 	/* /Leftarrow A: is implied by : 9573-2003-isotech*/
{ "lAtail", 	0x0291B, 	0x0 }, 	/* left double arrow-tail : 9573-2003-isoamsa*/
{ "lBarr", 	0x0290E, 	0x0 }, 	/* left doubly broken arrow : 9573-2003-isoamsa*/
{ "lE", 	0x02266, 	0x0 }, 	/* /leqq R: less, double equals : 9573-2003-isoamsr*/
{ "lEg", 	0x02A8B, 	0x0 }, 	/*  : STIX*/
{ "lHar", 	0x02962, 	0x0 }, 	/* left harpoon-up over left harpoon-down : 9573-2003-isoamsa*/
{ "lacute", 	0x0013A, 	0x0 }, 	/* =small l, acute accent : 9573-2003-isolat2*/
{ "laemptyv", 	0x029B4, 	0x0 }, 	/* circle, slash, left arrow above : 9573-2003-isoamso*/
{ "lagran", 	0x02112, 	0x0 }, 	/* Lagrangian (script capital L)  : 9573-2003-isotech*/
{ "lambda", 	0x003BB, 	0x0 }, 	/* /lambda small lambda, Greek : 9573-2003-isogrk3*/
{ "lang", 	0x027E8, 	0x0 }, 	/* /langle O: left angle bracket : 9573-2003-isotech*/
{ "langd", 	0x02991, 	0x0 }, 	/* left angle, dot : 9573-2003-isoamsc*/
{ "langle", 	0x027E8, 	0x0 }, 	/* alias ISOTECH lang : mmlalias*/
{ "lap", 	0x02A85, 	0x0 }, 	/* /lessapprox R: less, approximate : 9573-2003-isoamsr*/
{ "laquo", 	0x000AB, 	0x0 }, 	/* =angle quotation mark, left : 9573-2003-isonum*/
{ "larr", 	0x02190, 	0x0 }, 	/* /leftarrow /gets A: =leftward arrow : 9573-2003-isonum*/
{ "larr2", 	0x021C7, 	0x0 }, 	/* /leftleftarrows A: two left arrows  : 8879-isoamsa*/
{ "larrb", 	0x021E4, 	0x0 }, 	/* leftwards arrow to bar : mmlextra*/
{ "larrbfs", 	0x0291F, 	0x0 }, 	/* left arrow-bar, filled square : 9573-2003-isoamsa*/
{ "larrfs", 	0x0291D, 	0x0 }, 	/* left arrow, filled square : 9573-2003-isoamsa*/
{ "larrhk", 	0x021A9, 	0x0 }, 	/* /hookleftarrow A: left arrow-hooked : 9573-2003-isoamsa*/
{ "larrlp", 	0x021AB, 	0x0 }, 	/* /looparrowleft A: left arrow-looped : 9573-2003-isoamsa*/
{ "larrpl", 	0x02939, 	0x0 }, 	/* left arrow, plus : 9573-2003-isoamsa*/
{ "larrpl", 	0x02946, 	0x0 }, 	/*  : STIX*/
{ "larrsim", 	0x02973, 	0x0 }, 	/* left arrow, similar : 9573-2003-isoamsa*/
{ "larrtl", 	0x021A2, 	0x0 }, 	/* /leftarrowtail A: left arrow-tailed : 9573-2003-isoamsa*/
{ "lat", 	0x02AAB, 	0x0 }, 	/* larger than : 9573-2003-isoamsr*/
{ "latail", 	0x02919, 	0x0 }, 	/* left arrow-tail : 9573-2003-isoamsa*/
{ "late", 	0x02AAD, 	0x0 }, 	/* larger than or equal : 9573-2003-isoamsr*/
{ "lates", 	0x02AAD, 	0x0FE00 }, 	/* larger than or equal, slanted : 9573-2003-isoamsr*/
{ "lbarr", 	0x0290C, 	0x0 }, 	/* left broken arrow : 9573-2003-isoamsa*/
{ "lbbrk", 	0x02772, 	0x0 }, 	/* left broken bracket : 9573-2003-isotech*/
{ "lbrace", 	0x0007B, 	0x0 }, 	/* alias ISONUM lcub : mmlalias*/
{ "lbrack", 	0x0005B, 	0x0 }, 	/* alias ISONUM lsqb : mmlalias*/
{ "lbrke", 	0x0298B, 	0x0 }, 	/* left bracket, equal : 9573-2003-isoamsc*/
{ "lbrksld", 	0x0298F, 	0x0 }, 	/* left bracket, solidus bottom corner : 9573-2003-isoamsc*/
{ "lbrkslu", 	0x0298D, 	0x0 }, 	/* left bracket, solidus top corner : 9573-2003-isoamsc*/
{ "lcaron", 	0x0013E, 	0x0 }, 	/* =small l, caron : 9573-2003-isolat2*/
{ "lcedil", 	0x0013C, 	0x0 }, 	/* =small l, cedilla : 9573-2003-isolat2*/
{ "lceil", 	0x02308, 	0x0 }, 	/* /lceil O: left ceiling : 9573-2003-isoamsc*/
{ "lcub", 	0x0007B, 	0x0 }, 	/* /lbrace O: =left curly bracket : 9573-2003-isonum*/
{ "lcy", 	0x0043B, 	0x0 }, 	/* =small el, Cyrillic : 9573-2003-isocyr1*/
{ "ldca", 	0x02936, 	0x0 }, 	/* left down curved arrow : 9573-2003-isoamsa*/
{ "ldharb", 	0x02956, 	0x0 }, 	/*  : STIX*/
{ "ldot", 	0x022D6, 	0x0 }, 	/* /lessdot R: less than, with dot : 8879-isoamsr*/
{ "ldquo", 	0x0201C, 	0x0 }, 	/* =double quotation mark, left : 9573-2003-isonum*/
{ "ldquor", 	0x0201E, 	0x0 }, 	/* =rising dbl quote, left (low) : 9573-2003-isopub*/
{ "ldrdhar", 	0x02967, 	0x0 }, 	/* left harpoon-down over right harpoon-down : 9573-2003-isoamsa*/
{ "ldrdshar", 	0x02950, 	0x0 }, 	/*  : STIX*/
{ "ldrushar", 	0x0294B, 	0x0 }, 	/* left-down-right-up harpoon : 9573-2003-isoamsa*/
{ "ldsh", 	0x021B2, 	0x0 }, 	/* left down angled arrow : 9573-2003-isoamsa*/
{ "le", 	0x02264, 	0x0 }, 	/* /leq /le R: less-than-or-equal : 9573-2003-isotech*/
{ "leftarrow", 	0x02190, 	0x0 }, 	/* alias ISONUM larr : mmlalias*/
{ "leftarrowtail", 	0x021A2, 	0x0 }, 	/* alias ISOAMSA larrtl : mmlalias*/
{ "leftharpoondown", 	0x021BD, 	0x0 }, 	/* alias ISOAMSA lhard : mmlalias*/
{ "leftharpoonup", 	0x021BC, 	0x0 }, 	/* alias ISOAMSA lharu : mmlalias*/
{ "leftleftarrows", 	0x021C7, 	0x0 }, 	/* alias ISOAMSA llarr : mmlalias*/
{ "leftrightarrow", 	0x02194, 	0x0 }, 	/* alias ISOAMSA harr : mmlalias*/
{ "leftrightarrows", 	0x021C6, 	0x0 }, 	/* alias ISOAMSA lrarr : mmlalias*/
{ "leftrightharpoons", 	0x021CB, 	0x0 }, 	/* alias ISOAMSA lrhar : mmlalias*/
{ "leftrightsquigarrow", 	0x021AD, 	0x0 }, 	/* alias ISOAMSA harrw : mmlalias*/
{ "leftthreetimes", 	0x022CB, 	0x0 }, 	/* alias ISOAMSB lthree : mmlalias*/
{ "leg", 	0x022DA, 	0x0 }, 	/* /lesseqgtr R: less, eq, greater : 9573-2003-isoamsr*/
{ "leq", 	0x02264, 	0x0 }, 	/* alias ISOTECH le : mmlalias*/
{ "leqq", 	0x02266, 	0x0 }, 	/* alias ISOAMSR lE : mmlalias*/
{ "leqslant", 	0x02A7D, 	0x0 }, 	/* alias ISOAMSR les : mmlalias*/
{ "les", 	0x02A7D, 	0x0 }, 	/* /leqslant R: less-than-or-eq, slant : 9573-2003-isoamsr*/
{ "lescc", 	0x02AA8, 	0x0 }, 	/* less than, closed by curve, equal, slanted : 9573-2003-isoamsr*/
{ "lesdot", 	0x02A7F, 	0x0 }, 	/* less-than-or-equal, slanted, dot inside : 9573-2003-isoamsr*/
{ "lesdoto", 	0x02A81, 	0x0 }, 	/* less-than-or-equal, slanted, dot above : 9573-2003-isoamsr*/
{ "lesdotor", 	0x02A83, 	0x0 }, 	/* less-than-or-equal, slanted, dot above right : 9573-2003-isoamsr*/
{ "lesg", 	0x022DA, 	0x0FE00 }, 	/* less, equal, slanted, greater : 9573-2003-isoamsr*/
{ "lesges", 	0x02A93, 	0x0 }, 	/* less, equal, slanted, greater, equal, slanted : 9573-2003-isoamsr*/
{ "lessapprox", 	0x02A85, 	0x0 }, 	/* alias ISOAMSR lap : mmlalias*/
{ "lessdot", 	0x022D6, 	0x0 }, 	/* alias ISOAMSR ltdot : mmlalias*/
{ "lesseqgtr", 	0x022DA, 	0x0 }, 	/* alias ISOAMSR leg : mmlalias*/
{ "lesseqqgtr", 	0x02A8B, 	0x0 }, 	/* alias ISOAMSR lEg : mmlalias*/
{ "lessgtr", 	0x02276, 	0x0 }, 	/* alias ISOAMSR lg : mmlalias*/
{ "lesssim", 	0x02272, 	0x0 }, 	/* alias ISOAMSR lsim : mmlalias*/
{ "lfbowtie", 	0x029D1, 	0x0 }, 	/*  : STIX*/
{ "lfisht", 	0x0297C, 	0x0 }, 	/* left fish tail : 9573-2003-isoamsa*/
{ "lfloor", 	0x0230A, 	0x0 }, 	/* /lfloor O: left floor : 9573-2003-isoamsc*/
{ "lfr", 	0x1D529, 	0x0 }, 	/* /frak l, lower case l : 9573-2003-isomfrk*/
{ "lftimes", 	0x029D4, 	0x0 }, 	/*  : STIX*/
{ "lg", 	0x02276, 	0x0 }, 	/* /lessgtr R: less, greater : 9573-2003-isoamsr*/
{ "lgE", 	0x02A91, 	0x0 }, 	/* less, greater, equal : 9573-2003-isoamsr*/
{ "lgr", 	0x003BB, 	0x0 }, 	/* =small lambda, Greek : 9573-2003-isogrk1*/
{ "lhard", 	0x021BD, 	0x0 }, 	/* /leftharpoondown A: l harpoon-down : 9573-2003-isoamsa*/
{ "lharu", 	0x021BC, 	0x0 }, 	/* /leftharpoonup A: left harpoon-up : 9573-2003-isoamsa*/
{ "lharul", 	0x0296A, 	0x0 }, 	/* left harpoon-up over long dash : 9573-2003-isoamsa*/
{ "lhblk", 	0x02584, 	0x0 }, 	/* =lower half block : 9573-2003-isopub*/
{ "ljcy", 	0x00459, 	0x0 }, 	/* =small lje, Serbian : 9573-2003-isocyr2*/
{ "ll", 	0x0226A, 	0x0 }, 	/* alias ISOAMSR Lt : mmlalias*/
{ "llarr", 	0x021C7, 	0x0 }, 	/* /leftleftarrows A: two left arrows : 9573-2003-isoamsa*/
{ "llcorner", 	0x0231E, 	0x0 }, 	/* alias ISOAMSC dlcorn : mmlalias*/
{ "llhard", 	0x0296B, 	0x0 }, 	/* left harpoon-down below long dash : 9573-2003-isoamsa*/
{ "lltri", 	0x025FA, 	0x0 }, 	/* lower left triangle : 9573-2003-isoamso*/
{ "lltrif", 	0x025E3, 	0x0 }, 	/*  : STIX*/
{ "lmidot", 	0x00140, 	0x0 }, 	/* =small l, middle dot : 9573-2003-isolat2*/
{ "lmoust", 	0x023B0, 	0x0 }, 	/* /lmoustache : 9573-2003-isoamsc*/
{ "lmoustache", 	0x023B0, 	0x0 }, 	/* alias ISOAMSC lmoust : mmlalias*/
{ "lnE", 	0x02268, 	0x0 }, 	/* /lneqq N: less, not double equals : 9573-2003-isoamsn*/
{ "lnap", 	0x02A89, 	0x0 }, 	/* /lnapprox N: less, not approximate : 9573-2003-isoamsn*/
{ "lnapprox", 	0x02A89, 	0x0 }, 	/* alias ISOAMSN lnap : mmlalias*/
{ "lne", 	0x02A87, 	0x0 }, 	/*  : STIX*/
{ "lneq", 	0x02A87, 	0x0 }, 	/* alias ISOAMSN lne : mmlalias*/
{ "lneqq", 	0x02268, 	0x0 }, 	/* alias ISOAMSN lnE : mmlalias*/
{ "lnsim", 	0x022E6, 	0x0 }, 	/* /lnsim N: less, not similar : 9573-2003-isoamsn*/
{ "loang", 	0x027EC, 	0x0 }, 	/* left open angular bracket : 9573-2003-isotech*/
{ "loarr", 	0x021FD, 	0x0 }, 	/* left open arrow : 9573-2003-isoamsa*/
{ "lobrk", 	0x027E6, 	0x0 }, 	/* left open bracket : 9573-2003-isotech*/
{ "locub", 	0x02983, 	0x0 }, 	/*  : STIX*/
{ "longleftarrow", 	0x027F5, 	0x0 }, 	/* alias ISOAMSA xlarr : mmlalias*/
{ "longleftrightarrow", 	0x027F7, 	0x0 }, 	/* alias ISOAMSA xharr : mmlalias*/
{ "longmapsto", 	0x027FC, 	0x0 }, 	/* alias ISOAMSA xmap : mmlalias*/
{ "longrightarrow", 	0x027F6, 	0x0 }, 	/* alias ISOAMSA xrarr : mmlalias*/
{ "looparrowleft", 	0x021AB, 	0x0 }, 	/* alias ISOAMSA larrlp : mmlalias*/
{ "looparrowright", 	0x021AC, 	0x0 }, 	/* alias ISOAMSA rarrlp : mmlalias*/
{ "lopar", 	0x02985, 	0x0 }, 	/* left open parenthesis : 9573-2003-isotech*/
{ "lopf", 	0x1D55D, 	0x0 }, 	/*  : mmlextra*/
{ "loplus", 	0x02A2D, 	0x0 }, 	/* plus sign in left half circle : 9573-2003-isoamsb*/
{ "lotimes", 	0x02A34, 	0x0 }, 	/* multiply sign in left half circle  : 9573-2003-isoamsb*/
{ "lowast", 	0x0204E, 	0x0 }, 	/*  : STIX*/
{ "lowast", 	0x02217, 	0x0 }, 	/* low asterisk : 9573-2003-isotech*/
{ "lowbar", 	0x0005F, 	0x0 }, 	/* =low line : 9573-2003-isonum*/
{ "lowint", 	0x02A1C, 	0x0 }, 	/*  : STIX*/
{ "loz", 	0x025CA, 	0x0 }, 	/* /lozenge - lozenge or total mark : 9573-2003-isopub*/
{ "lozenge", 	0x025CA, 	0x0 }, 	/* alias ISOPUB loz : mmlalias*/
{ "lozf", 	0x029EB, 	0x0 }, 	/* /blacklozenge - lozenge, filled : 9573-2003-isopub*/
{ "lpar", 	0x00028, 	0x0 }, 	/* O: =left parenthesis : 9573-2003-isonum*/
{ "lpargt", 	0x029A0, 	0x0 }, 	/* /leftparengtr O: left parenthesis, gt : 8879-isoamsc*/
{ "lparlt", 	0x02993, 	0x0 }, 	/* O: left parenthesis, lt : 9573-2003-isoamsc*/
{ "lrarr", 	0x021C6, 	0x0 }, 	/* /leftrightarrows A: l arr over r arr : 9573-2003-isoamsa*/
{ "lrarr2", 	0x021C6, 	0x0 }, 	/* /leftrightarrows A: l arr over r arr  : 8879-isoamsa*/
{ "lrcorner", 	0x0231F, 	0x0 }, 	/* alias ISOAMSC drcorn : mmlalias*/
{ "lrhar", 	0x021CB, 	0x0 }, 	/* /leftrightharpoons A: l harp over r : 9573-2003-isoamsa*/
{ "lrhar2", 	0x021CB, 	0x0 }, 	/* /leftrightharpoons A: l harp over r  : 8879-isoamsa*/
{ "lrhard", 	0x0296D, 	0x0 }, 	/* right harpoon-down below long dash : 9573-2003-isoamsa*/
{ "lrm", 	0x0200E, 	0x0 }, 	/*  : xhtml1-special*/
{ "lrtri", 	0x022BF, 	0x0 }, 	/* lower right triangle : 9573-2003-isoamso*/
{ "lsaquo", 	0x02039, 	0x0 }, 	/*  : xhtml1-special*/
{ "lscr", 	0x1D4C1, 	0x0 }, 	/* /scr l, script letter l : 9573-2003-isomscr*/
{ "lsh", 	0x021B0, 	0x0 }, 	/* /Lsh A: : 9573-2003-isoamsa*/
{ "lsim", 	0x02272, 	0x0 }, 	/* /lesssim R: less, similar : 9573-2003-isoamsr*/
{ "lsime", 	0x02A8D, 	0x0 }, 	/* less, similar, equal : 9573-2003-isoamsr*/
{ "lsimg", 	0x02A8F, 	0x0 }, 	/* less, similar, greater : 9573-2003-isoamsr*/
{ "lsqb", 	0x0005B, 	0x0 }, 	/* /lbrack O: =left square bracket : 9573-2003-isonum*/
{ "lsquo", 	0x02018, 	0x0 }, 	/* =single quotation mark, left : 9573-2003-isonum*/
{ "lsquor", 	0x0201A, 	0x0 }, 	/* =rising single quote, left (low) : 9573-2003-isopub*/
{ "lstrok", 	0x00142, 	0x0 }, 	/* =small l, stroke : 9573-2003-isolat2*/
{ "lt", 	0x0003C, 	0x0 }, 	/* =less-than sign R: : 9573-2003-isonum*/
{ "ltcc", 	0x02AA6, 	0x0 }, 	/* less than, closed by curve : 9573-2003-isoamsr*/
{ "ltcir", 	0x02A79, 	0x0 }, 	/* less than, circle inside : 9573-2003-isoamsr*/
{ "ltdot", 	0x022D6, 	0x0 }, 	/* /lessdot R: less than, with dot : 9573-2003-isoamsr*/
{ "lthree", 	0x022CB, 	0x0 }, 	/* /leftthreetimes B: : 9573-2003-isoamsb*/
{ "ltimes", 	0x022C9, 	0x0 }, 	/* /ltimes B: times sign, left closed : 9573-2003-isoamsb*/
{ "ltlarr", 	0x02976, 	0x0 }, 	/* less than, left arrow : 9573-2003-isoamsr*/
{ "ltquest", 	0x02A7B, 	0x0 }, 	/* less than, questionmark above : 9573-2003-isoamsr*/
{ "ltrPar", 	0x02996, 	0x0 }, 	/* dbl right parenthesis, less : 9573-2003-isoamsc*/
{ "ltri", 	0x025C3, 	0x0 }, 	/* /triangleleft B: l triangle, open : 9573-2003-isopub*/
{ "ltrie", 	0x022B4, 	0x0 }, 	/* /trianglelefteq R: left triangle, eq : 9573-2003-isoamsr*/
{ "ltrif", 	0x025C2, 	0x0 }, 	/* /blacktriangleleft R: =l tri, filled : 9573-2003-isopub*/
{ "ltrivb", 	0x029CF, 	0x0 }, 	/*  : STIX*/
{ "luharb", 	0x02952, 	0x0 }, 	/*  : STIX*/
{ "lurdshar", 	0x0294A, 	0x0 }, 	/* left-up-right-down harpoon : 9573-2003-isoamsa*/
{ "luruhar", 	0x02966, 	0x0 }, 	/* left harpoon-up over right harpoon-up : 9573-2003-isoamsa*/
{ "lurushar", 	0x0294E, 	0x0 }, 	/*  : STIX*/
{ "lvertneqq", 	0x02268, 	0x0FE00 }, 	/* alias ISOAMSN lvnE : mmlalias*/
{ "lvnE", 	0x02268, 	0x0FE00 }, 	/* /lvertneqq N: less, vert, not dbl eq : 9573-2003-isoamsn*/
{ "mDDot", 	0x0223A, 	0x0 }, 	/* minus with four dots, geometric properties : 9573-2003-isoamsr*/
{ "macr", 	0x000AF, 	0x0 }, 	/* =macron : 9573-2003-isodia*/
{ "male", 	0x02642, 	0x0 }, 	/* =male symbol : 9573-2003-isopub*/
{ "malt", 	0x02720, 	0x0 }, 	/* /maltese =maltese cross : 9573-2003-isopub*/
{ "maltese", 	0x02720, 	0x0 }, 	/* alias ISOPUB malt : mmlalias*/
{ "map", 	0x021A6, 	0x0 }, 	/* /mapsto A: : 9573-2003-isoamsa*/
{ "mapsto", 	0x021A6, 	0x0 }, 	/* alias ISOAMSA map : mmlalias*/
{ "mapstodown", 	0x021A7, 	0x0 }, 	/* downwards arrow from bar : mmlextra*/
{ "mapstoleft", 	0x021A4, 	0x0 }, 	/* leftwards arrow from bar : mmlextra*/
{ "mapstoup", 	0x021A5, 	0x0 }, 	/* upwards arrow from bar : mmlextra*/
{ "marker", 	0x025AE, 	0x0 }, 	/* =histogram marker : 9573-2003-isopub*/
{ "mcomma", 	0x02A29, 	0x0 }, 	/* minus, comma above : 9573-2003-isoamsr*/
{ "mcy", 	0x0043C, 	0x0 }, 	/* =small em, Cyrillic : 9573-2003-isocyr1*/
{ "mdash", 	0x02014, 	0x0 }, 	/* em dash : xhtml1-special*/
{ "measuredangle", 	0x02221, 	0x0 }, 	/* alias ISOAMSO angmsd : mmlalias*/
{ "mfr", 	0x1D52A, 	0x0 }, 	/* /frak m, lower case m : 9573-2003-isomfrk*/
{ "mgr", 	0x003BC, 	0x0 }, 	/* =small mu, Greek : 9573-2003-isogrk1*/
{ "mho", 	0x02127, 	0x0 }, 	/* /mho - conductance : 9573-2003-isoamso*/
{ "micro", 	0x000B5, 	0x0 }, 	/* =micro sign : 9573-2003-isonum*/
{ "mid", 	0x02223, 	0x0 }, 	/* /mid R: : 9573-2003-isoamsr*/
{ "midast", 	0x0002A, 	0x0 }, 	/* /ast B: asterisk : 9573-2003-isoamsb*/
{ "midcir", 	0x02AF0, 	0x0 }, 	/*  : STIX*/
{ "middot", 	0x000B7, 	0x0 }, 	/* /centerdot B: =middle dot : 9573-2003-isonum*/
{ "minus", 	0x02212, 	0x0 }, 	/* B: minus sign : 9573-2003-isotech*/
{ "minusb", 	0x0229F, 	0x0 }, 	/* /boxminus B: minus sign in box : 9573-2003-isoamsb*/
{ "minusd", 	0x02238, 	0x0 }, 	/* /dotminus B: minus sign, dot above : 9573-2003-isoamsb*/
{ "minusdu", 	0x02A2A, 	0x0 }, 	/* minus sign, dot below : 9573-2003-isoamsb*/
{ "mlcp", 	0x02ADB, 	0x0 }, 	/* /mlcp : 9573-2003-isoamsr*/
{ "mldr", 	0x02026, 	0x0 }, 	/* em leader : 9573-2003-isopub*/
{ "mnplus", 	0x02213, 	0x0 }, 	/* /mp B: minus-or-plus sign : 9573-2003-isotech*/
{ "models", 	0x022A7, 	0x0 }, 	/* /models R: : 9573-2003-isoamsr*/
{ "mopf", 	0x1D55E, 	0x0 }, 	/*  : mmlextra*/
{ "mp", 	0x02213, 	0x0 }, 	/* alias ISOTECH mnplus : mmlalias*/
{ "mscr", 	0x1D4C2, 	0x0 }, 	/* /scr m, script letter m : 9573-2003-isomscr*/
{ "mstpos", 	0x0223E, 	0x0 }, 	/* most positive : 9573-2003-isoamsr*/
{ "mu", 	0x003BC, 	0x0 }, 	/* /mu small mu, Greek : 9573-2003-isogrk3*/
{ "multimap", 	0x022B8, 	0x0 }, 	/* alias ISOAMSA mumap : mmlalias*/
{ "mumap", 	0x022B8, 	0x0 }, 	/* /multimap A: : 9573-2003-isoamsa*/
{ "nGg", 	0x022D9, 	0x00338 }, 	/* not triple greater than : 9573-2003-isoamsn*/
{ "nGt", 	0x0226B, 	0x020D2 }, 	/* not, vert, much greater than : 9573-2003-isoamsn*/
{ "nGtv", 	0x0226B, 	0x00338 }, 	/* not much greater than, variant : 9573-2003-isoamsn*/
{ "nLeftarrow", 	0x021CD, 	0x0 }, 	/* alias ISOAMSA nlArr : mmlalias*/
{ "nLeftrightarrow", 	0x021CE, 	0x0 }, 	/* alias ISOAMSA nhArr : mmlalias*/
{ "nLl", 	0x022D8, 	0x00338 }, 	/* not triple less than : 9573-2003-isoamsn*/
{ "nLt", 	0x0226A, 	0x020D2 }, 	/* not, vert, much less than : 9573-2003-isoamsn*/
{ "nLtv", 	0x0226A, 	0x00338 }, 	/* not much less than, variant : 9573-2003-isoamsn*/
{ "nRightarrow", 	0x021CF, 	0x0 }, 	/* alias ISOAMSA nrArr : mmlalias*/
{ "nVDash", 	0x022AF, 	0x0 }, 	/* /nVDash N: not dbl vert, dbl dash : 9573-2003-isoamsn*/
{ "nVdash", 	0x022AE, 	0x0 }, 	/* /nVdash N: not dbl vertical, dash : 9573-2003-isoamsn*/
{ "nabla", 	0x02207, 	0x0 }, 	/* /nabla del, Hamilton operator : 9573-2003-isotech*/
{ "nacute", 	0x00144, 	0x0 }, 	/* =small n, acute accent : 9573-2003-isolat2*/
{ "nang", 	0x02220, 	0x020D2 }, 	/* not, vert, angle : 9573-2003-isoamso*/
{ "nap", 	0x02249, 	0x0 }, 	/* /napprox N: not approximate : 9573-2003-isoamsn*/
{ "napE", 	0x02A70, 	0x00338 }, 	/* not approximately equal or equal to : 9573-2003-isoamsn*/
{ "napid", 	0x0224B, 	0x00338 }, 	/* not approximately identical to : 9573-2003-isoamsn*/
{ "napos", 	0x00149, 	0x0 }, 	/* =small n, apostrophe : 9573-2003-isolat2*/
{ "napprox", 	0x02249, 	0x0 }, 	/* alias ISOAMSN nap : mmlalias*/
{ "natur", 	0x0266E, 	0x0 }, 	/* /natural - music natural : 9573-2003-isopub*/
{ "natural", 	0x0266E, 	0x0 }, 	/* alias ISOPUB natur : mmlalias*/
{ "naturals", 	0x02115, 	0x0 }, 	/* the semi-ring of natural numbers : mmlalias*/
{ "nbsp", 	0x000A0, 	0x0 }, 	/* =no break (required) space : 9573-2003-isonum*/
{ "nbump", 	0x0224E, 	0x00338 }, 	/* not bumpy equals : mmlextra*/
{ "nbumpe", 	0x0224F, 	0x00338 }, 	/* not bumpy single equals : mmlextra*/
{ "ncap", 	0x02A43, 	0x0 }, 	/* bar, intersection : 9573-2003-isoamsb*/
{ "ncaron", 	0x00148, 	0x0 }, 	/* =small n, caron : 9573-2003-isolat2*/
{ "ncedil", 	0x00146, 	0x0 }, 	/* =small n, cedilla : 9573-2003-isolat2*/
{ "ncong", 	0x02247, 	0x0 }, 	/* /ncong N: not congruent with : 9573-2003-isoamsn*/
{ "ncongdot", 	0x02A6D, 	0x00338 }, 	/* not congruent, dot : 9573-2003-isoamsn*/
{ "ncup", 	0x02A42, 	0x0 }, 	/* bar, union : 9573-2003-isoamsb*/
{ "ncy", 	0x0043D, 	0x0 }, 	/* =small en, Cyrillic : 9573-2003-isocyr1*/
{ "ndash", 	0x02013, 	0x0 }, 	/* =en dash : 9573-2003-isopub*/
{ "ne", 	0x02260, 	0x0 }, 	/* /ne /neq R: not equal : 9573-2003-isotech*/
{ "neArr", 	0x021D7, 	0x0 }, 	/* NE pointing dbl arrow : 9573-2003-isoamsa*/
{ "nearhk", 	0x02924, 	0x0 }, 	/* NE arrow-hooked : 9573-2003-isoamsa*/
{ "nearr", 	0x02197, 	0x0 }, 	/* /nearrow A: NE pointing arrow : 9573-2003-isoamsa*/
{ "nearrow", 	0x02197, 	0x0 }, 	/* alias ISOAMSA nearr : mmlalias*/
{ "nedot", 	0x02250, 	0x00338 }, 	/* not equal, dot : 9573-2003-isotech*/
{ "neonwarr", 	0x02931, 	0x0 }, 	/*  : STIX*/
{ "neosearr", 	0x0292E, 	0x0 }, 	/*  : STIX*/
{ "nequiv", 	0x02262, 	0x0 }, 	/* /nequiv N: not identical with : 9573-2003-isoamsn*/
{ "nesear", 	0x02928, 	0x0 }, 	/* /toea A: NE & SE arrows : 9573-2003-isoamsa*/
{ "nesim", 	0x02242, 	0x00338 }, 	/* not equal or similar : mmlextra*/
{ "neswsarr", 	0x02922, 	0x0 }, 	/*  : STIX*/
{ "nexist", 	0x02204, 	0x0 }, 	/* /nexists - negated exists : 9573-2003-isoamso*/
{ "nexists", 	0x02204, 	0x0 }, 	/* alias ISOAMSO nexist : mmlalias*/
{ "nfr", 	0x1D52B, 	0x0 }, 	/* /frak n, lower case n : 9573-2003-isomfrk*/
{ "ngE", 	0x02267, 	0x00338 }, 	/* /ngeqq N: not greater, dbl equals : 9573-2003-isoamsn*/
{ "nge", 	0x02271, 	0x0 }, 	/* /ngeq N: not greater-than-or-equal : 9573-2003-isoamsn*/
{ "ngeq", 	0x02271, 	0x0 }, 	/* alias ISOAMSN nge : mmlalias*/
{ "ngeqq", 	0x02267, 	0x00338 }, 	/* alias ISOAMSN ngE : mmlalias*/
{ "ngeqslant", 	0x02A7E, 	0x00338 }, 	/* alias ISOAMSN nges : mmlalias*/
{ "nges", 	0x02A7E, 	0x00338 }, 	/* /ngeqslant N: not gt-or-eq, slanted : 9573-2003-isoamsn*/
{ "ngr", 	0x003BD, 	0x0 }, 	/* =small nu, Greek : 9573-2003-isogrk1*/
{ "ngsim", 	0x02275, 	0x0 }, 	/* not greater, similar : 9573-2003-isoamsn*/
{ "ngt", 	0x0226F, 	0x0 }, 	/* /ngtr N: not greater-than : 9573-2003-isoamsn*/
{ "ngtr", 	0x0226F, 	0x0 }, 	/* alias ISOAMSN ngt : mmlalias*/
{ "nhArr", 	0x021CE, 	0x0 }, 	/* /nLeftrightarrow A: not l&r dbl arr : 9573-2003-isoamsa*/
{ "nharr", 	0x021AE, 	0x0 }, 	/* /nleftrightarrow A: not l&r arrow : 9573-2003-isoamsa*/
{ "nhpar", 	0x02AF2, 	0x0 }, 	/* not, horizontal, parallel : 9573-2003-isotech*/
{ "ni", 	0x0220B, 	0x0 }, 	/* /ni /owns R: =contains : 8879-isotech*/
{ "nis", 	0x022FC, 	0x0 }, 	/* contains, vertical bar on horizontal stroke : 9573-2003-isotech*/
{ "nisd", 	0x022FA, 	0x0 }, 	/* contains, long horizontal stroke : 9573-2003-isotech*/
{ "niv", 	0x0220B, 	0x0 }, 	/* contains, variant : 9573-2003-isotech*/
{ "njcy", 	0x0045A, 	0x0 }, 	/* =small nje, Serbian : 9573-2003-isocyr2*/
{ "nlArr", 	0x021CD, 	0x0 }, 	/* /nLeftarrow A: not implied by : 9573-2003-isoamsa*/
{ "nlE", 	0x02266, 	0x00338 }, 	/* /nleqq N: not less, dbl equals : 9573-2003-isoamsn*/
{ "nlarr", 	0x0219A, 	0x0 }, 	/* /nleftarrow A: not left arrow : 9573-2003-isoamsa*/
{ "nldr", 	0x02025, 	0x0 }, 	/* =double baseline dot (en leader) : 9573-2003-isopub*/
{ "nle", 	0x02270, 	0x0 }, 	/* /nleq N: not less-than-or-equal : 9573-2003-isoamsn*/
{ "nleftarrow", 	0x0219A, 	0x0 }, 	/* alias ISOAMSA nlarr : mmlalias*/
{ "nleftrightarrow", 	0x021AE, 	0x0 }, 	/* alias ISOAMSA nharr : mmlalias*/
{ "nleq", 	0x02270, 	0x0 }, 	/* alias ISOAMSN nle : mmlalias*/
{ "nleqq", 	0x02266, 	0x00338 }, 	/* alias ISOAMSN nlE : mmlalias*/
{ "nleqslant", 	0x02A7D, 	0x00338 }, 	/* alias ISOAMSN nles : mmlalias*/
{ "nles", 	0x02A7D, 	0x00338 }, 	/* /nleqslant N: not less-or-eq, slant : 9573-2003-isoamsn*/
{ "nless", 	0x0226E, 	0x0 }, 	/* alias ISOAMSN nlt : mmlalias*/
{ "nlsim", 	0x02274, 	0x0 }, 	/* not less, similar : 9573-2003-isoamsn*/
{ "nlt", 	0x0226E, 	0x0 }, 	/* /nless N: not less-than : 9573-2003-isoamsn*/
{ "nltri", 	0x022EA, 	0x0 }, 	/* /ntriangleleft N: not left triangle : 9573-2003-isoamsn*/
{ "nltrie", 	0x022EC, 	0x0 }, 	/* /ntrianglelefteq N: not l tri, eq : 9573-2003-isoamsn*/
{ "nltrivb", 	0x029CF, 	0x00338 }, 	/*  : STIX*/
{ "nmid", 	0x02224, 	0x0 }, 	/* /nmid : 9573-2003-isoamsn*/
{ "nopf", 	0x1D55F, 	0x0 }, 	/*  : mmlextra*/
{ "not", 	0x000AC, 	0x0 }, 	/* /neg /lnot =not sign : 9573-2003-isonum*/
{ "notin", 	0x02209, 	0x0 }, 	/* /notin N: negated set membership : 9573-2003-isotech*/
{ "notinE", 	0x022F9, 	0x00338 }, 	/* negated set membership, two horizontal strokes : 9573-2003-isotech*/
{ "notindot", 	0x022F5, 	0x00338 }, 	/* negated set membership, dot above : 9573-2003-isotech*/
{ "notinva", 	0x02209, 	0x0 }, 	/* negated set membership, variant : 9573-2003-isotech*/
{ "notinvb", 	0x022F7, 	0x0 }, 	/* negated set membership, variant : 9573-2003-isotech*/
{ "notinvc", 	0x022F6, 	0x0 }, 	/* negated set membership, variant : 9573-2003-isotech*/
{ "notni", 	0x0220C, 	0x0 }, 	/* negated contains : 9573-2003-isotech*/
{ "notniva", 	0x0220C, 	0x0 }, 	/* negated contains, variant : 9573-2003-isotech*/
{ "notnivb", 	0x022FE, 	0x0 }, 	/* contains, variant : 9573-2003-isotech*/
{ "notnivc", 	0x022FD, 	0x0 }, 	/* contains, variant : 9573-2003-isotech*/
{ "npar", 	0x02226, 	0x0 }, 	/* /nparallel N: not parallel : 9573-2003-isoamsn*/
{ "nparallel", 	0x02226, 	0x0 }, 	/* alias ISOAMSN npar : mmlalias*/
{ "nparsl", 	0x02AFD, 	0x020E5 }, 	/* not parallel, slanted : 9573-2003-isotech*/
{ "npart", 	0x02202, 	0x00338 }, 	/* not partial differential : 9573-2003-isotech*/
{ "npolint", 	0x02A14, 	0x0 }, 	/* line integration, not including the pole : 9573-2003-isotech*/
{ "npr", 	0x02280, 	0x0 }, 	/* /nprec N: not precedes : 9573-2003-isoamsn*/
{ "nprcue", 	0x022E0, 	0x0 }, 	/* not curly precedes, eq : 9573-2003-isoamsn*/
{ "npre", 	0x02AAF, 	0x00338 }, 	/* /npreceq N: not precedes, equals : 9573-2003-isoamsn*/
{ "nprec", 	0x02280, 	0x0 }, 	/* alias ISOAMSN npr : mmlalias*/
{ "npreceq", 	0x02AAF, 	0x00338 }, 	/* alias ISOAMSN npre : mmlalias*/
{ "nprsim", 	0x0227E, 	0x00338 }, 	/*  : STIX*/
{ "nrArr", 	0x021CF, 	0x0 }, 	/* /nRightarrow A: not implies : 9573-2003-isoamsa*/
{ "nrarr", 	0x0219B, 	0x0 }, 	/* /nrightarrow A: not right arrow : 9573-2003-isoamsa*/
{ "nrarrc", 	0x02933, 	0x00338 }, 	/* not right arrow-curved : 9573-2003-isoamsa*/
{ "nrarrw", 	0x0219D, 	0x00338 }, 	/* not right arrow-wavy : 9573-2003-isoamsa*/
{ "nrightarrow", 	0x0219B, 	0x0 }, 	/* alias ISOAMSA nrarr : mmlalias*/
{ "nrtri", 	0x022EB, 	0x0 }, 	/* /ntriangleright N: not rt triangle : 9573-2003-isoamsn*/
{ "nrtrie", 	0x022ED, 	0x0 }, 	/* /ntrianglerighteq N: not r tri, eq : 9573-2003-isoamsn*/
{ "nsGt", 	0x02AA2, 	0x00338 }, 	/*  : STIX*/
{ "nsLt", 	0x02AA1, 	0x00338 }, 	/*  : STIX*/
{ "nsc", 	0x02281, 	0x0 }, 	/* /nsucc N: not succeeds : 9573-2003-isoamsn*/
{ "nsccue", 	0x022E1, 	0x0 }, 	/* not succeeds, curly eq : 9573-2003-isoamsn*/
{ "nsce", 	0x02AB0, 	0x00338 }, 	/* /nsucceq N: not succeeds, equals : 9573-2003-isoamsn*/
{ "nscr", 	0x1D4C3, 	0x0 }, 	/* /scr n, script letter n : 9573-2003-isomscr*/
{ "nscsim", 	0x0227F, 	0x00338 }, 	/*  : STIX*/
{ "nshortmid", 	0x02224, 	0x0 }, 	/* alias ISOAMSN nsmid : mmlalias*/
{ "nshortparallel", 	0x02226, 	0x0 }, 	/* alias ISOAMSN nspar : mmlalias*/
{ "nsim", 	0x02241, 	0x0 }, 	/* /nsim N: not similar : 9573-2003-isoamsn*/
{ "nsime", 	0x02244, 	0x0 }, 	/* /nsimeq N: not similar, equals : 9573-2003-isoamsn*/
{ "nsimeq", 	0x02244, 	0x0 }, 	/* alias ISOAMSN nsime : mmlalias*/
{ "nsmid", 	0x02224, 	0x0 }, 	/* /nshortmid : 9573-2003-isoamsn*/
{ "nspar", 	0x02226, 	0x0 }, 	/* /nshortparallel N: not short par : 9573-2003-isoamsn*/
{ "nsqsub", 	0x0228F, 	0x00338 }, 	/*  : STIX*/
{ "nsqsube", 	0x022E2, 	0x0 }, 	/* not, square subset, equals : 9573-2003-isoamsn*/
{ "nsqsup", 	0x02290, 	0x00338 }, 	/*  : STIX*/
{ "nsqsupe", 	0x022E3, 	0x0 }, 	/* not, square superset, equals : 9573-2003-isoamsn*/
{ "nsub", 	0x02284, 	0x0 }, 	/* not subset : 9573-2003-isoamsn*/
{ "nsubE", 	0x02AC5, 	0x00338 }, 	/*  : STIX*/
{ "nsube", 	0x02288, 	0x0 }, 	/* /nsubseteq N: not subset, equals : 9573-2003-isoamsn*/
{ "nsubset", 	0x02282, 	0x020D2 }, 	/* alias ISOAMSN vnsub : mmlalias*/
{ "nsubseteq", 	0x02288, 	0x0 }, 	/* alias ISOAMSN nsube : mmlalias*/
{ "nsubseteqq", 	0x02AC5, 	0x00338 }, 	/* alias ISOAMSN nsubE : mmlalias*/
{ "nsucc", 	0x02281, 	0x0 }, 	/* alias ISOAMSN nsc : mmlalias*/
{ "nsucceq", 	0x02AB0, 	0x00338 }, 	/* alias ISOAMSN nsce : mmlalias*/
{ "nsup", 	0x02285, 	0x0 }, 	/* not superset : 9573-2003-isoamsn*/
{ "nsupE", 	0x02AC6, 	0x00338 }, 	/* /nsupseteqq N: not superset, dbl eq : 9573-2003-isoamsn*/
{ "nsupe", 	0x02289, 	0x0 }, 	/* /nsupseteq N: not superset, equals : 9573-2003-isoamsn*/
{ "nsupset", 	0x02283, 	0x020D2 }, 	/* alias ISOAMSN vnsup : mmlalias*/
{ "nsupseteq", 	0x02289, 	0x0 }, 	/* alias ISOAMSN nsupe : mmlalias*/
{ "nsupseteqq", 	0x02AC6, 	0x00338 }, 	/* alias ISOAMSN nsupE : mmlalias*/
{ "ntgl", 	0x02279, 	0x0 }, 	/* not greater, less : 9573-2003-isoamsn*/
{ "ntilde", 	0x000F1, 	0x0 }, 	/* =small n, tilde : 9573-2003-isolat1*/
{ "ntlg", 	0x02278, 	0x0 }, 	/* not less, greater : 9573-2003-isoamsn*/
{ "ntriangleleft", 	0x022EA, 	0x0 }, 	/* alias ISOAMSN nltri : mmlalias*/
{ "ntrianglelefteq", 	0x022EC, 	0x0 }, 	/* alias ISOAMSN nltrie : mmlalias*/
{ "ntriangleright", 	0x022EB, 	0x0 }, 	/* alias ISOAMSN nrtri : mmlalias*/
{ "ntrianglerighteq", 	0x022ED, 	0x0 }, 	/* alias ISOAMSN nrtrie : mmlalias*/
{ "nu", 	0x003BD, 	0x0 }, 	/* /nu small nu, Greek : 9573-2003-isogrk3*/
{ "num", 	0x00023, 	0x0 }, 	/* =number sign : 9573-2003-isonum*/
{ "numero", 	0x02116, 	0x0 }, 	/* =numero sign : 9573-2003-isocyr1*/
{ "numsp", 	0x02007, 	0x0 }, 	/* =digit space (width of a number) : 9573-2003-isopub*/
{ "nvDash", 	0x022AD, 	0x0 }, 	/* /nvDash N: not vertical, dbl dash : 9573-2003-isoamsn*/
{ "nvHarr", 	0x02904, 	0x0 }, 	/* not, vert, left and right double arrow  : 9573-2003-isoamsa*/
{ "nvap", 	0x0224D, 	0x020D2 }, 	/* not, vert, approximate : 9573-2003-isoamsn*/
{ "nvbrtri", 	0x029D0, 	0x00338 }, 	/*  : STIX*/
{ "nvdash", 	0x022AC, 	0x0 }, 	/* /nvdash N: not vertical, dash : 9573-2003-isoamsn*/
{ "nvge", 	0x02265, 	0x020D2 }, 	/* not, vert, greater-than-or-equal : 9573-2003-isoamsn*/
{ "nvgt", 	0x0003E, 	0x020D2 }, 	/* not, vert, greater-than : 9573-2003-isoamsn*/
{ "nvinfin", 	0x029DE, 	0x0 }, 	/* not, vert, infinity : 9573-2003-isotech*/
{ "nvlArr", 	0x02902, 	0x0 }, 	/* not, vert, left double arrow : 9573-2003-isoamsa*/
{ "nvle", 	0x02264, 	0x020D2 }, 	/* not, vert, less-than-or-equal : 9573-2003-isoamsn*/
{ "nvlt", 	0x0003C, 	0x020D2 }, 	/* not, vert, less-than : 9573-2003-isoamsn*/
{ "nvltrie", 	0x022B4, 	0x020D2 }, 	/* not, vert, left triangle, equals : 9573-2003-isoamsn*/
{ "nvrArr", 	0x02903, 	0x0 }, 	/* not, vert, right double arrow : 9573-2003-isoamsa*/
{ "nvrtrie", 	0x022B5, 	0x020D2 }, 	/* not, vert, right triangle, equals : 9573-2003-isoamsn*/
{ "nvsim", 	0x0223C, 	0x020D2 }, 	/* not, vert, similar : 9573-2003-isoamsn*/
{ "nwArr", 	0x021D6, 	0x0 }, 	/* NW pointing dbl arrow : 9573-2003-isoamsa*/
{ "nwarhk", 	0x02923, 	0x0 }, 	/* NW arrow-hooked : 9573-2003-isoamsa*/
{ "nwarr", 	0x02196, 	0x0 }, 	/* /nwarrow A: NW pointing arrow : 9573-2003-isoamsa*/
{ "nwarrow", 	0x02196, 	0x0 }, 	/* alias ISOAMSA nwarr : mmlalias*/
{ "nwnear", 	0x02927, 	0x0 }, 	/* NW & NE arrows : 9573-2003-isoamsa*/
{ "nwonearr", 	0x02932, 	0x0 }, 	/*  : STIX*/
{ "nwsesarr", 	0x02921, 	0x0 }, 	/*  : STIX*/
{ "oS", 	0x024C8, 	0x0 }, 	/* /circledS - capital S in circle : 9573-2003-isoamso*/
{ "oacgr", 	0x003CC, 	0x0 }, 	/* =small omicron, accent, Greek : 9573-2003-isogrk2*/
{ "oacute", 	0x000F3, 	0x0 }, 	/* =small o, acute accent : 9573-2003-isolat1*/
{ "oast", 	0x0229B, 	0x0 }, 	/* /circledast B: asterisk in circle : 9573-2003-isoamsb*/
{ "obsol", 	0x029B8, 	0x0 }, 	/*  : STIX*/
{ "ocir", 	0x0229A, 	0x0 }, 	/* /circledcirc B: small circle in circle : 9573-2003-isoamsb*/
{ "ocirc", 	0x000F4, 	0x0 }, 	/* =small o, circumflex accent : 9573-2003-isolat1*/
{ "ocy", 	0x0043E, 	0x0 }, 	/* =small o, Cyrillic : 9573-2003-isocyr1*/
{ "odash", 	0x0229D, 	0x0 }, 	/* /circleddash B: hyphen in circle : 9573-2003-isoamsb*/
{ "odblac", 	0x00151, 	0x0 }, 	/* =small o, double acute accent : 9573-2003-isolat2*/
{ "odiv", 	0x02A38, 	0x0 }, 	/* divide in circle : 9573-2003-isoamsb*/
{ "odot", 	0x02299, 	0x0 }, 	/* /odot B: middle dot in circle : 9573-2003-isoamsb*/
{ "odsold", 	0x029BC, 	0x0 }, 	/* dot, solidus, dot in circle : 9573-2003-isoamsb*/
{ "oelig", 	0x00153, 	0x0 }, 	/* =small oe ligature : 9573-2003-isolat2*/
{ "ofcir", 	0x029BF, 	0x0 }, 	/* filled circle in circle : 9573-2003-isoamsb*/
{ "ofr", 	0x1D52C, 	0x0 }, 	/* /frak o, lower case o : 9573-2003-isomfrk*/
{ "ogon", 	0x002DB, 	0x0 }, 	/* =ogonek : 9573-2003-isodia*/
{ "ogr", 	0x003BF, 	0x0 }, 	/* =small omicron, Greek : 9573-2003-isogrk1*/
{ "ograve", 	0x000F2, 	0x0 }, 	/* =small o, grave accent : 9573-2003-isolat1*/
{ "ogt", 	0x029C1, 	0x0 }, 	/* greater-than in circle : 9573-2003-isoamsb*/
{ "ohacgr", 	0x003CE, 	0x0 }, 	/* =small omega, accent, Greek : 9573-2003-isogrk2*/
{ "ohbar", 	0x029B5, 	0x0 }, 	/* circle with horizontal bar : 9573-2003-isoamsb*/
{ "ohgr", 	0x003C9, 	0x0 }, 	/* =small omega, Greek : 9573-2003-isogrk1*/
{ "ohm", 	0x003A9, 	0x0 }, 	/* =ohm sign : 9573-2003-isonum*/
{ "oint", 	0x0222E, 	0x0 }, 	/* alias ISOTECH conint : mmlalias*/
{ "olarr", 	0x021BA, 	0x0 }, 	/* /circlearrowleft A: l arr in circle : 9573-2003-isoamsa*/
{ "olarr", 	0x02940, 	0x0 }, 	/* 21BA : STIX*/
{ "olcir", 	0x029BE, 	0x0 }, 	/* large circle in circle : 9573-2003-isoamsb*/
{ "olcross", 	0x029BB, 	0x0 }, 	/* circle, cross : 9573-2003-isotech*/
{ "oline", 	0x0203E, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "olt", 	0x029C0, 	0x0 }, 	/* less-than in circle : 9573-2003-isoamsb*/
{ "omacr", 	0x0014D, 	0x0 }, 	/* =small o, macron : 9573-2003-isolat2*/
{ "omega", 	0x003C9, 	0x0 }, 	/* /omega small omega, Greek : 9573-2003-isogrk3*/
{ "omicron", 	0x003BF, 	0x0 }, 	/* greek small letter omicron : xhtml1-symbol*/
{ "omid", 	0x029B6, 	0x0 }, 	/* vertical bar in circle : 9573-2003-isoamsb*/
{ "ominus", 	0x02296, 	0x0 }, 	/* /ominus B: minus sign in circle : 9573-2003-isoamsb*/
{ "oopf", 	0x1D560, 	0x0 }, 	/*  : mmlextra*/
{ "opar", 	0x029B7, 	0x0 }, 	/* parallel in circle : 9573-2003-isoamsb*/
{ "operp", 	0x029B9, 	0x0 }, 	/* perpendicular in circle : 9573-2003-isoamsb*/
{ "opfgamma", 	0x0213D, 	0x0 }, 	/*  : STIX*/
{ "opfpi", 	0x0213F, 	0x0 }, 	/*  : STIX*/
{ "opfsum", 	0x02140, 	0x0 }, 	/*  : STIX*/
{ "oplus", 	0x02295, 	0x0 }, 	/* /oplus B: plus sign in circle : 9573-2003-isoamsb*/
{ "or", 	0x02228, 	0x0 }, 	/* /vee /lor B: logical or : 9573-2003-isotech*/
{ "orarr", 	0x021BB, 	0x0 }, 	/* /circlearrowright A: r arr in circle : 9573-2003-isoamsa*/
{ "orarr", 	0x02941, 	0x0 }, 	/* 21BB : STIX*/
{ "ord", 	0x02A5D, 	0x0 }, 	/* or, horizontal dash : 9573-2003-isotech*/
{ "order", 	0x02134, 	0x0 }, 	/* order of (script small o)  : 9573-2003-isotech*/
{ "orderof", 	0x02134, 	0x0 }, 	/* alias ISOTECH order : mmlalias*/
{ "ordf", 	0x000AA, 	0x0 }, 	/* =ordinal indicator, feminine : 9573-2003-isonum*/
{ "ordm", 	0x000BA, 	0x0 }, 	/* =ordinal indicator, masculine : 9573-2003-isonum*/
{ "origof", 	0x022B6, 	0x0 }, 	/* original of : 9573-2003-isoamsa*/
{ "oror", 	0x02A56, 	0x0 }, 	/* two logical or : 9573-2003-isotech*/
{ "orslope", 	0x02A57, 	0x0 }, 	/* sloping large or : 9573-2003-isotech*/
{ "orv", 	0x02A5B, 	0x0 }, 	/* or with middle stem : 9573-2003-isotech*/
{ "oscr", 	0x02134, 	0x0 }, 	/* /scr o, script letter o : 9573-2003-isomscr*/
{ "oslash", 	0x000F8, 	0x0 }, 	/* latin small letter o with stroke, = latin small letter o slash, : xhtml1-lat1*/
{ "osol", 	0x02298, 	0x0 }, 	/* /oslash B: solidus in circle : 9573-2003-isoamsb*/
{ "otilde", 	0x000F5, 	0x0 }, 	/* =small o, tilde : 9573-2003-isolat1*/
{ "otimes", 	0x02297, 	0x0 }, 	/* /otimes B: multiply sign in circle : 9573-2003-isoamsb*/
{ "otimesas", 	0x02A36, 	0x0 }, 	/* multiply sign in circle, circumflex accent : 9573-2003-isoamsb*/
{ "ouml", 	0x000F6, 	0x0 }, 	/* =small o, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "ovbar", 	0x0233D, 	0x0 }, 	/* circle with vertical bar : 9573-2003-isoamsb*/
{ "ovrbrk", 	0x023B4, 	0x0 }, 	/*  : STIX*/
{ "ovrcub", 	0x023DE, 	0x0 }, 	/*  : STIX*/
{ "ovrpar", 	0x023DC, 	0x0 }, 	/*  : STIX*/
{ "oxuarr", 	0x029BD, 	0x0 }, 	/*  : STIX*/
{ "par", 	0x02225, 	0x0 }, 	/* /parallel R: parallel : 9573-2003-isotech*/
{ "para", 	0x000B6, 	0x0 }, 	/* =pilcrow (paragraph sign) : 9573-2003-isonum*/
{ "parallel", 	0x02225, 	0x0 }, 	/* alias ISOTECH par : mmlalias*/
{ "parsim", 	0x02AF3, 	0x0 }, 	/* parallel, similar : 9573-2003-isoamsn*/
{ "parsl", 	0x02AFD, 	0x0 }, 	/* parallel, slanted : 9573-2003-isotech*/
{ "part", 	0x02202, 	0x0 }, 	/* /partial partial differential : 9573-2003-isotech*/
{ "pcy", 	0x0043F, 	0x0 }, 	/* =small pe, Cyrillic : 9573-2003-isocyr1*/
{ "percnt", 	0x00025, 	0x0 }, 	/* =percent sign : 9573-2003-isonum*/
{ "period", 	0x0002E, 	0x0 }, 	/* =full stop, period : 9573-2003-isonum*/
{ "permil", 	0x02030, 	0x0 }, 	/* per thousand : 9573-2003-isotech*/
{ "perp", 	0x022A5, 	0x0 }, 	/* /perp R: perpendicular : 9573-2003-isotech*/
{ "pertenk", 	0x02031, 	0x0 }, 	/* per 10 thousand : 9573-2003-isotech*/
{ "pfr", 	0x1D52D, 	0x0 }, 	/* /frak p, lower case p : 9573-2003-isomfrk*/
{ "pgr", 	0x003C0, 	0x0 }, 	/* =small pi, Greek : 9573-2003-isogrk1*/
{ "phgr", 	0x003C6, 	0x0 }, 	/* =small phi, Greek : 9573-2003-isogrk1*/
{ "phi", 	0x003C6, 	0x0 }, 	/* greek small letter phi : xhtml1-symbol*/
{ "phis", 	0x003D5, 	0x0 }, 	/* /straightphi - straight phi : 8879-isogrk3*/
{ "phiv", 	0x003D5, 	0x0 }, 	/* /varphi -  straight phi : 9573-2003-isogrk3*/
{ "phmmat", 	0x02133, 	0x0 }, 	/* physics M-matrix (script capital M)  : 9573-2003-isotech*/
{ "phone", 	0x0260E, 	0x0 }, 	/* =telephone symbol  : 9573-2003-isopub*/
{ "pi", 	0x003C0, 	0x0 }, 	/* /pi small pi, Greek : 9573-2003-isogrk3*/
{ "pitchfork", 	0x022D4, 	0x0 }, 	/* alias ISOAMSR fork : mmlalias*/
{ "piv", 	0x003D6, 	0x0 }, 	/* /varpi : 9573-2003-isogrk3*/
{ "planck", 	0x0210F, 	0x0 }, 	/* /hbar - Planck's over 2pi : 9573-2003-isoamso*/
{ "planckh", 	0x0210E, 	0x0 }, 	/*  : mmlextra*/
{ "plankv", 	0x0210F, 	0x0 }, 	/* /hslash - variant Planck's over 2pi : 9573-2003-isoamso*/
{ "plus", 	0x0002B, 	0x0 }, 	/* =plus sign B: : 9573-2003-isonum*/
{ "plusacir", 	0x02A23, 	0x0 }, 	/* plus, circumflex accent above : 9573-2003-isoamsb*/
{ "plusb", 	0x0229E, 	0x0 }, 	/* /boxplus B: plus sign in box : 9573-2003-isoamsb*/
{ "pluscir", 	0x02A22, 	0x0 }, 	/* plus, small circle above : 9573-2003-isoamsb*/
{ "plusdo", 	0x02214, 	0x0 }, 	/* /dotplus B: plus sign, dot above : 9573-2003-isoamsb*/
{ "plusdu", 	0x02A25, 	0x0 }, 	/* plus sign, dot below : 9573-2003-isoamsb*/
{ "pluse", 	0x02A72, 	0x0 }, 	/* plus, equals : 9573-2003-isoamsb*/
{ "plusmn", 	0x000B1, 	0x0 }, 	/* /pm B: =plus-or-minus sign : 9573-2003-isonum*/
{ "plussim", 	0x02A26, 	0x0 }, 	/* plus, similar below : 9573-2003-isoamsb*/
{ "plustrif", 	0x02A28, 	0x0 }, 	/*  : STIX*/
{ "plustwo", 	0x02A27, 	0x0 }, 	/* plus, two; Nim-addition : 9573-2003-isoamsb*/
{ "pm", 	0x000B1, 	0x0 }, 	/* alias ISONUM plusmn : mmlalias*/
{ "pointint", 	0x02A15, 	0x0 }, 	/* integral around a point operator : 9573-2003-isotech*/
{ "popf", 	0x1D561, 	0x0 }, 	/*  : mmlextra*/
{ "pound", 	0x000A3, 	0x0 }, 	/* =pound sign : 9573-2003-isonum*/
{ "pr", 	0x0227A, 	0x0 }, 	/* /prec R: precedes : 9573-2003-isoamsr*/
{ "prE", 	0x02AB3, 	0x0 }, 	/*  : STIX*/
{ "prap", 	0x02AB7, 	0x0 }, 	/* /precapprox R: precedes, approximate : 9573-2003-isoamsr*/
{ "prcue", 	0x0227C, 	0x0 }, 	/* /preccurlyeq R: precedes, curly eq : 9573-2003-isoamsr*/
{ "pre", 	0x02AAF, 	0x0 }, 	/* /preceq R: precedes, equals : 9573-2003-isoamsr*/
{ "prec", 	0x0227A, 	0x0 }, 	/* alias ISOAMSR pr : mmlalias*/
{ "precapprox", 	0x02AB7, 	0x0 }, 	/* alias ISOAMSR prap : mmlalias*/
{ "preccurlyeq", 	0x0227C, 	0x0 }, 	/* alias ISOAMSR prcue : mmlalias*/
{ "preceq", 	0x02AAF, 	0x0 }, 	/* alias ISOAMSR pre : mmlalias*/
{ "precnapprox", 	0x02AB9, 	0x0 }, 	/* alias ISOAMSN prnap : mmlalias*/
{ "precneqq", 	0x02AB5, 	0x0 }, 	/* alias ISOAMSN prnE : mmlalias*/
{ "precnsim", 	0x022E8, 	0x0 }, 	/* alias ISOAMSN prnsim : mmlalias*/
{ "precsim", 	0x0227E, 	0x0 }, 	/* alias ISOAMSR prsim : mmlalias*/
{ "prime", 	0x02032, 	0x0 }, 	/* /prime prime or minute : 9573-2003-isotech*/
{ "primes", 	0x02119, 	0x0 }, 	/* the prime natural numbers : mmlalias*/
{ "prnE", 	0x02AB5, 	0x0 }, 	/* /precneqq N: precedes, not dbl eq : 9573-2003-isoamsn*/
{ "prnap", 	0x02AB9, 	0x0 }, 	/* /precnapprox N: precedes, not approx : 9573-2003-isoamsn*/
{ "prnsim", 	0x022E8, 	0x0 }, 	/* /precnsim N: precedes, not similar : 9573-2003-isoamsn*/
{ "prod", 	0x0220F, 	0x0 }, 	/* /prod L: product operator : 9573-2003-isoamsb*/
{ "profalar", 	0x0232E, 	0x0 }, 	/* all-around profile : 9573-2003-isotech*/
{ "profline", 	0x02312, 	0x0 }, 	/* profile of a line : 9573-2003-isotech*/
{ "profsurf", 	0x02313, 	0x0 }, 	/* profile of a surface : 9573-2003-isotech*/
{ "prop", 	0x0221D, 	0x0 }, 	/* /propto R: is proportional to : 9573-2003-isotech*/
{ "propto", 	0x0221D, 	0x0 }, 	/* alias ISOTECH prop : mmlalias*/
{ "prsim", 	0x0227E, 	0x0 }, 	/* /precsim R: precedes, similar : 9573-2003-isoamsr*/
{ "prurel", 	0x022B0, 	0x0 }, 	/* element precedes under relation : 9573-2003-isoamsr*/
{ "pscr", 	0x1D4C5, 	0x0 }, 	/* /scr p, script letter p : 9573-2003-isomscr*/
{ "psgr", 	0x003C8, 	0x0 }, 	/* =small psi, Greek : 9573-2003-isogrk1*/
{ "psi", 	0x003C8, 	0x0 }, 	/* /psi small psi, Greek : 9573-2003-isogrk3*/
{ "puncsp", 	0x02008, 	0x0 }, 	/* =punctuation space (width of comma) : 9573-2003-isopub*/
{ "qfr", 	0x1D52E, 	0x0 }, 	/* /frak q, lower case q : 9573-2003-isomfrk*/
{ "qint", 	0x02A0C, 	0x0 }, 	/* /iiiint quadruple integral operator : 9573-2003-isotech*/
{ "qopf", 	0x1D562, 	0x0 }, 	/*  : mmlextra*/
{ "qprime", 	0x02057, 	0x0 }, 	/* quadruple prime : 9573-2003-isotech*/
{ "qscr", 	0x1D4C6, 	0x0 }, 	/* /scr q, script letter q : 9573-2003-isomscr*/
{ "quaternions", 	0x0210D, 	0x0 }, 	/* the ring (skew field) of quaternions : mmlalias*/
{ "quatint", 	0x02A16, 	0x0 }, 	/* quaternion integral operator : 9573-2003-isotech*/
{ "quest", 	0x0003F, 	0x0 }, 	/* =question mark : 9573-2003-isonum*/
{ "questeq", 	0x0225F, 	0x0 }, 	/* alias ISOAMSR equest : mmlalias*/
{ "quot", 	0x00022, 	0x0 }, 	/* =quotation mark : 9573-2003-isonum*/
{ "rAarr", 	0x021DB, 	0x0 }, 	/* /Rrightarrow A: right triple arrow : 9573-2003-isoamsa*/
{ "rArr", 	0x021D2, 	0x0 }, 	/* /Rightarrow A: implies : 9573-2003-isotech*/
{ "rAtail", 	0x0291C, 	0x0 }, 	/* right double arrow-tail : 9573-2003-isoamsa*/
{ "rBarr", 	0x0290F, 	0x0 }, 	/* /dbkarow A: right doubly broken arrow : 9573-2003-isoamsa*/
{ "rHar", 	0x02964, 	0x0 }, 	/* right harpoon-up over right harpoon-down : 9573-2003-isoamsa*/
{ "race", 	0x0223D, 	0x00331 }, 	/* reverse most positive, line below : 9573-2003-isoamsb*/
{ "racute", 	0x00155, 	0x0 }, 	/* =small r, acute accent : 9573-2003-isolat2*/
{ "radic", 	0x0221A, 	0x0 }, 	/* /surd radical : 9573-2003-isotech*/
{ "raemptyv", 	0x029B3, 	0x0 }, 	/* circle, slash, right arrow above : 9573-2003-isoamso*/
{ "rang", 	0x027E9, 	0x0 }, 	/* /rangle C: right angle bracket : 9573-2003-isotech*/
{ "rangd", 	0x02992, 	0x0 }, 	/* right angle, dot : 9573-2003-isoamsc*/
{ "range", 	0x029A5, 	0x0 }, 	/* reverse angle, equal : 9573-2003-isoamso*/
{ "rangle", 	0x027E9, 	0x0 }, 	/* alias ISOTECH rang : mmlalias*/
{ "raquo", 	0x000BB, 	0x0 }, 	/* =angle quotation mark, right : 9573-2003-isonum*/
{ "rarr", 	0x02192, 	0x0 }, 	/* /rightarrow /to A: =rightward arrow : 9573-2003-isonum*/
{ "rarr2", 	0x021C9, 	0x0 }, 	/* /rightrightarrows A: two rt arrows  : 8879-isoamsa*/
{ "rarr3", 	0x021F6, 	0x0 }, 	/*  : STIX*/
{ "rarrap", 	0x02975, 	0x0 }, 	/* approximate, right arrow above : 9573-2003-isoamsa*/
{ "rarrb", 	0x021E5, 	0x0 }, 	/* leftwards arrow to bar : mmlextra*/
{ "rarrbfs", 	0x02920, 	0x0 }, 	/* right arrow-bar, filled square : 9573-2003-isoamsa*/
{ "rarrc", 	0x02933, 	0x0 }, 	/* right arrow-curved : 9573-2003-isoamsa*/
{ "rarrfs", 	0x0291E, 	0x0 }, 	/* right arrow, filled square : 9573-2003-isoamsa*/
{ "rarrhk", 	0x021AA, 	0x0 }, 	/* /hookrightarrow A: rt arrow-hooked : 9573-2003-isoamsa*/
{ "rarrlp", 	0x021AC, 	0x0 }, 	/* /looparrowright A: rt arrow-looped : 9573-2003-isoamsa*/
{ "rarrpl", 	0x02945, 	0x0 }, 	/* right arrow, plus : 9573-2003-isoamsa*/
{ "rarrsim", 	0x02974, 	0x0 }, 	/* right arrow, similar : 9573-2003-isoamsa*/
{ "rarrtl", 	0x021A3, 	0x0 }, 	/* /rightarrowtail A: rt arrow-tailed : 9573-2003-isoamsa*/
{ "rarrw", 	0x0219D, 	0x0 }, 	/* /rightsquigarrow A: rt arrow-wavy : 9573-2003-isoamsa*/
{ "rarrx", 	0x02947, 	0x0 }, 	/*  : STIX*/
{ "ratail", 	0x0291A, 	0x0 }, 	/* right arrow-tail : 9573-2003-isoamsa*/
{ "ratio", 	0x02236, 	0x0 }, 	/* /ratio : 9573-2003-isoamsr*/
{ "rationals", 	0x0211A, 	0x0 }, 	/* the field of rational numbers : mmlalias*/
{ "rbarr", 	0x0290D, 	0x0 }, 	/* /bkarow A: right broken arrow : 9573-2003-isoamsa*/
{ "rbbrk", 	0x02773, 	0x0 }, 	/* right broken bracket : 9573-2003-isotech*/
{ "rbrace", 	0x0007D, 	0x0 }, 	/* alias ISONUM rcub : mmlalias*/
{ "rbrack", 	0x0005D, 	0x0 }, 	/* alias ISONUM rsqb : mmlalias*/
{ "rbrke", 	0x0298C, 	0x0 }, 	/* right bracket, equal : 9573-2003-isoamsc*/
{ "rbrksld", 	0x0298E, 	0x0 }, 	/* right bracket, solidus bottom corner : 9573-2003-isoamsc*/
{ "rbrkslu", 	0x02990, 	0x0 }, 	/* right bracket, solidus top corner : 9573-2003-isoamsc*/
{ "rcaron", 	0x00159, 	0x0 }, 	/* =small r, caron : 9573-2003-isolat2*/
{ "rcedil", 	0x00157, 	0x0 }, 	/* =small r, cedilla : 9573-2003-isolat2*/
{ "rceil", 	0x02309, 	0x0 }, 	/* /rceil C: right ceiling : 9573-2003-isoamsc*/
{ "rcub", 	0x0007D, 	0x0 }, 	/* /rbrace C: =right curly bracket : 9573-2003-isonum*/
{ "rcy", 	0x00440, 	0x0 }, 	/* =small er, Cyrillic : 9573-2003-isocyr1*/
{ "rdca", 	0x02937, 	0x0 }, 	/* right down curved arrow : 9573-2003-isoamsa*/
{ "rdharb", 	0x02957, 	0x0 }, 	/*  : STIX*/
{ "rdiag", 	0x02571, 	0x0 }, 	/*  : STIX*/
{ "rdiofdi", 	0x0292B, 	0x0 }, 	/*  : STIX*/
{ "rdldhar", 	0x02969, 	0x0 }, 	/* right harpoon-down over left harpoon-down : 9573-2003-isoamsa*/
{ "rdosearr", 	0x02930, 	0x0 }, 	/*  : STIX*/
{ "rdquo", 	0x0201D, 	0x0 }, 	/* =double quotation mark, right : 9573-2003-isonum*/
{ "rdquor", 	0x0201D, 	0x0 }, 	/* rising dbl quote, right (high) : 9573-2003-isopub*/
{ "rdsh", 	0x021B3, 	0x0 }, 	/* right down angled arrow : 9573-2003-isoamsa*/
{ "real", 	0x0211C, 	0x0 }, 	/* /Re - real : 9573-2003-isoamso*/
{ "realine", 	0x0211B, 	0x0 }, 	/* the geometric real line : mmlalias*/
{ "realpart", 	0x0211C, 	0x0 }, 	/* alias ISOAMSO real : mmlalias*/
{ "reals", 	0x0211D, 	0x0 }, 	/* the field of real numbers : mmlalias*/
{ "rect", 	0x025AD, 	0x0 }, 	/* =rectangle, open : 9573-2003-isopub*/
{ "reg", 	0x000AE, 	0x0 }, 	/* /circledR =registered sign : 9573-2003-isonum*/
{ "rfbowtie", 	0x029D2, 	0x0 }, 	/*  : STIX*/
{ "rfisht", 	0x0297D, 	0x0 }, 	/* right fish tail : 9573-2003-isoamsa*/
{ "rfloor", 	0x0230B, 	0x0 }, 	/* /rfloor C: right floor : 9573-2003-isoamsc*/
{ "rfr", 	0x1D52F, 	0x0 }, 	/* /frak r, lower case r : 9573-2003-isomfrk*/
{ "rftimes", 	0x029D5, 	0x0 }, 	/*  : STIX*/
{ "rgr", 	0x003C1, 	0x0 }, 	/* =small rho, Greek : 9573-2003-isogrk1*/
{ "rhard", 	0x021C1, 	0x0 }, 	/* /rightharpoondown A: rt harpoon-down : 9573-2003-isoamsa*/
{ "rharu", 	0x021C0, 	0x0 }, 	/* /rightharpoonup A: rt harpoon-up : 9573-2003-isoamsa*/
{ "rharul", 	0x0296C, 	0x0 }, 	/* right harpoon-up over long dash : 9573-2003-isoamsa*/
{ "rho", 	0x003C1, 	0x0 }, 	/* /rho small rho, Greek : 9573-2003-isogrk3*/
{ "rhov", 	0x003F1, 	0x0 }, 	/* /varrho : 9573-2003-isogrk3*/
{ "rightarrow", 	0x02192, 	0x0 }, 	/* alias ISONUM rarr : mmlalias*/
{ "rightarrowtail", 	0x021A3, 	0x0 }, 	/* alias ISOAMSA rarrtl : mmlalias*/
{ "rightharpoondown", 	0x021C1, 	0x0 }, 	/* alias ISOAMSA rhard : mmlalias*/
{ "rightharpoonup", 	0x021C0, 	0x0 }, 	/* alias ISOAMSA rharu : mmlalias*/
{ "rightleftarrows", 	0x021C4, 	0x0 }, 	/* alias ISOAMSA rlarr : mmlalias*/
{ "rightleftharpoons", 	0x021CC, 	0x0 }, 	/* alias ISOAMSA rlhar : mmlalias*/
{ "rightrightarrows", 	0x021C9, 	0x0 }, 	/* alias ISOAMSA rrarr : mmlalias*/
{ "rightsquigarrow", 	0x0219D, 	0x0 }, 	/* alias ISOAMSA rarrw : mmlalias*/
{ "rightthreetimes", 	0x022CC, 	0x0 }, 	/* alias ISOAMSB rthree : mmlalias*/
{ "rimply", 	0x02970, 	0x0 }, 	/*  : STIX*/
{ "ring", 	0x002DA, 	0x0 }, 	/* =ring : 9573-2003-isodia*/
{ "risingdotseq", 	0x02253, 	0x0 }, 	/* alias ISOAMSR erDot : mmlalias*/
{ "rlarr", 	0x021C4, 	0x0 }, 	/* /rightleftarrows A: r arr over l arr : 9573-2003-isoamsa*/
{ "rlarr2", 	0x021C4, 	0x0 }, 	/* /rightleftarrows A: r arr over l arr  : 8879-isoamsa*/
{ "rlhar", 	0x021CC, 	0x0 }, 	/* /rightleftharpoons A: r harp over l : 9573-2003-isoamsa*/
{ "rlhar2", 	0x021CC, 	0x0 }, 	/* /rightleftharpoons A: r harp over l  : 8879-isoamsa*/
{ "rlm", 	0x0200F, 	0x0 }, 	/*  : xhtml1-special*/
{ "rmoust", 	0x023B1, 	0x0 }, 	/* /rmoustache : 9573-2003-isoamsc*/
{ "rmoustache", 	0x023B1, 	0x0 }, 	/* alias ISOAMSC rmoust : mmlalias*/
{ "rnmid", 	0x02AEE, 	0x0 }, 	/* reverse /nmid : 9573-2003-isoamsn*/
{ "roang", 	0x027ED, 	0x0 }, 	/* right open angular bracket : 9573-2003-isotech*/
{ "roarr", 	0x021FE, 	0x0 }, 	/* right open arrow : 9573-2003-isoamsa*/
{ "robrk", 	0x027E7, 	0x0 }, 	/* right open bracket : 9573-2003-isotech*/
{ "rocub", 	0x02984, 	0x0 }, 	/*  : STIX*/
{ "ropar", 	0x02986, 	0x0 }, 	/* right open parenthesis : 9573-2003-isotech*/
{ "ropf", 	0x1D563, 	0x0 }, 	/*  : mmlextra*/
{ "roplus", 	0x02A2E, 	0x0 }, 	/* plus sign in right half circle : 9573-2003-isoamsb*/
{ "rotimes", 	0x02A35, 	0x0 }, 	/*  : STIX*/
{ "rpar", 	0x00029, 	0x0 }, 	/* C: =right parenthesis : 9573-2003-isonum*/
{ "rpargt", 	0x02994, 	0x0 }, 	/* C: right paren, gt : 9573-2003-isoamsc*/
{ "rppolint", 	0x02A12, 	0x0 }, 	/* line integration, rectangular path around pole : 9573-2003-isotech*/
{ "rrarr", 	0x021C9, 	0x0 }, 	/* /rightrightarrows A: two rt arrows : 9573-2003-isoamsa*/
{ "rsaquo", 	0x0203A, 	0x0 }, 	/*  : xhtml1-special*/
{ "rscr", 	0x1D4C7, 	0x0 }, 	/* /scr r, script letter r : 9573-2003-isomscr*/
{ "rsh", 	0x021B1, 	0x0 }, 	/* /Rsh A: : 9573-2003-isoamsa*/
{ "rsolbar", 	0x029F7, 	0x0 }, 	/*  : STIX*/
{ "rsqb", 	0x0005D, 	0x0 }, 	/* /rbrack C: =right square bracket : 9573-2003-isonum*/
{ "rsquo", 	0x02019, 	0x0 }, 	/* =single quotation mark, right : 9573-2003-isonum*/
{ "rsquor", 	0x02019, 	0x0 }, 	/* rising single quote, right (high) : 9573-2003-isopub*/
{ "rthree", 	0x022CC, 	0x0 }, 	/* /rightthreetimes B: : 9573-2003-isoamsb*/
{ "rtimes", 	0x022CA, 	0x0 }, 	/* /rtimes B: times sign, right closed : 9573-2003-isoamsb*/
{ "rtri", 	0x025B9, 	0x0 }, 	/* /triangleright B: r triangle, open : 9573-2003-isopub*/
{ "rtrie", 	0x022B5, 	0x0 }, 	/* /trianglerighteq R: right tri, eq : 9573-2003-isoamsr*/
{ "rtrif", 	0x025B8, 	0x0 }, 	/* /blacktriangleright R: =r tri, filled : 9573-2003-isopub*/
{ "rtriltri", 	0x029CE, 	0x0 }, 	/* right triangle above left triangle : 9573-2003-isoamsr*/
{ "ruharb", 	0x02953, 	0x0 }, 	/*  : STIX*/
{ "ruluhar", 	0x02968, 	0x0 }, 	/* right harpoon-up over left harpoon-up : 9573-2003-isoamsa*/
{ "rx", 	0x0211E, 	0x0 }, 	/* pharmaceutical prescription (Rx) : 9573-2003-isopub*/
{ "sacute", 	0x0015B, 	0x0 }, 	/* =small s, acute accent : 9573-2003-isolat2*/
{ "samalg", 	0x02210, 	0x0 }, 	/* /smallamalg R: small amalg : 8879-isoamsr*/
{ "sampi", 	0x003E0, 	0x0 }, 	/* 03E0 : STIX*/
{ "sbquo", 	0x0201A, 	0x0 }, 	/* single low-9 quotation mark : xhtml1-special*/
{ "sbsol", 	0x0FE68, 	0x0 }, 	/*  : 8879-isoamso*/
{ "sc", 	0x0227B, 	0x0 }, 	/* /succ R: succeeds : 9573-2003-isoamsr*/
{ "scE", 	0x02AB4, 	0x0 }, 	/*  : STIX*/
{ "scap", 	0x02AB8, 	0x0 }, 	/* /succapprox R: succeeds, approximate : 9573-2003-isoamsr*/
{ "scaron", 	0x00161, 	0x0 }, 	/* =small s, caron : 9573-2003-isolat2*/
{ "sccue", 	0x0227D, 	0x0 }, 	/* /succcurlyeq R: succeeds, curly eq : 9573-2003-isoamsr*/
{ "sce", 	0x02AB0, 	0x0 }, 	/*  : STIX*/
{ "scedil", 	0x0015F, 	0x0 }, 	/* =small s, cedilla : 9573-2003-isolat2*/
{ "scirc", 	0x0015D, 	0x0 }, 	/* =small s, circumflex accent : 9573-2003-isolat2*/
{ "scnE", 	0x02AB6, 	0x0 }, 	/* /succneqq N: succeeds, not dbl eq : 9573-2003-isoamsn*/
{ "scnap", 	0x02ABA, 	0x0 }, 	/* /succnapprox N: succeeds, not approx : 9573-2003-isoamsn*/
{ "scnsim", 	0x022E9, 	0x0 }, 	/* /succnsim N: succeeds, not similar : 9573-2003-isoamsn*/
{ "scpolint", 	0x02A13, 	0x0 }, 	/* line integration, semi-circular path around pole : 9573-2003-isotech*/
{ "scsim", 	0x0227F, 	0x0 }, 	/* /succsim R: succeeds, similar : 9573-2003-isoamsr*/
{ "scy", 	0x00441, 	0x0 }, 	/* =small es, Cyrillic : 9573-2003-isocyr1*/
{ "sdot", 	0x022C5, 	0x0 }, 	/* /cdot B: small middle dot : 9573-2003-isoamsb*/
{ "sdotb", 	0x022A1, 	0x0 }, 	/* /dotsquare /boxdot B: small dot in box : 9573-2003-isoamsb*/
{ "sdote", 	0x02A66, 	0x0 }, 	/* equal, dot below : 9573-2003-isoamsr*/
{ "seArr", 	0x021D8, 	0x0 }, 	/* SE pointing dbl arrow : 9573-2003-isoamsa*/
{ "searhk", 	0x02925, 	0x0 }, 	/* /hksearow A: SE arrow-hooken : 9573-2003-isoamsa*/
{ "searr", 	0x02198, 	0x0 }, 	/* /searrow A: SE pointing arrow : 9573-2003-isoamsa*/
{ "searrow", 	0x02198, 	0x0 }, 	/* alias ISOAMSA searr : mmlalias*/
{ "sect", 	0x000A7, 	0x0 }, 	/* =section sign : 9573-2003-isonum*/
{ "semi", 	0x0003B, 	0x0 }, 	/* =semicolon P: : 9573-2003-isonum*/
{ "seonearr", 	0x0292D, 	0x0 }, 	/*  : STIX*/
{ "seswar", 	0x02929, 	0x0 }, 	/* /tosa A: SE & SW arrows : 9573-2003-isoamsa*/
{ "setminus", 	0x02216, 	0x0 }, 	/* alias ISOAMSB setmn : mmlalias*/
{ "setmn", 	0x02216, 	0x0 }, 	/* /setminus B: reverse solidus : 9573-2003-isoamsb*/
{ "sext", 	0x02736, 	0x0 }, 	/* sextile (6-pointed star) : 9573-2003-isopub*/
{ "sfgr", 	0x003C2, 	0x0 }, 	/* =final small sigma, Greek : 9573-2003-isogrk1*/
{ "sfr", 	0x1D530, 	0x0 }, 	/* /frak s, lower case s : 9573-2003-isomfrk*/
{ "sfrown", 	0x02322, 	0x0 }, 	/* /smallfrown R: small down curve : 9573-2003-isoamsr*/
{ "sgr", 	0x003C3, 	0x0 }, 	/* =small sigma, Greek : 9573-2003-isogrk1*/
{ "sharp", 	0x0266F, 	0x0 }, 	/* /sharp =musical sharp : 9573-2003-isopub*/
{ "shchcy", 	0x00449, 	0x0 }, 	/* =small shcha, Cyrillic : 9573-2003-isocyr1*/
{ "shcy", 	0x00448, 	0x0 }, 	/* =small sha, Cyrillic : 9573-2003-isocyr1*/
{ "shortmid", 	0x02223, 	0x0 }, 	/* alias ISOAMSR smid : mmlalias*/
{ "shortparallel", 	0x02225, 	0x0 }, 	/* alias ISOAMSR spar : mmlalias*/
{ "shuffle", 	0x029E2, 	0x0 }, 	/*  : STIX*/
{ "shy", 	0x000AD, 	0x0 }, 	/* =soft hyphen : 9573-2003-isonum*/
{ "sigma", 	0x003C3, 	0x0 }, 	/* /sigma small sigma, Greek : 9573-2003-isogrk3*/
{ "sigmaf", 	0x003C2, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "sigmav", 	0x003C2, 	0x0 }, 	/* /varsigma : 9573-2003-isogrk3*/
{ "sim", 	0x0223C, 	0x0 }, 	/* /sim R: similar : 9573-2003-isotech*/
{ "simdot", 	0x02A6A, 	0x0 }, 	/* similar, dot : 9573-2003-isotech*/
{ "sime", 	0x02243, 	0x0 }, 	/* /simeq R: similar, equals : 9573-2003-isotech*/
{ "simeq", 	0x02243, 	0x0 }, 	/* alias ISOTECH sime : mmlalias*/
{ "simg", 	0x02A9E, 	0x0 }, 	/* similar, greater : 9573-2003-isoamsr*/
{ "simgE", 	0x02AA0, 	0x0 }, 	/* similar, greater, equal : 9573-2003-isoamsr*/
{ "siml", 	0x02A9D, 	0x0 }, 	/* similar, less : 9573-2003-isoamsr*/
{ "simlE", 	0x02A9F, 	0x0 }, 	/* similar, less, equal : 9573-2003-isoamsr*/
{ "simne", 	0x02246, 	0x0 }, 	/* similar, not equals : 9573-2003-isoamsn*/
{ "simplus", 	0x02A24, 	0x0 }, 	/* plus, similar above : 9573-2003-isoamsb*/
{ "simrarr", 	0x02972, 	0x0 }, 	/* similar, right arrow below : 9573-2003-isoamsa*/
{ "slarr", 	0x02190, 	0x0 }, 	/* short left arrow : 9573-2003-isoamsa*/
{ "slint", 	0x02A0F, 	0x0 }, 	/*  : STIX*/
{ "smallsetminus", 	0x02216, 	0x0 }, 	/* alias ISOAMSB ssetmn : mmlalias*/
{ "smashp", 	0x02A33, 	0x0 }, 	/* smash product : 9573-2003-isoamsb*/
{ "smeparsl", 	0x029E4, 	0x0 }, 	/* similar, parallel, slanted, equal : 9573-2003-isotech*/
{ "smid", 	0x02223, 	0x0 }, 	/* /shortmid R: : 9573-2003-isoamsr*/
{ "smile", 	0x02323, 	0x0 }, 	/* /smile R: up curve : 9573-2003-isoamsr*/
{ "smt", 	0x02AAA, 	0x0 }, 	/* smaller than : 9573-2003-isoamsr*/
{ "smte", 	0x02AAC, 	0x0 }, 	/* smaller than or equal : 9573-2003-isoamsr*/
{ "smtes", 	0x02AAC, 	0x0FE00 }, 	/* smaller than or equal, slanted : 9573-2003-isoamsr*/
{ "softcy", 	0x0044C, 	0x0 }, 	/* =small soft sign, Cyrillic : 9573-2003-isocyr1*/
{ "sol", 	0x0002F, 	0x0 }, 	/* =solidus : 9573-2003-isonum*/
{ "solb", 	0x029C4, 	0x0 }, 	/* solidus in square : 9573-2003-isoamsb*/
{ "solbar", 	0x0233F, 	0x0 }, 	/* solidus, bar through : 9573-2003-isoamsn*/
{ "sopf", 	0x1D564, 	0x0 }, 	/*  : mmlextra*/
{ "spades", 	0x02660, 	0x0 }, 	/* black spade suit : xhtml1-symbol*/
{ "spadesuit", 	0x02660, 	0x0 }, 	/* ISOPUB    spades  : mmlalias*/
{ "spar", 	0x02225, 	0x0 }, 	/* /shortparallel R: short parallel : 9573-2003-isoamsr*/
{ "sqcap", 	0x02293, 	0x0 }, 	/* /sqcap B: square intersection : 9573-2003-isoamsb*/
{ "sqcaps", 	0x02293, 	0x0FE00 }, 	/* square intersection, serifs : 9573-2003-isoamsb*/
{ "sqcup", 	0x02294, 	0x0 }, 	/* /sqcup B: square union : 9573-2003-isoamsb*/
{ "sqcups", 	0x02294, 	0x0FE00 }, 	/* square union, serifs : 9573-2003-isoamsb*/
{ "sqsub", 	0x0228F, 	0x0 }, 	/* /sqsubset R: square subset : 9573-2003-isoamsr*/
{ "sqsube", 	0x02291, 	0x0 }, 	/* /sqsubseteq R: square subset, equals : 9573-2003-isoamsr*/
{ "sqsubset", 	0x0228F, 	0x0 }, 	/* alias ISOAMSR sqsub : mmlalias*/
{ "sqsubseteq", 	0x02291, 	0x0 }, 	/* alias ISOAMSR sqsube : mmlalias*/
{ "sqsup", 	0x02290, 	0x0 }, 	/* /sqsupset R: square superset : 9573-2003-isoamsr*/
{ "sqsupe", 	0x02292, 	0x0 }, 	/* /sqsupseteq R: square superset, eq : 9573-2003-isoamsr*/
{ "sqsupset", 	0x02290, 	0x0 }, 	/* alias ISOAMSR sqsup : mmlalias*/
{ "sqsupseteq", 	0x02292, 	0x0 }, 	/* alias ISOAMSR sqsupe : mmlalias*/
{ "squ", 	0x025A1, 	0x0 }, 	/* =square, open : 9573-2003-isopub*/
{ "square", 	0x025A1, 	0x0 }, 	/* /square, square : 9573-2003-isotech*/
{ "squarf", 	0x025AA, 	0x0 }, 	/* /blacksquare, square, filled  : 9573-2003-isotech*/
{ "squb", 	0x029C8, 	0x0 }, 	/*  : STIX*/
{ "squerr", 	0x029EE, 	0x0 }, 	/*  : STIX*/
{ "squf", 	0x025AA, 	0x0 }, 	/* /blacksquare =sq bullet, filled : 9573-2003-isopub*/
{ "squferr", 	0x029EF, 	0x0 }, 	/*  : STIX*/
{ "srarr", 	0x02192, 	0x0 }, 	/* short right arrow : 9573-2003-isoamsa*/
{ "sscr", 	0x1D4C8, 	0x0 }, 	/* /scr s, script letter s : 9573-2003-isomscr*/
{ "ssetmn", 	0x02216, 	0x0 }, 	/* /smallsetminus B: sm reverse solidus : 9573-2003-isoamsb*/
{ "ssmile", 	0x02323, 	0x0 }, 	/* /smallsmile R: small up curve : 9573-2003-isoamsr*/
{ "sstarf", 	0x022C6, 	0x0 }, 	/* /star B: small star, filled : 9573-2003-isoamsb*/
{ "star", 	0x02606, 	0x0 }, 	/* =star, open : 9573-2003-isopub*/
{ "starf", 	0x02605, 	0x0 }, 	/* /bigstar - star, filled  : 9573-2003-isopub*/
{ "stigma", 	0x003DA, 	0x0 }, 	/* 03DA : STIX*/
{ "straightepsilon", 	0x003F5, 	0x0 }, 	/* alias ISOGRK3 epsiv : mmlalias*/
{ "straightphi", 	0x003D5, 	0x0 }, 	/* alias ISOGRK3 phiv : mmlalias*/
{ "strns", 	0x000AF, 	0x0 }, 	/* straightness : 9573-2003-isotech*/
{ "sub", 	0x02282, 	0x0 }, 	/* /subset R: subset or is implied by : 9573-2003-isotech*/
{ "subE", 	0x02AC5, 	0x0 }, 	/*  : STIX*/
{ "subdot", 	0x02ABD, 	0x0 }, 	/* subset, with dot : 9573-2003-isoamsb*/
{ "sube", 	0x02286, 	0x0 }, 	/* /subseteq R: subset, equals : 9573-2003-isotech*/
{ "subedot", 	0x02AC3, 	0x0 }, 	/* subset, equals, dot : 9573-2003-isoamsr*/
{ "submult", 	0x02AC1, 	0x0 }, 	/* subset, multiply : 9573-2003-isoamsr*/
{ "subnE", 	0x02ACB, 	0x0 }, 	/*  : STIX*/
{ "subne", 	0x0228A, 	0x0 }, 	/* /subsetneq N: subset, not equals : 9573-2003-isoamsn*/
{ "subplus", 	0x02ABF, 	0x0 }, 	/* subset, plus : 9573-2003-isoamsr*/
{ "subrarr", 	0x02979, 	0x0 }, 	/* subset, right arrow : 9573-2003-isoamsr*/
{ "subset", 	0x02282, 	0x0 }, 	/* alias ISOTECH sub : mmlalias*/
{ "subseteq", 	0x02286, 	0x0 }, 	/* alias ISOTECH sube : mmlalias*/
{ "subseteqq", 	0x02AC5, 	0x0 }, 	/* alias ISOAMSR subE : mmlalias*/
{ "subsetneq", 	0x0228A, 	0x0 }, 	/* alias ISOAMSN subne : mmlalias*/
{ "subsetneqq", 	0x02ACB, 	0x0 }, 	/* alias ISOAMSN subnE : mmlalias*/
{ "subsim", 	0x02AC7, 	0x0 }, 	/* subset, similar : 9573-2003-isoamsr*/
{ "subsub", 	0x02AD5, 	0x0 }, 	/* subset above subset : 9573-2003-isoamsr*/
{ "subsup", 	0x02AD3, 	0x0 }, 	/* subset above superset : 9573-2003-isoamsr*/
{ "succ", 	0x0227B, 	0x0 }, 	/* alias ISOAMSR sc : mmlalias*/
{ "succapprox", 	0x02AB8, 	0x0 }, 	/* alias ISOAMSR scap : mmlalias*/
{ "succcurlyeq", 	0x0227D, 	0x0 }, 	/* alias ISOAMSR sccue : mmlalias*/
{ "succeq", 	0x02AB0, 	0x0 }, 	/* alias ISOAMSR sce : mmlalias*/
{ "succnapprox", 	0x02ABA, 	0x0 }, 	/* alias ISOAMSN scnap : mmlalias*/
{ "succneqq", 	0x02AB6, 	0x0 }, 	/* alias ISOAMSN scnE : mmlalias*/
{ "succnsim", 	0x022E9, 	0x0 }, 	/* alias ISOAMSN scnsim : mmlalias*/
{ "succsim", 	0x0227F, 	0x0 }, 	/* alias ISOAMSR scsim : mmlalias*/
{ "sum", 	0x02211, 	0x0 }, 	/* /sum L: summation operator : 9573-2003-isoamsb*/
{ "sumint", 	0x02A0B, 	0x0 }, 	/*  : STIX*/
{ "sung", 	0x0266A, 	0x0 }, 	/* =music note (sung text sign) : 9573-2003-isonum*/
{ "sup", 	0x02283, 	0x0 }, 	/* /supset R: superset or implies : 9573-2003-isotech*/
{ "sup1", 	0x000B9, 	0x0 }, 	/* =superscript one : 9573-2003-isonum*/
{ "sup2", 	0x000B2, 	0x0 }, 	/* =superscript two : 9573-2003-isonum*/
{ "sup3", 	0x000B3, 	0x0 }, 	/* =superscript three : 9573-2003-isonum*/
{ "supE", 	0x02AC6, 	0x0 }, 	/*  : STIX*/
{ "supdot", 	0x02ABE, 	0x0 }, 	/* superset, with dot : 9573-2003-isoamsb*/
{ "supdsub", 	0x02AD8, 	0x0 }, 	/* superset, subset, dash joining them : 9573-2003-isoamsr*/
{ "supe", 	0x02287, 	0x0 }, 	/* /supseteq R: superset, equals : 9573-2003-isotech*/
{ "supedot", 	0x02AC4, 	0x0 }, 	/* superset, equals, dot : 9573-2003-isoamsr*/
{ "suphsol", 	0x027C9, 	0x0 }, 	/* superset, solidus : 9573-2003-isoamsr*/
{ "suphsub", 	0x02AD7, 	0x0 }, 	/* superset, subset : 9573-2003-isoamsr*/
{ "suplarr", 	0x0297B, 	0x0 }, 	/* superset, left arrow : 9573-2003-isoamsr*/
{ "supmult", 	0x02AC2, 	0x0 }, 	/* superset, multiply : 9573-2003-isoamsr*/
{ "supnE", 	0x02ACC, 	0x0 }, 	/*  : STIX*/
{ "supne", 	0x0228B, 	0x0 }, 	/* /supsetneq N: superset, not equals : 9573-2003-isoamsn*/
{ "supplus", 	0x02AC0, 	0x0 }, 	/* superset, plus : 9573-2003-isoamsr*/
{ "supset", 	0x02283, 	0x0 }, 	/* alias ISOTECH sup : mmlalias*/
{ "supseteq", 	0x02287, 	0x0 }, 	/* alias ISOTECH supe : mmlalias*/
{ "supseteqq", 	0x02AC6, 	0x0 }, 	/* alias ISOAMSR supE : mmlalias*/
{ "supsetneq", 	0x0228B, 	0x0 }, 	/* alias ISOAMSN supne : mmlalias*/
{ "supsetneqq", 	0x02ACC, 	0x0 }, 	/* alias ISOAMSN supnE : mmlalias*/
{ "supsim", 	0x02AC8, 	0x0 }, 	/* superset, similar : 9573-2003-isoamsr*/
{ "supsub", 	0x02AD4, 	0x0 }, 	/* superset above subset : 9573-2003-isoamsr*/
{ "supsup", 	0x02AD6, 	0x0 }, 	/* superset above superset : 9573-2003-isoamsr*/
{ "swArr", 	0x021D9, 	0x0 }, 	/* SW pointing dbl arrow : 9573-2003-isoamsa*/
{ "swarhk", 	0x02926, 	0x0 }, 	/* /hkswarow A: SW arrow-hooked : 9573-2003-isoamsa*/
{ "swarr", 	0x02199, 	0x0 }, 	/* /swarrow A: SW pointing arrow : 9573-2003-isoamsa*/
{ "swarrow", 	0x02199, 	0x0 }, 	/* alias ISOAMSA swarr : mmlalias*/
{ "swnwar", 	0x0292A, 	0x0 }, 	/* SW & NW arrows : 9573-2003-isoamsa*/
{ "szlig", 	0x000DF, 	0x0 }, 	/* =small sharp s, German (sz ligature) : 9573-2003-isolat1*/
{ "target", 	0x02316, 	0x0 }, 	/* register mark or target : 9573-2003-isopub*/
{ "tau", 	0x003C4, 	0x0 }, 	/* /tau small tau, Greek : 9573-2003-isogrk3*/
{ "tbrk", 	0x023B4, 	0x0 }, 	/* top square bracket : 9573-2003-isoamso*/
{ "tcaron", 	0x00165, 	0x0 }, 	/* =small t, caron : 9573-2003-isolat2*/
{ "tcedil", 	0x00163, 	0x0 }, 	/* =small t, cedilla : 9573-2003-isolat2*/
{ "tcy", 	0x00442, 	0x0 }, 	/* =small te, Cyrillic : 9573-2003-isocyr1*/
{ "tdot", 	0x020DB, 	0x0 }, 	/* three dots above : 9573-2003-isotech*/
{ "telrec", 	0x02315, 	0x0 }, 	/* =telephone recorder symbol : 9573-2003-isopub*/
{ "tfr", 	0x1D531, 	0x0 }, 	/* /frak t, lower case t : 9573-2003-isomfrk*/
{ "tgr", 	0x003C4, 	0x0 }, 	/* =small tau, Greek : 9573-2003-isogrk1*/
{ "there4", 	0x02234, 	0x0 }, 	/* /therefore R: therefore : 9573-2003-isotech*/
{ "therefore", 	0x02234, 	0x0 }, 	/* alias ISOTECH there4 : mmlalias*/
{ "thermod", 	0x029E7, 	0x0 }, 	/* 01C2 : STIX*/
{ "theta", 	0x003B8, 	0x0 }, 	/* greek small letter theta : xhtml1-symbol*/
{ "thetas", 	0x003B8, 	0x0 }, 	/* straight theta : 8879-isogrk3*/
{ "thetasym", 	0x003D1, 	0x0 }, 	/* greek small letter theta symbol : xhtml1-symbol*/
{ "thetav", 	0x003D1, 	0x0 }, 	/* /vartheta - curly or open theta : 9573-2003-isogrk3*/
{ "thgr", 	0x003B8, 	0x0 }, 	/* =small theta, Greek : 9573-2003-isogrk1*/
{ "thickapprox", 	0x02248, 	0x0 }, 	/* ISOAMSR   thkap  : mmlalias*/
{ "thicksim", 	0x0223C, 	0x0 }, 	/* ISOAMSR   thksim : mmlalias*/
{ "thinsp", 	0x02009, 	0x0 }, 	/* =thin space (1/6-em) : 9573-2003-isopub*/
{ "thkap", 	0x02248, 	0x0 }, 	/* /thickapprox R: thick approximate : 9573-2003-isoamsr*/
{ "thksim", 	0x0223C, 	0x0 }, 	/* /thicksim R: thick similar : 9573-2003-isoamsr*/
{ "thorn", 	0x000FE, 	0x0 }, 	/* =small thorn, Icelandic : 9573-2003-isolat1*/
{ "tilde", 	0x002DC, 	0x0 }, 	/* =tilde : 9573-2003-isodia*/
{ "timeint", 	0x02A18, 	0x0 }, 	/*  : STIX*/
{ "times", 	0x000D7, 	0x0 }, 	/* /times B: =multiply sign : 9573-2003-isonum*/
{ "timesb", 	0x022A0, 	0x0 }, 	/* /boxtimes B: multiply sign in box : 9573-2003-isoamsb*/
{ "timesbar", 	0x02A31, 	0x0 }, 	/* multiply sign, bar below : 9573-2003-isoamsb*/
{ "timesd", 	0x02A30, 	0x0 }, 	/* times, dot : 9573-2003-isoamsb*/
{ "tint", 	0x0222D, 	0x0 }, 	/* /iiint triple integral operator : 9573-2003-isotech*/
{ "toea", 	0x02928, 	0x0 }, 	/* alias ISOAMSA nesear : mmlalias*/
{ "top", 	0x022A4, 	0x0 }, 	/* /top top : 9573-2003-isotech*/
{ "topbot", 	0x02336, 	0x0 }, 	/* top and bottom : 9573-2003-isotech*/
{ "topcir", 	0x02AF1, 	0x0 }, 	/* top, circle below : 9573-2003-isotech*/
{ "topf", 	0x1D565, 	0x0 }, 	/*  : mmlextra*/
{ "topfork", 	0x02ADA, 	0x0 }, 	/* fork with top : 9573-2003-isoamsr*/
{ "tosa", 	0x02929, 	0x0 }, 	/* alias ISOAMSA seswar : mmlalias*/
{ "tprime", 	0x02034, 	0x0 }, 	/* triple prime : 9573-2003-isotech*/
{ "trade", 	0x02122, 	0x0 }, 	/* =trade mark sign : 9573-2003-isonum*/
{ "triS", 	0x029CC, 	0x0 }, 	/*  : STIX*/
{ "triangle", 	0x025B5, 	0x0 }, 	/* alias ISOPUB utri : mmlalias*/
{ "triangledown", 	0x025BF, 	0x0 }, 	/* alias ISOPUB dtri : mmlalias*/
{ "triangleleft", 	0x025C3, 	0x0 }, 	/* alias ISOPUB ltri : mmlalias*/
{ "trianglelefteq", 	0x022B4, 	0x0 }, 	/* alias ISOAMSR ltrie : mmlalias*/
{ "triangleq", 	0x0225C, 	0x0 }, 	/* alias ISOAMSR trie : mmlalias*/
{ "triangleright", 	0x025B9, 	0x0 }, 	/* alias ISOPUB rtri : mmlalias*/
{ "trianglerighteq", 	0x022B5, 	0x0 }, 	/* alias ISOAMSR rtrie : mmlalias*/
{ "tribar", 	0x029CB, 	0x0 }, 	/*  : STIX*/
{ "tridot", 	0x025EC, 	0x0 }, 	/* dot in triangle : 9573-2003-isoamsb*/
{ "tridoto", 	0x029CA, 	0x0 }, 	/*  : STIX*/
{ "trie", 	0x0225C, 	0x0 }, 	/* /triangleq R: triangle, equals : 9573-2003-isoamsr*/
{ "triminus", 	0x02A3A, 	0x0 }, 	/* minus in triangle : 9573-2003-isoamsb*/
{ "triplus", 	0x02A39, 	0x0 }, 	/* plus in triangle : 9573-2003-isoamsb*/
{ "trisb", 	0x029CD, 	0x0 }, 	/* triangle, serifs at bottom : 9573-2003-isoamsb*/
{ "tritime", 	0x02A3B, 	0x0 }, 	/* multiply in triangle : 9573-2003-isoamsb*/
{ "trpezium", 	0x023E2, 	0x0 }, 	/* trapezium : 9573-2003-isoamso*/
{ "tscr", 	0x1D4C9, 	0x0 }, 	/* /scr t, script letter t : 9573-2003-isomscr*/
{ "tscy", 	0x00446, 	0x0 }, 	/* =small tse, Cyrillic : 9573-2003-isocyr1*/
{ "tshcy", 	0x0045B, 	0x0 }, 	/* =small tshe, Serbian : 9573-2003-isocyr2*/
{ "tstrok", 	0x00167, 	0x0 }, 	/* =small t, stroke : 9573-2003-isolat2*/
{ "tverbar", 	0x02980, 	0x0 }, 	/*  : STIX*/
{ "twixt", 	0x0226C, 	0x0 }, 	/* /between R: between : 9573-2003-isoamsr*/
{ "twoheadleftarrow", 	0x0219E, 	0x0 }, 	/* alias ISOAMSA Larr : mmlalias*/
{ "twoheadrightarrow", 	0x021A0, 	0x0 }, 	/* alias ISOAMSA Rarr : mmlalias*/
{ "uAarr", 	0x0290A, 	0x0 }, 	/*  : STIX*/
{ "uArr", 	0x021D1, 	0x0 }, 	/* /Uparrow A: up dbl arrow : 9573-2003-isoamsa*/
{ "uHar", 	0x02963, 	0x0 }, 	/* up harpoon-left, up harpoon-right : 9573-2003-isoamsa*/
{ "uacgr", 	0x003CD, 	0x0 }, 	/* =small upsilon, accent, Greek : 9573-2003-isogrk2*/
{ "uacute", 	0x000FA, 	0x0 }, 	/* =small u, acute accent : 9573-2003-isolat1*/
{ "uarr", 	0x02191, 	0x0 }, 	/* /uparrow A: =upward arrow : 9573-2003-isonum*/
{ "uarr2", 	0x021C8, 	0x0 }, 	/* /upuparrows A: two up arrows  : 8879-isoamsa*/
{ "uarrb", 	0x02912, 	0x0 }, 	/*  : STIX*/
{ "uarrln", 	0x02909, 	0x0 }, 	/* 234F : STIX*/
{ "ubrcy", 	0x0045E, 	0x0 }, 	/* =small u, Byelorussian : 9573-2003-isocyr2*/
{ "ubreve", 	0x0016D, 	0x0 }, 	/* =small u, breve : 9573-2003-isolat2*/
{ "ucirc", 	0x000FB, 	0x0 }, 	/* =small u, circumflex accent : 9573-2003-isolat1*/
{ "ucy", 	0x00443, 	0x0 }, 	/* =small u, Cyrillic : 9573-2003-isocyr1*/
{ "udarr", 	0x021C5, 	0x0 }, 	/* up arrow, down arrow : 9573-2003-isoamsa*/
{ "udblac", 	0x00171, 	0x0 }, 	/* =small u, double acute accent : 9573-2003-isolat2*/
{ "udhar", 	0x0296E, 	0x0 }, 	/* up harp, down harp : 9573-2003-isoamsa*/
{ "udiagr", 	0x003B0, 	0x0 }, 	/* =small upsilon, dieresis, accent, Greek : 9573-2003-isogrk2*/
{ "udigr", 	0x003CB, 	0x0 }, 	/* =small upsilon, dieresis, Greek : 9573-2003-isogrk2*/
{ "udrbrk", 	0x023B5, 	0x0 }, 	/*  : STIX*/
{ "udrcub", 	0x023DF, 	0x0 }, 	/*  : STIX*/
{ "udrpar", 	0x023DD, 	0x0 }, 	/*  : STIX*/
{ "ufisht", 	0x0297E, 	0x0 }, 	/* up fish tail : 9573-2003-isoamsa*/
{ "ufr", 	0x1D532, 	0x0 }, 	/* /frak u, lower case u : 9573-2003-isomfrk*/
{ "ugr", 	0x003C5, 	0x0 }, 	/* =small upsilon, Greek : 9573-2003-isogrk1*/
{ "ugrave", 	0x000F9, 	0x0 }, 	/* =small u, grave accent : 9573-2003-isolat1*/
{ "uharl", 	0x021BF, 	0x0 }, 	/* /upharpoonleft A: up harpoon-left : 9573-2003-isoamsa*/
{ "uharr", 	0x021BE, 	0x0 }, 	/* /upharpoonright /restriction A: up harp-r : 9573-2003-isoamsa*/
{ "uhblk", 	0x02580, 	0x0 }, 	/* =upper half block : 9573-2003-isopub*/
{ "ulcorn", 	0x0231C, 	0x0 }, 	/* /ulcorner O: upper left corner : 9573-2003-isoamsc*/
{ "ulcorner", 	0x0231C, 	0x0 }, 	/* alias ISOAMSC ulcorn : mmlalias*/
{ "ulcrop", 	0x0230F, 	0x0 }, 	/* upward left crop mark  : 9573-2003-isopub*/
{ "uldlshar", 	0x02951, 	0x0 }, 	/*  : STIX*/
{ "ulharb", 	0x02958, 	0x0 }, 	/*  : STIX*/
{ "ultri", 	0x025F8, 	0x0 }, 	/* upper left triangle : 9573-2003-isoamso*/
{ "umacr", 	0x0016B, 	0x0 }, 	/* =small u, macron : 9573-2003-isolat2*/
{ "uml", 	0x000A8, 	0x0 }, 	/* =umlaut mark : 9573-2003-isodia*/
{ "uogon", 	0x00173, 	0x0 }, 	/* =small u, ogonek : 9573-2003-isolat2*/
{ "uopf", 	0x1D566, 	0x0 }, 	/*  : mmlextra*/
{ "uparrow", 	0x02191, 	0x0 }, 	/* alias ISONUM uarr : mmlalias*/
{ "updownarrow", 	0x02195, 	0x0 }, 	/* alias ISOAMSA varr : mmlalias*/
{ "upharpoonleft", 	0x021BF, 	0x0 }, 	/* alias ISOAMSA uharl : mmlalias*/
{ "upharpoonright", 	0x021BE, 	0x0 }, 	/* alias ISOAMSA uharr : mmlalias*/
{ "upint", 	0x02A1B, 	0x0 }, 	/*  : STIX*/
{ "uplus", 	0x0228E, 	0x0 }, 	/* /uplus B: plus sign in union : 9573-2003-isoamsb*/
{ "upsi", 	0x003C5, 	0x0 }, 	/* /upsilon small upsilon, Greek : 9573-2003-isogrk3*/
{ "upsih", 	0x003D2, 	0x0 }, 	/* greek upsilon with hook symbol : xhtml1-symbol*/
{ "upsilon", 	0x003C5, 	0x0 }, 	/*  : xhtml1-symbol*/
{ "upuparrows", 	0x021C8, 	0x0 }, 	/* alias ISOAMSA uuarr : mmlalias*/
{ "urcorn", 	0x0231D, 	0x0 }, 	/* /urcorner C: upper right corner : 9573-2003-isoamsc*/
{ "urcorner", 	0x0231D, 	0x0 }, 	/* alias ISOAMSC urcorn : mmlalias*/
{ "urcrop", 	0x0230E, 	0x0 }, 	/* upward right crop mark  : 9573-2003-isopub*/
{ "urdrshar", 	0x0294F, 	0x0 }, 	/*  : STIX*/
{ "urharb", 	0x02954, 	0x0 }, 	/*  : STIX*/
{ "uring", 	0x0016F, 	0x0 }, 	/* =small u, ring : 9573-2003-isolat2*/
{ "urtri", 	0x025F9, 	0x0 }, 	/* upper right triangle : 9573-2003-isoamso*/
{ "urtrif", 	0x025E5, 	0x0 }, 	/*  : STIX*/
{ "uscr", 	0x1D4CA, 	0x0 }, 	/* /scr u, script letter u : 9573-2003-isomscr*/
{ "utdot", 	0x022F0, 	0x0 }, 	/* three dots, ascending : 9573-2003-isotech*/
{ "utilde", 	0x00169, 	0x0 }, 	/* =small u, tilde : 9573-2003-isolat2*/
{ "utri", 	0x025B5, 	0x0 }, 	/* /triangle =up triangle, open : 9573-2003-isopub*/
{ "utrif", 	0x025B4, 	0x0 }, 	/* /blacktriangle =up tri, filled : 9573-2003-isopub*/
{ "uuarr", 	0x021C8, 	0x0 }, 	/* /upuparrows A: two up arrows : 9573-2003-isoamsa*/
{ "uuml", 	0x000FC, 	0x0 }, 	/* =small u, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "uwangle", 	0x029A7, 	0x0 }, 	/* large upward pointing angle : 9573-2003-isotech*/
{ "vArr", 	0x021D5, 	0x0 }, 	/* /Updownarrow A: up&down dbl arrow : 9573-2003-isoamsa*/
{ "vBar", 	0x02AE8, 	0x0 }, 	/* vert, dbl bar (under) : 9573-2003-isoamsr*/
{ "vBarv", 	0x02AE9, 	0x0 }, 	/* dbl bar, vert over and under : 9573-2003-isoamsr*/
{ "vDash", 	0x022A8, 	0x0 }, 	/* /vDash R: vertical, dbl dash : 9573-2003-isoamsr*/
{ "vDdash", 	0x02AE2, 	0x0 }, 	/*  : STIX*/
{ "vangrt", 	0x0299C, 	0x0 }, 	/* right angle, variant : 9573-2003-isotech*/
{ "varepsilon", 	0x003F5, 	0x0 }, 	/* alias ISOGRK3 epsiv : mmlalias*/
{ "varkappa", 	0x003F0, 	0x0 }, 	/* alias ISOGRK3 kappav : mmlalias*/
{ "varnothing", 	0x02205, 	0x0 }, 	/* alias ISOAMSO emptyv : mmlalias*/
{ "varphi", 	0x003D5, 	0x0 }, 	/* alias ISOGRK3 phiv : mmlalias*/
{ "varpi", 	0x003D6, 	0x0 }, 	/* alias ISOGRK3 piv : mmlalias*/
{ "varpropto", 	0x0221D, 	0x0 }, 	/* alias ISOAMSR vprop : mmlalias*/
{ "varr", 	0x02195, 	0x0 }, 	/* /updownarrow A: up&down arrow : 9573-2003-isoamsa*/
{ "varrho", 	0x003F1, 	0x0 }, 	/* alias ISOGRK3 rhov : mmlalias*/
{ "varsigma", 	0x003C2, 	0x0 }, 	/* alias ISOGRK3 sigmav : mmlalias*/
{ "varsubsetneq", 	0x0228A, 	0x0FE00 }, 	/* alias ISOAMSN vsubne : mmlalias*/
{ "varsubsetneqq", 	0x02ACB, 	0x0FE00 }, 	/* alias ISOAMSN vsubnE : mmlalias*/
{ "varsupsetneq", 	0x0228B, 	0x0FE00 }, 	/* alias ISOAMSN vsupne : mmlalias*/
{ "varsupsetneqq", 	0x02ACC, 	0x0FE00 }, 	/* alias ISOAMSN vsupnE : mmlalias*/
{ "vartheta", 	0x003D1, 	0x0 }, 	/* alias ISOGRK3 thetav : mmlalias*/
{ "vartriangleleft", 	0x022B2, 	0x0 }, 	/* alias ISOAMSR vltri : mmlalias*/
{ "vartriangleright", 	0x022B3, 	0x0 }, 	/* alias ISOAMSR vrtri : mmlalias*/
{ "vbrtri", 	0x029D0, 	0x0 }, 	/*  : STIX*/
{ "vcy", 	0x00432, 	0x0 }, 	/* =small ve, Cyrillic : 9573-2003-isocyr1*/
{ "vdash", 	0x022A2, 	0x0 }, 	/* /vdash R: vertical, dash : 9573-2003-isoamsr*/
{ "vee", 	0x02228, 	0x0 }, 	/* alias ISOTECH or : mmlalias*/
{ "veeBar", 	0x02A63, 	0x0 }, 	/* 225A : STIX*/
{ "veebar", 	0x022BB, 	0x0 }, 	/* /veebar B: logical or, bar below : 9573-2003-isoamsb*/
{ "veebar", 	0x02A61, 	0x0 }, 	/* 22BB : STIX*/
{ "veeeq", 	0x0225A, 	0x0 }, 	/* logical or, equals : 9573-2003-isotech*/
{ "vellip", 	0x022EE, 	0x0 }, 	/* vertical ellipsis : 9573-2003-isopub*/
{ "vellip4", 	0x02999, 	0x0 }, 	/*  : STIX*/
{ "vellipv", 	0x02AF6, 	0x0 }, 	/*  : STIX*/
{ "verbar", 	0x0007C, 	0x0 }, 	/* /vert =vertical bar : 9573-2003-isonum*/
{ "vert", 	0x0007C, 	0x0 }, 	/* alias ISONUM verbar : mmlalias*/
{ "vert3", 	0x02AF4, 	0x0 }, 	/*  : STIX*/
{ "vfr", 	0x1D533, 	0x0 }, 	/* /frak v, lower case v : 9573-2003-isomfrk*/
{ "vldash", 	0x023A3, 	0x0 }, 	/*  : STIX*/
{ "vltri", 	0x022B2, 	0x0 }, 	/* /vartriangleleft R: l tri, open, var : 9573-2003-isoamsr*/
{ "vnsub", 	0x02282, 	0x020D2 }, 	/* /nsubset N: not subset, var : 9573-2003-isoamsn*/
{ "vnsup", 	0x02283, 	0x020D2 }, 	/* /nsupset N: not superset, var : 9573-2003-isoamsn*/
{ "vopf", 	0x1D567, 	0x0 }, 	/*  : mmlextra*/
{ "vprime", 	0x02032, 	0x0 }, 	/* /varprime - prime, variant : 8879-isoamso*/
{ "vprop", 	0x0221D, 	0x0 }, 	/* /varpropto R: proportional, variant : 9573-2003-isoamsr*/
{ "vrtri", 	0x022B3, 	0x0 }, 	/* /vartriangleright R: r tri, open, var : 9573-2003-isoamsr*/
{ "vscr", 	0x1D4CB, 	0x0 }, 	/* /scr v, script letter v : 9573-2003-isomscr*/
{ "vsubnE", 	0x02ACB, 	0x0FE00 }, 	/* /varsubsetneqq N: subset not dbl eq, var : 9573-2003-isoamsn*/
{ "vsubne", 	0x0228A, 	0x0FE00 }, 	/* /varsubsetneq N: subset, not eq, var : 9573-2003-isoamsn*/
{ "vsupnE", 	0x02ACC, 	0x0FE00 }, 	/* /varsupsetneqq N: super not dbl eq, var : 9573-2003-isoamsn*/
{ "vsupne", 	0x0228B, 	0x0FE00 }, 	/* /varsupsetneq N: superset, not eq, var : 9573-2003-isoamsn*/
{ "vzigzag", 	0x0299A, 	0x0 }, 	/* vertical zig-zag line : 9573-2003-isoamso*/
{ "wcirc", 	0x00175, 	0x0 }, 	/* =small w, circumflex accent : 9573-2003-isolat2*/
{ "wedbar", 	0x02A5F, 	0x0 }, 	/* wedge, bar below : 9573-2003-isoamsb*/
{ "wedge", 	0x02227, 	0x0 }, 	/* alias ISOTECH and : mmlalias*/
{ "wedgeq", 	0x02259, 	0x0 }, 	/* /wedgeq R: corresponds to (wedge, equals) : 9573-2003-isotech*/
{ "weierp", 	0x02118, 	0x0 }, 	/* /wp - Weierstrass p : 9573-2003-isoamso*/
{ "wfr", 	0x1D534, 	0x0 }, 	/* /frak w, lower case w : 9573-2003-isomfrk*/
{ "wopf", 	0x1D568, 	0x0 }, 	/*  : mmlextra*/
{ "wp", 	0x02118, 	0x0 }, 	/* alias ISOAMSO weierp : mmlalias*/
{ "wr", 	0x02240, 	0x0 }, 	/* alias ISOAMSB wreath : mmlalias*/
{ "wreath", 	0x02240, 	0x0 }, 	/* /wr B: wreath product : 9573-2003-isoamsb*/
{ "wscr", 	0x1D4CC, 	0x0 }, 	/* /scr w, script letter w : 9573-2003-isomscr*/
{ "xandand", 	0x02A07, 	0x0 }, 	/*  : STIX*/
{ "xbsol", 	0x02571, 	0x0 }, 	/*  : STIX*/
{ "xcap", 	0x022C2, 	0x0 }, 	/* /bigcap L: intersection operator : 9573-2003-isoamsb*/
{ "xcirc", 	0x025EF, 	0x0 }, 	/* /bigcirc B: large circle : 9573-2003-isoamsb*/
{ "xcup", 	0x022C3, 	0x0 }, 	/* /bigcup L: union operator : 9573-2003-isoamsb*/
{ "xcupdot", 	0x02A03, 	0x0 }, 	/*  : STIX*/
{ "xdtri", 	0x025BD, 	0x0 }, 	/* /bigtriangledown B: big dn tri, open : 9573-2003-isoamsb*/
{ "xfr", 	0x1D535, 	0x0 }, 	/* /frak x, lower case x : 9573-2003-isomfrk*/
{ "xgr", 	0x003BE, 	0x0 }, 	/* =small xi, Greek : 9573-2003-isogrk1*/
{ "xhArr", 	0x027FA, 	0x0 }, 	/* /Longleftrightarrow A: long l&r dbl arr : 9573-2003-isoamsa*/
{ "xharr", 	0x027F7, 	0x0 }, 	/* /longleftrightarrow A: long l&r arr : 9573-2003-isoamsa*/
{ "xi", 	0x003BE, 	0x0 }, 	/* /xi small xi, Greek : 9573-2003-isogrk3*/
{ "xlArr", 	0x027F8, 	0x0 }, 	/* /Longleftarrow A: long l dbl arrow : 9573-2003-isoamsa*/
{ "xlarr", 	0x027F5, 	0x0 }, 	/* /longleftarrow A: long left arrow : 9573-2003-isoamsa*/
{ "xmap", 	0x027FC, 	0x0 }, 	/* /longmapsto A: : 9573-2003-isoamsa*/
{ "xnis", 	0x022FB, 	0x0 }, 	/* large contains, vertical bar on horizontal stroke : 9573-2003-isotech*/
{ "xodot", 	0x02A00, 	0x0 }, 	/* /bigodot L: circle dot operator : 9573-2003-isoamsb*/
{ "xopf", 	0x1D569, 	0x0 }, 	/*  : mmlextra*/
{ "xoplus", 	0x02A01, 	0x0 }, 	/* /bigoplus L: circle plus operator : 9573-2003-isoamsb*/
{ "xoror", 	0x02A08, 	0x0 }, 	/*  : STIX*/
{ "xotime", 	0x02A02, 	0x0 }, 	/* /bigotimes L: circle times operator : 9573-2003-isoamsb*/
{ "xrArr", 	0x027F9, 	0x0 }, 	/* /Longrightarrow A: long rt dbl arr : 9573-2003-isoamsa*/
{ "xrarr", 	0x027F6, 	0x0 }, 	/* /longrightarrow A: long right arrow : 9573-2003-isoamsa*/
{ "xscr", 	0x1D4CD, 	0x0 }, 	/* /scr x, script letter x : 9573-2003-isomscr*/
{ "xsol", 	0x02572, 	0x0 }, 	/*  : STIX*/
{ "xsqcap", 	0x02A05, 	0x0 }, 	/* 2293 : STIX*/
{ "xsqcup", 	0x02A06, 	0x0 }, 	/*  : STIX*/
{ "xsqu", 	0x025FB, 	0x0 }, 	/*  : STIX*/
{ "xsquf", 	0x025FC, 	0x0 }, 	/*  : STIX*/
{ "xtimes", 	0x02A09, 	0x0 }, 	/*  : STIX*/
{ "xuplus", 	0x02A04, 	0x0 }, 	/*  : STIX*/
{ "xutri", 	0x025B3, 	0x0 }, 	/* /bigtriangleup B: big up tri, open : 9573-2003-isoamsb*/
{ "xvee", 	0x022C1, 	0x0 }, 	/* /bigvee L: logical or operator : 9573-2003-isoamsb*/
{ "xwedge", 	0x022C0, 	0x0 }, 	/* /bigwedge L: logical and operator : 9573-2003-isoamsb*/
{ "yacute", 	0x000FD, 	0x0 }, 	/* =small y, acute accent : 9573-2003-isolat1*/
{ "yacy", 	0x0044F, 	0x0 }, 	/* =small ya, Cyrillic : 9573-2003-isocyr1*/
{ "ycirc", 	0x00177, 	0x0 }, 	/* =small y, circumflex accent : 9573-2003-isolat2*/
{ "ycy", 	0x0044B, 	0x0 }, 	/* =small yeru, Cyrillic : 9573-2003-isocyr1*/
{ "yen", 	0x000A5, 	0x0 }, 	/* /yen =yen sign : 9573-2003-isonum*/
{ "yfr", 	0x1D536, 	0x0 }, 	/* /frak y, lower case y : 9573-2003-isomfrk*/
{ "yicy", 	0x00457, 	0x0 }, 	/* =small yi, Ukrainian : 9573-2003-isocyr2*/
{ "yopf", 	0x1D56A, 	0x0 }, 	/*  : mmlextra*/
{ "yscr", 	0x1D4CE, 	0x0 }, 	/* /scr y, script letter y : 9573-2003-isomscr*/
{ "yucy", 	0x0044E, 	0x0 }, 	/* =small yu, Cyrillic : 9573-2003-isocyr1*/
{ "yuml", 	0x000FF, 	0x0 }, 	/* =small y, dieresis or umlaut mark : 9573-2003-isolat1*/
{ "zacute", 	0x0017A, 	0x0 }, 	/* =small z, acute accent : 9573-2003-isolat2*/
{ "zcaron", 	0x0017E, 	0x0 }, 	/* =small z, caron : 9573-2003-isolat2*/
{ "zcy", 	0x00437, 	0x0 }, 	/* =small ze, Cyrillic : 9573-2003-isocyr1*/
{ "zdot", 	0x0017C, 	0x0 }, 	/* =small z, dot above : 9573-2003-isolat2*/
{ "zeetrf", 	0x02128, 	0x0 }, 	/* zee transform : mmlalias*/
{ "zeta", 	0x003B6, 	0x0 }, 	/* /zeta small zeta, Greek : 9573-2003-isogrk3*/
{ "zfr", 	0x1D537, 	0x0 }, 	/* /frak z, lower case z : 9573-2003-isomfrk*/
{ "zgr", 	0x003B6, 	0x0 }, 	/* =small zeta, Greek : 9573-2003-isogrk1*/
{ "zhcy", 	0x00436, 	0x0 }, 	/* =small zhe, Cyrillic : 9573-2003-isocyr1*/
{ "zigrarr", 	0x021DD, 	0x0 }, 	/* right zig-zag arrow : 9573-2003-isoamsa*/
{ "zopf", 	0x1D56B, 	0x0 }, 	/*  : mmlextra*/
{ "zscr", 	0x1D4CF, 	0x0 }, 	/* /scr z, script letter z : 9573-2003-isomscr*/
{ "zwj", 	0x0200D, 	0x0 }, 	/*  : xhtml1-special*/
{ "zwnj", 	0x0200C, 	0x0 }, 	/*  : xhtml1-special*/
